project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - datos/

website:
  title: "Perú HC"
  description: "Implementación de Huellas de Carbono por parte del INEI de Perú"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
