<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Renato Vargas">
<meta name="author" content="Lisbeth Rivas">

<title>Huellas de carbono nacionales: concepto, método y experiencias internacionales – Perú HC</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-cd3eb1407d048ed404cff86421788ee8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Perú HC</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../../materiales/documentos/contexto-huella-de-carbono-peru/index.html" aria-current="page"> 
<span class="menu-text">Materiales</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">Acerca de</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../materiales/documentos/contexto-huella-de-carbono-peru/index.html">Documentos</a></li><li class="breadcrumb-item"><a href="../../../materiales/documentos/contexto-huella-de-carbono-peru/index.html">Huellas de carbono</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Documentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../materiales/documentos/contexto-huella-de-carbono-peru/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Huellas de carbono</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Presentaciones</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../materiales/presentaciones/00-contexto-huella-de-carbono.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Huellas de carbono</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../materiales/presentaciones/01-intro-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Álgebra matricial para insumo-producto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../materiales/presentaciones/02-modelo-insumo-producto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">El modelo de insumo-producto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../materiales/presentaciones/03-extension-ambiental.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extensión ambiental y multiplicadores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../materiales/presentaciones/04-matrices-rectangulares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matrices rectangulares de insumo-producto</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#el-concepto-de-huella-de-carbono" id="toc-el-concepto-de-huella-de-carbono" class="nav-link" data-scroll-target="#el-concepto-de-huella-de-carbono"><span class="header-section-number">2</span> El concepto de huella de carbono</a>
  <ul class="collapse">
  <li><a href="#un-término-con-varios-significados" id="toc-un-término-con-varios-significados" class="nav-link" data-scroll-target="#un-término-con-varios-significados"><span class="header-section-number">2.1</span> Un término con varios significados</a></li>
  <li><a href="#tres-formas-de-asignar-las-emisiones" id="toc-tres-formas-de-asignar-las-emisiones" class="nav-link" data-scroll-target="#tres-formas-de-asignar-las-emisiones"><span class="header-section-number">2.2</span> Tres formas de asignar las emisiones</a></li>
  <li><a href="#territorio-y-residencia" id="toc-territorio-y-residencia" class="nav-link" data-scroll-target="#territorio-y-residencia"><span class="header-section-number">2.3</span> Territorio y residencia</a></li>
  <li><a href="#gases-y-unidad-de-medida" id="toc-gases-y-unidad-de-medida" class="nav-link" data-scroll-target="#gases-y-unidad-de-medida"><span class="header-section-number">2.4</span> Gases y unidad de medida</a></li>
  </ul></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">3</span> Metodología</a>
  <ul class="collapse">
  <li><a href="#datos-necesarios" id="toc-datos-necesarios" class="nav-link" data-scroll-target="#datos-necesarios"><span class="header-section-number">3.1</span> Datos necesarios</a></li>
  <li><a href="#cálculo" id="toc-cálculo" class="nav-link" data-scroll-target="#cálculo"><span class="header-section-number">3.2</span> Cálculo</a></li>
  <li><a href="#tratamiento-de-las-importaciones" id="toc-tratamiento-de-las-importaciones" class="nav-link" data-scroll-target="#tratamiento-de-las-importaciones"><span class="header-section-number">3.3</span> Tratamiento de las importaciones</a></li>
  <li><a href="#problemas-habituales-de-compilación" id="toc-problemas-habituales-de-compilación" class="nav-link" data-scroll-target="#problemas-habituales-de-compilación"><span class="header-section-number">3.4</span> Problemas habituales de compilación</a></li>
  </ul></li>
  <li><a href="#usos-de-política" id="toc-usos-de-política" class="nav-link" data-scroll-target="#usos-de-política"><span class="header-section-number">4</span> Usos de política</a></li>
  <li><a href="#evidencia-global-y-posición-de-américa-latina" id="toc-evidencia-global-y-posición-de-américa-latina" class="nav-link" data-scroll-target="#evidencia-global-y-posición-de-américa-latina"><span class="header-section-number">5</span> Evidencia global y posición de América Latina</a>
  <ul class="collapse">
  <li><a href="#cifras-globales" id="toc-cifras-globales" class="nav-link" data-scroll-target="#cifras-globales"><span class="header-section-number">5.1</span> Cifras globales</a></li>
  <li><a href="#américa-latina-en-las-cifras-de-la-ocde" id="toc-américa-latina-en-las-cifras-de-la-ocde" class="nav-link" data-scroll-target="#américa-latina-en-las-cifras-de-la-ocde"><span class="header-section-number">5.2</span> América Latina en las cifras de la OCDE</a></li>
  </ul></li>
  <li><a href="#experiencias-internacionales" id="toc-experiencias-internacionales" class="nav-link" data-scroll-target="#experiencias-internacionales"><span class="header-section-number">6</span> Experiencias internacionales</a>
  <ul class="collapse">
  <li><a href="#prácticas-oficiales" id="toc-prácticas-oficiales" class="nav-link" data-scroll-target="#prácticas-oficiales"><span class="header-section-number">6.1</span> Prácticas oficiales</a></li>
  <li><a href="#referencias-de-la-ocde-y-de-la-literatura-científica" id="toc-referencias-de-la-ocde-y-de-la-literatura-científica" class="nav-link" data-scroll-target="#referencias-de-la-ocde-y-de-la-literatura-científica"><span class="header-section-number">6.2</span> Referencias de la OCDE y de la literatura científica</a></li>
  <li><a href="#bases-multirregionales" id="toc-bases-multirregionales" class="nav-link" data-scroll-target="#bases-multirregionales"><span class="header-section-number">6.3</span> Bases multirregionales</a></li>
  <li><a href="#américa-latina" id="toc-américa-latina" class="nav-link" data-scroll-target="#américa-latina"><span class="header-section-number">6.4</span> América Latina</a></li>
  <li><a href="#lecciones-comunes" id="toc-lecciones-comunes" class="nav-link" data-scroll-target="#lecciones-comunes"><span class="header-section-number">6.5</span> Lecciones comunes</a></li>
  </ul></li>
  <li><a href="#consideraciones-de-diseño" id="toc-consideraciones-de-diseño" class="nav-link" data-scroll-target="#consideraciones-de-diseño"><span class="header-section-number">7</span> Consideraciones de diseño</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  <li><a href="#anexo-a.-glosario" id="toc-anexo-a.-glosario" class="nav-link" data-scroll-target="#anexo-a.-glosario">Anexo A. Glosario</a></li>
  <li><a href="#anexo-b.-contexto-de-la-asistencia-técnica-del-fmi-a-perú" id="toc-anexo-b.-contexto-de-la-asistencia-técnica-del-fmi-a-perú" class="nav-link" data-scroll-target="#anexo-b.-contexto-de-la-asistencia-técnica-del-fmi-a-perú">Anexo B. Contexto de la asistencia técnica del FMI a Perú</a>
  <ul class="collapse">
  <li><a href="#antecedentes" id="toc-antecedentes" class="nav-link" data-scroll-target="#antecedentes">Antecedentes</a></li>
  <li><a href="#disponibilidad-de-datos" id="toc-disponibilidad-de-datos" class="nav-link" data-scroll-target="#disponibilidad-de-datos">Disponibilidad de datos</a></li>
  <li><a href="#secuencia-de-compilación-sugerida" id="toc-secuencia-de-compilación-sugerida" class="nav-link" data-scroll-target="#secuencia-de-compilación-sugerida">Secuencia de compilación sugerida</a></li>
  <li><a href="#problemas-específicos-y-decisiones" id="toc-problemas-específicos-y-decisiones" class="nav-link" data-scroll-target="#problemas-específicos-y-decisiones">Problemas específicos y decisiones</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../materiales/documentos/contexto-huella-de-carbono-peru/index.html">Documentos</a></li><li class="breadcrumb-item"><a href="../../../materiales/documentos/contexto-huella-de-carbono-peru/index.html">Huellas de carbono</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Huellas de carbono nacionales: concepto, método y experiencias internacionales</h1>
<p class="subtitle lead">Una nota de contexto para oficinas de estadística</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autores/as</div>
  <div class="quarto-title-meta-heading">Afiliaciones</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Renato Vargas </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Economista / Consultor FMI
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Lisbeth Rivas </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Economista Senior FMI
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    <p>Las huellas de carbono nacionales miden las emisiones que provoca la demanda final de un país, sin importar dónde ocurren. Esta nota explica el concepto, describe el método de insumo-producto ambientalmente extendido que las sustenta y revisa la evidencia global y las experiencias de oficinas de estadística, organismos internacionales e investigadores, con atención a América Latina. Concluye con los problemas habituales de compilación y con las decisiones de diseño que enfrenta una oficina que inicia el trabajo. Dos anexos incluyen un glosario de términos técnicos y el contexto de la asistencia técnica a Perú que motivó el documento.</p>
  </div>
</div>


</header>


<section id="introducción" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">1</span> Introducción</h2>
<p>Los compromisos internacionales de mitigación se miden, en general, con inventarios de emisiones que registran lo que ocurre dentro del territorio de cada país <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015</a>)</span>. Ese enfoque tiene ventajas claras: se apoya en estadísticas de combustibles y en metodologías acordadas, y permite verificar el cumplimiento de metas. Deja fuera, sin embargo, una pregunta que cobra importancia en el debate de política: cuántas emisiones se generan para sostener el consumo de un país, incluidas las que ocurren en otros países que producen los bienes que ese país importa.</p>
<p>La magnitud de esa diferencia es considerable. Estudios de referencia estiman que entre una quinta parte y algo más de una cuarta parte de las emisiones mundiales de CO2 se asocia con bienes que cruzan fronteras <span class="citation" data-cites="davis2010 peters2011 yamano2020">(<a href="#ref-davis2010" role="doc-biblioref">Davis y Caldeira, 2010</a>; <a href="#ref-peters2011" role="doc-biblioref">Peters et&nbsp;al., 2011</a>; <a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. La distinción también tiene consecuencias para el diseño de políticas. Cuando los países con metas ambiciosas reducen sus emisiones territoriales, parte de la reducción puede reflejar el traslado de producción a economías con tecnologías más intensivas en carbono, de modo que las emisiones regresan al consumo del país en forma de importaciones <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. El debate sobre qué parte de la carga de mitigación corresponde a cada país, que se remonta al principio de responsabilidades comunes pero diferenciadas del Protocolo de Kioto, depende en buena medida de cómo se asignen las emisiones <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</p>
<p>La huella de carbono nacional responde a esa pregunta. Es una estadística que asigna a la demanda final de los residentes de un país las emisiones generadas en toda la cadena de producción, dentro y fuera de su territorio. Varias oficinas de estadística y organismos internacionales la publican de forma regular, entre ellos el Departamento de Medio Ambiente del Reino Unido y Eurostat <span class="citation" data-cites="defra2026 eurostatghgfp">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>; <a href="#ref-eurostatghgfp" role="doc-biblioref">Eurostat, 2026</a>)</span>. Su cálculo descansa en las cuentas de emisiones atmosféricas del Marco Central del SEEA, que comparten la estructura de los cuadros de oferta y utilización de las cuentas nacionales y pueden, por tanto, combinarse con ellos en un modelo de insumo-producto <span class="citation" data-cites="eurostat2015 seea2014">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015</a>; <a href="#ref-seea2014" role="doc-biblioref">United Nations, 2014</a>)</span>.</p>
<p>Esta nota ofrece una introducción al tema para quienes compilan o utilizan estas estadísticas. La sección 2 aclara el concepto y lo distingue de otros usos del término. La sección 3 describe el método, y la sección 4 resume los usos de política. La sección 5 presenta la evidencia global y la posición de América Latina, y la sección 6 revisa las experiencias de oficinas de estadística, de bases de datos multirregionales y de estudios latinoamericanos. La sección 7 reúne las consideraciones de diseño. El documento se limita a la huella nacional basada en la demanda final; las huellas de producto y de organización se mencionan solo para evitar confusiones. Dos anexos completan el documento: el anexo A ofrece un glosario de términos técnicos, y el anexo B describe el contexto de la asistencia técnica del FMI al Instituto Nacional de Estadística e Informática (INEI) de Perú, que motivó la preparación de esta nota.</p>
</section>
<section id="el-concepto-de-huella-de-carbono" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="el-concepto-de-huella-de-carbono"><span class="header-section-number">2</span> El concepto de huella de carbono</h2>
<section id="un-término-con-varios-significados" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="un-término-con-varios-significados"><span class="header-section-number">2.1</span> Un término con varios significados</h3>
<p>La expresión huella de carbono se usa con sentidos distintos y no existe una definición de aceptación general <span class="citation" data-cites="espindola2012">(<a href="#ref-espindola2012" role="doc-biblioref">Espíndola y Valderrama, 2012</a>)</span>. En el ámbito empresarial predominan las huellas de producto y de organización. Se calculan con métodos de abajo hacia arriba, como el análisis de ciclo de vida, y siguen referencias como el GHG Protocol, la especificación PAS 2050 o las normas ISO 14040 y 14044 <span class="citation" data-cites="espindola2012 frohmann2013">(<a href="#ref-espindola2012" role="doc-biblioref">Espíndola y Valderrama, 2012</a>; <a href="#ref-frohmann2013" role="doc-biblioref">Frohmann y Olmos, 2013</a>)</span>. Una empresa que mide las emisiones de su producción, o de un producto a lo largo de su vida útil, produce una huella de este tipo.</p>
<p>Las estadísticas oficiales usan el término con otro sentido. El Reino Unido, que publica una serie oficial desde 2012, define su huella como las emisiones de gases de efecto invernadero asociadas con el gasto de consumo de los residentes, en cualquier lugar del mundo donde ocurran a lo largo de la cadena de suministro, más las emisiones directas de los hogares por el uso de combustibles <span class="citation" data-cites="defra2026">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>)</span>. El manual de Eurostat describe la misma perspectiva como cuentas de emisiones basadas en el consumo, que resultan de un modelo y se conocen también como huellas de carbono <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, sec. 8</a>)</span>. Ese es el sentido que se adopta en esta nota.</p>
<p>El término tiene además una historia más larga que su uso reciente. Los métodos de insumo-producto en que se apoya la huella nacional se remontan a los trabajos de Leontief de la década de 1970, y la literatura sobre huellas creció con rapidez en los años previos a 2012 <span class="citation" data-cites="espindola2012">(<a href="#ref-espindola2012" role="doc-biblioref">Espíndola y Valderrama, 2012</a>)</span>. Las definiciones difieren según la fuente: algunas miden solo CO2 y otras toda la canasta de gases del Protocolo de Kioto; algunas se limitan a las emisiones directas y otras incluyen toda la cadena de suministro. Los métodos también tienen ventajas y costos distintos. El de abajo hacia arriba modela procesos concretos y es preciso para un producto definido, pero corta la cadena en un límite arbitrario, lo que genera un error de truncamiento de tamaño desconocido. El de insumo-producto cubre toda la economía a costa de usar promedios sectoriales. Por eso una propuesta frecuente es combinar ambos en un enfoque híbrido <span class="citation" data-cites="espindola2012">(<a href="#ref-espindola2012" role="doc-biblioref">Espíndola y Valderrama, 2012</a>)</span>. Tampoco existe una norma internacional única: la norma ISO 14067 sobre huella de producto quedó como especificación técnica y no como norma <span class="citation" data-cites="frohmann2013">(<a href="#ref-frohmann2013" role="doc-biblioref">Frohmann y Olmos, 2013</a>)</span>.</p>
</section>
<section id="tres-formas-de-asignar-las-emisiones" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="tres-formas-de-asignar-las-emisiones"><span class="header-section-number">2.2</span> Tres formas de asignar las emisiones</h3>
<p>Para entender qué mide la huella conviene situarla frente a otras dos formas de contar las emisiones. La OCDE distingue tres enfoques de asignación <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>, que resume el <strong>?@tbl-enfoques</strong>. El primero es el territorial, propio de los inventarios que los países reportan a la Convención Marco de las Naciones Unidas sobre el Cambio Climático (CMNUCC) y de las estadísticas de la Agencia Internacional de Energía (AIE). El segundo es el de producción, o de residencia, que sigue la lógica de las cuentas nacionales y se aplica en las cuentas de emisiones atmosféricas. El tercero es el de demanda final, que corresponde a la huella.</p>
<table class="caption-top table">
<caption>Enfoques de asignación de emisiones</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Enfoque</th>
<th style="text-align: left;">Qué cuenta</th>
<th style="text-align: left;">Fuentes típicas</th>
<th style="text-align: left;">Pregunta que responde</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Territorial</td>
<td style="text-align: left;">Combustibles comprados y quemados en el territorio, incluidos los de no residentes</td>
<td style="text-align: left;">Inventarios de la CMNUCC y estadísticas de la AIE</td>
<td style="text-align: left;">¿Cuánto se emite dentro de las fronteras?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Producción (residencia)</td>
<td style="text-align: left;">Emisiones de industrias y hogares residentes, dentro y fuera del territorio</td>
<td style="text-align: left;">Cuentas de emisiones atmosféricas (SEEA)</td>
<td style="text-align: left;">¿Qué actividades económicas emiten?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Demanda final (huella)</td>
<td style="text-align: left;">Emisiones de todas las etapas de producción asociadas con la demanda final de los residentes</td>
<td style="text-align: left;">Cuentas de emisiones y tablas de insumo-producto</td>
<td style="text-align: left;">¿Qué consumo, inversión o exportación provoca las emisiones?</td>
</tr>
</tbody>
</table>
<p>Los tres enfoques son consistentes entre sí. A escala mundial, las emisiones basadas en la demanda y las basadas en la producción suman lo mismo; la diferencia aparece entre países, como resultado del comercio <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. Un país cuyo consumo depende de bienes importados intensivos en emisiones tendrá una huella mayor que sus emisiones de producción, y lo contrario ocurre en un país exportador de esos bienes.</p>
</section>
<section id="territorio-y-residencia" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="territorio-y-residencia"><span class="header-section-number">2.3</span> Territorio y residencia</h3>
<p>La diferencia entre el primer y el segundo enfoque merece atención, porque es la que más ajustes exige al compilar. Las cuentas de emisiones atmosféricas registran las emisiones de las unidades residentes de una economía, sin importar dónde ocurren, con el mismo criterio de residencia de las cuentas nacionales. Los inventarios de la CMNUCC, en cambio, siguen el principio territorial y registran lo emitido en el territorio, sin importar quién lo emite <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 3</a> y 37)</span>.</p>
<p>El manual de Eurostat ilustra la diferencia con una aerolínea residente en Irlanda: las emisiones de uno de sus vuelos entre Fráncfort y Nueva York se registran en la cuenta irlandesa, porque la utilidad del vuelo contribuye al producto interno bruto de Irlanda <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 35</a>)</span>. Lo mismo vale para embarcaciones pesqueras, camiones de carga y turistas que conducen vehículos en el extranjero: las cuentas asignan las emisiones al operador del vehículo y a su país de residencia <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 40</a>)</span>. En economías pequeñas, con mucho tránsito internacional, las diferencias entre ambos criterios pueden ser grandes en relación con los totales nacionales <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 36</a>)</span>.</p>
<p>Los compiladores hacen explícita la conciliación entre ambos criterios mediante las llamadas partidas puente, que muestran las diferencias entre el total de la cuenta y el total del inventario. El transporte internacional es la fuente principal de esas diferencias <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 39</a>)</span>. La <a href="#fig-residencia" class="quarto-xref">Figura&nbsp;1</a> ilustra la diferencia con dos elipses: una delimita las emisiones de los residentes, que incluye lo que ocurre en el resto del mundo, y la otra las del territorio, que incluye lo que emiten los no residentes.</p>
<div id="fig-residencia" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-residencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paste-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-residencia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Definición geográfica y económica (de residencia) de un país. Fuente: Eurostat (2015), figura 3.
</figcaption>
</figure>
</div>
</section>
<section id="gases-y-unidad-de-medida" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="gases-y-unidad-de-medida"><span class="header-section-number">2.4</span> Gases y unidad de medida</h3>
<p>Las cuentas cubren seis gases de efecto invernadero: CO2, N2O, CH4, HFC, PFC y SF6, con el NF3 incorporado recientemente al reporte. Se expresan en CO2 equivalente mediante potenciales de calentamiento global <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, sec. 3.1</a>)</span>. Algunas fuentes, como la serie de la OCDE que se usa en la sección 5, incluyen solo el CO2 por combustión de combustibles fósiles <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. La diferencia importa en economías donde la agricultura o el cambio de uso de suelo pesan mucho en las emisiones totales, porque esas fuentes quedan fuera de las series de combustión.</p>
</section>
</section>
<section id="metodología" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metodología"><span class="header-section-number">3</span> Metodología</h2>
<section id="datos-necesarios" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="datos-necesarios"><span class="header-section-number">3.1</span> Datos necesarios</h3>
<p>El cálculo de una huella nacional combina tres insumos: tablas de insumo-producto, que pueden derivarse de los cuadros de oferta y utilización; medidas de las emisiones directas; y cuentas de emisiones atmosféricas, que asignan las emisiones a las actividades económicas con las mismas clasificaciones de las cuentas nacionales. Estas últimas siguen las estructuras y los principios del Marco Central del SEEA y son coherentes con los datos monetarios del Sistema de Cuentas Nacionales <span class="citation" data-cites="seea2014 sna2009">(<a href="#ref-sna2009" role="doc-biblioref">United Nations, 2009</a>, <a href="#ref-seea2014" role="doc-biblioref">2014</a>)</span>.</p>
<p>Esa coherencia es lo que vuelve posible el modelo: como las cuentas físicas y los cuadros monetarios comparten clasificaciones, las emisiones por industria pueden vincularse directamente con el producto de cada industria. La cuenta debe además tener el desglose completo por actividad económica (en Eurostat, la lista A*64 de la NACE); sin él, las huellas y las descomposiciones no son posibles o pierden valor <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 118</a>)</span>.</p>
<p>La compilación de la cuenta de emisiones, que suele ser el insumo menos familiar para una oficina de cuentas nacionales, admite dos rutas según el manual de Eurostat. En la primera se parte de los inventarios que se reportan a la CMNUCC y se reasignan a industrias y hogares. En la segunda se parte de las estadísticas de energía, idealmente de las cuentas físicas de flujos de energía, que ya siguen el criterio de residencia, y se aplican los mismos factores de emisión del inventario para la combustión, mientras las emisiones que no provienen de la combustión se toman de los inventarios <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 141</a> a 151)</span>. La combustión explica hasta cerca de 90% del CO2 <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 133</a>)</span>. Sigue el ajuste por residencia: se restan las emisiones de no residentes en el territorio y se suman las de residentes en el exterior. El manual recomienda concentrarse en las partidas grandes y no gastar esfuerzo en ajustes teóricamente correctos pero pequeños <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 190</a>)</span>, y reconoce que el transporte por carretera es una de las partes más difíciles <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 280</a>)</span>. Advierte además que un desglose incompleto por actividad, o la marcación como confidenciales de celdas que no lo son, puede impedir los modelos de huella <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 117</a> a 121)</span>.</p>
</section>
<section id="cálculo" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="cálculo"><span class="header-section-number">3.2</span> Cálculo</h3>
<p>La idea del cálculo es sencilla. Cada industria emite una cantidad conocida por unidad de producto, pero para producir un bien necesita insumos de otras industrias, que a su vez emiten y necesitan insumos. El modelo de insumo-producto suma todas esas rondas de producción, y por eso la huella de un producto incluye las emisiones de sus proveedores directos e indirectos <span class="citation" data-cites="millerblair2022">(<a href="#ref-millerblair2022" role="doc-biblioref">Miller y Blair, 2022</a>)</span>. Sea <span class="math inline">\(\boldsymbol{\varepsilon}\)</span> el vector de coeficientes de emisión por industria (emisiones directas divididas entre el producto bruto), <span class="math inline">\(\mathbf{T}\)</span> la matriz de requerimientos totales del modelo de producto por industria y <span class="math inline">\(\mathbf{f}\)</span> el vector de demanda final por producto. La huella de la demanda final es:</p>
<p><span class="math display">\[
F = \boldsymbol{\varepsilon}'\,\mathbf{T}\,\mathbf{f} + e_h
\]</span></p>
<p>donde <span class="math inline">\(e_h\)</span> son las emisiones directas de los hogares, como el uso de combustibles para transporte y cocción. La OCDE usa una expresión equivalente, <span class="math inline">\(C = \mathbf{eB}\,\mathbf{Y} + HE\)</span>, con la inversa de Leontief de una tabla multirregional <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>, ecuación 7a)</span>.</p>
<p>Un ejemplo del manual de Eurostat aclara la lógica de la asignación. En una economía hipotética sin comercio exterior, el total emitido por las industrias coincidiría con el total asociado con la demanda final. Aun así, las emisiones de la industria A no coincidirían con las emisiones asociadas con el uso final del producto A, porque parte de la producción de A es insumo de otros productos y porque producir A requiere insumos de otras industrias <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 332</a>)</span>. La huella reasigna las emisiones desde donde se producen hacia el uso final que las origina.</p>
<p>Al descomponer <span class="math inline">\(\mathbf{f}\)</span> por producto y por categoría de uso final (consumo de los hogares, consumo del gobierno, formación bruta de capital y exportaciones) se obtienen las dimensiones de análisis habituales <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 337</a>)</span>. Incluir la formación de capital es importante: en el análisis global de <span class="citation" data-cites="hertwich2009">Hertwich y Peters (<a href="#ref-hertwich2009" role="doc-biblioref">2009</a>)</span>, los hogares explican 72% de la huella de gases de efecto invernadero, el gobierno 10% y la inversión 18% (según el resumen del artículo). En una economía abierta, el total asociado con toda la demanda final, exportaciones incluidas, coincide con las emisiones de producción cuando se contabilizan por completo las emisiones incorporadas en las importaciones <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 338</a>)</span>.</p>
</section>
<section id="tratamiento-de-las-importaciones" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="tratamiento-de-las-importaciones"><span class="header-section-number">3.3</span> Tratamiento de las importaciones</h3>
<p>La decisión metodológica más delicada es cómo estimar las emisiones incorporadas en las importaciones. Cuando no se dispone de una tabla multirregional, se usa la tabla nacional como aproximación; esto supone que los bienes importados se producen con la tecnología del país, el llamado supuesto de tecnología doméstica. Con ese supuesto el resultado debe interpretarse con cautela, porque no mide las emisiones reales de los países proveedores: mide las que se evitarían en el país si este produjera las importaciones por sí mismo <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 335</a> y 336)</span>.</p>
<p>Una tabla multirregional resuelve ese límite, porque representa las entregas intermedias y finales entre países y permite vincular el uso final en un país con los insumos y las emisiones de todos los países de la cadena. Su construcción, no obstante, exige muchos datos <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 334</a>)</span>. Por eso la mayoría de las oficinas que publican huellas combinan sus cuadros nacionales con una base multirregional externa, como se verá en la sección 6.</p>
</section>
<section id="problemas-habituales-de-compilación" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="problemas-habituales-de-compilación"><span class="header-section-number">3.4</span> Problemas habituales de compilación</h3>
<p>Las experiencias revisadas en este documento coinciden en un conjunto de dificultades recurrentes, que resume el <strong>?@tbl-problemas-gen</strong>. Muchas de ellas son de naturaleza estadística y no de modelación: provienen de la correspondencia entre clasificaciones y de la coherencia temporal de las fuentes.</p>
<table class="caption-top table">
<caption>Problemas habituales en la compilación de huellas</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 47%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Problema</th>
<th style="text-align: left;">Descripción</th>
<th style="text-align: left;">Evidencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Concordancias</td>
<td style="text-align: left;">Hay que mapear inventarios, cuentas nacionales, encuestas y bases multirregionales; por ejemplo, de los 34 flujos de combustión de la AIE, 11 se relacionan con varias industrias del modelo</td>
<td style="text-align: left;"><span class="citation" data-cites="yamano2020">Yamano y Guilhoto (<a href="#ref-yamano2020" role="doc-biblioref">2020</a>)</span>; <span class="citation" data-cites="hernandez2021">Hernández (<a href="#ref-hernandez2021" role="doc-biblioref">2021</a>)</span>; <span class="citation" data-cites="cachola2021">Cachola y Pacca (<a href="#ref-cachola2021" role="doc-biblioref">2021</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Residencia</td>
<td style="text-align: left;">El transporte internacional, la pesca y el turismo exigen ajustes con fuentes externas</td>
<td style="text-align: left;"><span class="citation" data-cites="eurostat2015">Eurostat (<a href="#ref-eurostat2015" role="doc-biblioref">2015</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Importaciones</td>
<td style="text-align: left;">Supuesto de tecnología doméstica frente a base multirregional</td>
<td style="text-align: left;"><span class="citation" data-cites="eurostat2015">Eurostat (<a href="#ref-eurostat2015" role="doc-biblioref">2015</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Valoración</td>
<td style="text-align: left;">Precios de comprador y precios básicos; márgenes de comercio y transporte; un único tipo de cambio por sector</td>
<td style="text-align: left;"><span class="citation" data-cites="owen2026">Owen (<a href="#ref-owen2026" role="doc-biblioref">2026</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Años de referencia</td>
<td style="text-align: left;">Tablas, inventarios y encuestas de años distintos</td>
<td style="text-align: left;"><span class="citation" data-cites="renner2018">Renner (<a href="#ref-renner2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="owen2026">Owen (<a href="#ref-owen2026" role="doc-biblioref">2026</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Alcance de gases</td>
<td style="text-align: left;">Inclusión o exclusión del cambio de uso de suelo y de los gases distintos del CO2</td>
<td style="text-align: left;"><span class="citation" data-cites="yamano2020">Yamano y Guilhoto (<a href="#ref-yamano2020" role="doc-biblioref">2020</a>)</span>; <span class="citation" data-cites="owen2026">Owen (<a href="#ref-owen2026" role="doc-biblioref">2026</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Revisiones y rezago</td>
<td style="text-align: left;">Las series se revisan en cada edición y se publican con varios años de rezago</td>
<td style="text-align: left;"><span class="citation" data-cites="owen2026">Owen (<a href="#ref-owen2026" role="doc-biblioref">2026</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Gasto de hogares</td>
<td style="text-align: left;">Escalar la encuesta de gasto a los totales de las cuentas nacionales sigue siendo un tema abierto</td>
<td style="text-align: left;"><span class="citation" data-cites="malerba2024">Malerba et&nbsp;al. (<a href="#ref-malerba2024" role="doc-biblioref">2024</a>)</span></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="usos-de-política" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="usos-de-política"><span class="header-section-number">4</span> Usos de política</h2>
<p>La principal ventaja de la huella frente a los inventarios es que permite analizar el efecto ambiental del patrón de consumo y de producción. El manual de Eurostat distingue una perspectiva de producción, que compara el desempeño ambiental de las industrias, y una de consumo, que examina las emisiones directas e indirectas a lo largo de las cadenas internacionales de los productos consumidos y compara las categorías de demanda final <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 307</a>)</span>. Con ella pueden ordenarse los grupos de productos según sus emisiones incorporadas, o medirse cuántas emisiones indirectas activan el consumo, la inversión y, en particular, las exportaciones <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 337</a>)</span>.</p>
<p>La huella también permite medir la productividad del carbono desde la demanda, es decir, el producto interno bruto real generado por unidad de CO2 asociada con la demanda final, una variante de los indicadores de crecimiento verde de la OCDE <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. Combinada con descomposiciones estructurales, separa los cambios de intensidad de emisiones de cada industria, de tecnología y de estructura de la demanda <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 308</a>)</span>. Entre los hallazgos analíticos, <span class="citation" data-cites="hertwich2009">Hertwich y Peters (<a href="#ref-hertwich2009" role="doc-biblioref">2009</a>)</span> encuentran que la alimentación, la vivienda y la movilidad son las categorías de mayor peso en la huella de los hogares (20%, 19% y 17% respectivamente, según el resumen del artículo).</p>
<p>Para la política comercial y climática, la comparación entre emisiones de producción y de consumo es la herramienta más apropiada para evaluar la fuga de carbono, es decir, el traslado de producción intensiva en emisiones a otros países. Los países con metas ambiciosas pueden desacoplar sus emisiones de producción del crecimiento mediante el traslado de producción al exterior, mientras parte de esas emisiones regresa en forma de importaciones intensivas en carbono <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</p>
</section>
<section id="evidencia-global-y-posición-de-américa-latina" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="evidencia-global-y-posición-de-américa-latina"><span class="header-section-number">5</span> Evidencia global y posición de América Latina</h2>
<section id="cifras-globales" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="cifras-globales"><span class="header-section-number">5.1</span> Cifras globales</h3>
<p>Tres estudios de referencia, con bases y años distintos, cuantifican la parte de las emisiones ligada al comercio (<strong>?@tbl-global</strong>). Las cifras no forman una serie homogénea y no deben compararse como tal, pero coinciden en el orden de magnitud y en la tendencia creciente.</p>
<table class="caption-top table">
<caption>Emisiones de CO2 asociadas con el comercio internacional</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 33%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estudio</th>
<th style="text-align: left;">Año</th>
<th style="text-align: left;">Resultado</th>
<th style="text-align: left;">Base de datos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="davis2010">Davis y Caldeira (<a href="#ref-davis2010" role="doc-biblioref">2010</a>)</span></td>
<td style="text-align: left;">2004</td>
<td style="text-align: left;">6.2 Gt de CO2, 23% de las emisiones fósiles, se emitieron en la producción de bienes consumidos en otro país</td>
<td style="text-align: left;">GTAP v7, 113 países o regiones, 57 sectores</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="citation" data-cites="peters2011">Peters et&nbsp;al. (<a href="#ref-peters2011" role="doc-biblioref">2011</a>)</span></td>
<td style="text-align: left;">1990 y 2008</td>
<td style="text-align: left;">Emisiones incorporadas en bienes comerciados: 4.3 Gt (20%) en 1990 y 7.8 Gt (26%) en 2008; la transferencia neta de países en desarrollo a desarrollados pasó de 0.4 a 1.6 Gt</td>
<td style="text-align: left;">113 países, 57 sectores</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="citation" data-cites="yamano2020">Yamano y Guilhoto (<a href="#ref-yamano2020" role="doc-biblioref">2020</a>)</span></td>
<td style="text-align: left;">2015</td>
<td style="text-align: left;">8.8 Gt, cerca de 27% del CO2 de combustión, ligado al comercio internacional</td>
<td style="text-align: left;">ICIO de la OCDE, 65 economías</td>
</tr>
</tbody>
</table>
<p>Los resultados de la OCDE añaden detalle sectorial y por grupo de países. Siete grupos de industrias explican cerca de dos tercios del CO2 incorporado en las exportaciones de 2015, con los productos químicos y minerales no metálicos (18.2%) y los metales básicos (16.1%) a la cabeza <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. Entre los países miembros de la OCDE, las emisiones de producción cayeron 9% entre 2005 y 2015 y las basadas en el consumo, 11%; entre las economías no miembros subieron 47% y 61%, respectivamente <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. La <a href="#fig-oecd-etapas" class="quarto-xref">Figura&nbsp;2</a> muestra cómo se distribuyen las emisiones entre las etapas de producción y por qué la huella de demanda final difiere de la de comercio bruto.</p>
<div id="fig-oecd-etapas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-oecd-etapas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/paste-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-oecd-etapas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Emisiones incorporadas en el comercio y en la demanda final. Fuente: Yamano y Guilhoto (2020), figura 2.1.
</figcaption>
</figure>
</div>
</section>
<section id="américa-latina-en-las-cifras-de-la-ocde" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="américa-latina-en-las-cifras-de-la-ocde"><span class="header-section-number">5.2</span> América Latina en las cifras de la OCDE</h3>
<p>La misma fuente permite situar a los países latinoamericanos incluidos en la base ICIO. Perú sirve de ejemplo de lo que muestran los datos. En 2015, el CO2 de combustión asociado con su demanda final sumó 63.6 Mt, frente a 49.2 Mt emitidos por la producción residente. La diferencia, 14.4 Mt, es el saldo neto de emisiones importadas; en 2005 fue de 2.6 Mt. Entre 2005 y 2015 la producción creció 71% y la huella basada en la demanda, 103% (<a href="#fig-peru" class="quarto-xref">Figura&nbsp;3</a>). Del total asociado con la demanda final, 36.6% se emitió fuera del país en 2015, frente a 32.4% en 2005 (<a href="#fig-ext" class="quarto-xref">Figura&nbsp;4</a>). El <a href="#tbl-oecd" class="quarto-xref">Cuadro&nbsp;1</a> compara a Perú con otros seis países de la región.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-peru" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-peru-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-peru-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-peru-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Perú: emisiones de CO2 por combustión según base de contabilidad, 2005 y 2015 (millones de toneladas). Fuente: Yamano y Guilhoto (2020), anexo D.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ext" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ext-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-ext-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ext-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Parte del CO2 asociado con la demanda final que se emite en el exterior, 2005 y 2015 (porcentaje). Fuente: Yamano y Guilhoto (2020), anexo E.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div id="tbl-oecd" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-oecd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: América Latina: CO2 por combustión según la OCDE, 2015 (millones de toneladas, salvo indicación) y parte emitida en el exterior
</figcaption>
<div aria-describedby="tbl-oecd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">País</th>
<th style="text-align: right;">Producción 2015</th>
<th style="text-align: right;">Demanda final 2015</th>
<th style="text-align: right;">Saldo neto 2015</th>
<th style="text-align: right;">Demanda per cápita 2005 (t)</th>
<th style="text-align: right;">Demanda per cápita 2015 (t)</th>
<th style="text-align: right;">Emitido en el exterior 2015 (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Perú</td>
<td style="text-align: right;">49.2</td>
<td style="text-align: right;">63.6</td>
<td style="text-align: right;">14.4</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">36.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">86.7</td>
<td style="text-align: right;">89.2</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">36.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">82.8</td>
<td style="text-align: right;">97.4</td>
<td style="text-align: right;">14.6</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">34.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">México</td>
<td style="text-align: right;">453.0</td>
<td style="text-align: right;">485.5</td>
<td style="text-align: right;">32.5</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">26.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">195.0</td>
<td style="text-align: right;">216.0</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">3.6</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">18.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brasil</td>
<td style="text-align: right;">461.2</td>
<td style="text-align: right;">475.4</td>
<td style="text-align: right;">14.2</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">2.3</td>
<td style="text-align: right;">21.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Costa Rica</td>
<td style="text-align: right;">8.0</td>
<td style="text-align: right;">13.5</td>
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">52.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Dos advertencias acompañan estas cifras. Primero, se refieren solo al CO2 de combustión, con las tablas ICIO de la edición 2018 de la OCDE, y excluyen el cambio de uso de suelo y las emisiones agropecuarias de CH4 y N2O, que en varios países de la región son relevantes. Segundo, el signo del saldo puede depender de la base y del período: según el resumen de <span class="citation" data-cites="wang2024">Wang et&nbsp;al. (<a href="#ref-wang2024" role="doc-biblioref">2024</a>)</span>, Brasil es el único exportador neto de emisiones incorporadas entre nueve países sudamericanos en 2015-2019, mientras que la OCDE lo muestra como exportador neto en 2005 (321.1 Mt de producción frente a 312.8 Mt de demanda final) y como importador neto en 2015 <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. Las diferencias de alcance y de base de datos explican parte de esa discrepancia, y ejemplifican la sensibilidad de los resultados al método.</p>
</section>
</section>
<section id="experiencias-internacionales" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="experiencias-internacionales"><span class="header-section-number">6</span> Experiencias internacionales</h2>
<p>Esta sección revisa con detalle los casos que sirven de referencia para quien se propone compilar una huella nacional. Se agrupan en cuatro conjuntos: las oficinas de estadística y organismos que publican huellas de forma regular, los trabajos de la OCDE y de la literatura científica que establecieron los métodos y las cifras globales, las bases de datos multirregionales de las que casi todos dependen, y los estudios latinoamericanos, que provienen sobre todo de la academia. Para cada caso se describen los datos y el método, los hallazgos principales, las dificultades que reconocen los propios autores y lo que cabe rescatar para una oficina que inicia el trabajo. Los términos técnicos que aparecen por primera vez se definen en el glosario del anexo A.</p>
<section id="prácticas-oficiales" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="prácticas-oficiales"><span class="header-section-number">6.1</span> Prácticas oficiales</h3>
<section id="reino-unido" class="level4" data-number="6.1.1">
<h4 data-number="6.1.1" class="anchored" data-anchor-id="reino-unido"><span class="header-section-number">6.1.1</span> Reino Unido</h4>
<p>El Reino Unido es el caso más documentado de huella publicada como estadística oficial. El Departamento de Medio Ambiente, Alimentación y Asuntos Rurales (Defra) difunde cada año, desde 2012, la huella de carbono del país y de Inglaterra <span class="citation" data-cites="defra2026">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>)</span>. La construye un equipo de la Universidad de Leeds con un modelo propio, y su metodología se describe en una nota pública de 31 páginas <span class="citation" data-cites="owen2026">(<a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>)</span>. Esa nota distingue tres cuentas que conviene tener presentes porque ilustran, con un mismo país, los tres enfoques de asignación del <strong>?@tbl-enfoques</strong>. La cuenta territorial sigue el inventario nacional que se reporta a la CMNUCC, y trata el transporte aéreo y marítimo internacional solo como partida informativa. La cuenta de producción se apoya en las cuentas ambientales de la oficina de estadística (ONS) y sigue el principio de residencia: incluye el combustible de embarque internacional y las emisiones de residentes en el exterior, y excluye las de no residentes en el territorio y el uso de suelo, el cambio de uso de suelo y la silvicultura. La cuenta de consumo parte de la de producción, resta las emisiones asociadas con las exportaciones y suma las incorporadas en las importaciones <span class="citation" data-cites="owen2026">(<a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>)</span>.</p>
<p><strong>Datos y método.</strong> El modelo, llamado UKMRIO, es una tabla de insumo-producto multirregional con 11 regiones (el Reino Unido, siete economías con detalle propio, la Unión Europea, el resto de la OCDE y el resto del mundo) y 112 sectores. Para el Reino Unido se usan los cuadros de oferta y utilización de la ONS, que cubren de 1997 a 2023 en 112 sectores, y que se complementan con las llamadas tablas analíticas. Estas últimas separan, dentro del uso de cada producto, la parte de origen nacional de la importada y permiten convertir los valores de precios de comprador a precios básicos, es decir, al precio que recibe el productor antes de márgenes comerciales e impuestos. Para el resto del mundo se emplea EXIOBASE hasta 2009 y FIGARO desde 2010. Las importaciones se reparten por país de origen y sector con las proporciones de esas bases, de modo que no se necesita convertir monedas para ese bloque; las exportaciones se obtienen por diferencia, como identidad contable. Las tablas se concilian con el método RAS, un procedimiento iterativo que ajusta filas y columnas hasta que cuadran con totales conocidos. Los valores se expresan en libras esterlinas con el tipo de cambio promedio de doce meses. La huella cubre siete gases (CO2, CH4, N2O, HFC, PFC, NF3 y SF6), convertidos a CO2 equivalente con los potenciales de calentamiento del quinto informe del IPCC, e incluye las emisiones directas de los hogares <span class="citation" data-cites="owen2026 defra2026">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>; <a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>)</span>.</p>
<p><strong>Hallazgos.</strong> En 2023 la huella fue de 699 millones de toneladas de CO2 equivalente (MtCO2e), 4% menos que en 2022 y 10 toneladas por persona, frente a un máximo de 16 en 2004. El máximo absoluto se registró en 2007, con 984 Mt. Más de la mitad de la huella, 371 Mt o 53%, proviene de bienes importados, frente a 31% en 1996; los bienes producidos y consumidos dentro del país aportan 206 Mt (29%) y las emisiones directas de los hogares, 122 Mt. China es el principal origen de las emisiones importadas, con 93 Mt, equivalentes a 25% de las importadas y 13% del total; en 1996 era 8% y 2%. Por categoría de gasto de los hogares, el transporte (150 Mt) y la electricidad, el gas y otros combustibles (113 Mt) son los mayores, seguidos de los alimentos (75 Mt); mientras las emisiones por electricidad y combustibles bajaron 42% desde 1996, las asociadas con muebles y electrodomésticos subieron 85% y las de ropa, 80% <span class="citation" data-cites="defra2026">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>)</span>.</p>
<p>Esa trayectoria muestra por qué la huella aporta información que los inventarios no ofrecen. Entre 1996 y 2023 la huella cayó 15%, mientras que las emisiones territoriales cayeron 50% y las de producción, 42% <span class="citation" data-cites="defra2026">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>)</span>. La <a href="#fig-uk" class="quarto-xref">Figura&nbsp;5</a> muestra las tres series. La brecha se explica porque las emisiones asociadas con importaciones aumentaron 43% en ese período, mientras que las de bienes producidos y consumidos en el país bajaron 49%. La publicación advierte que la caída reciente puede reflejar descarbonización, pero también un menor gasto o un gasto distinto, y por eso encarga descomposiciones que separan ambos efectos <span class="citation" data-cites="defra2026">(<a href="#ref-defra2026" role="doc-biblioref">Department for Environment, Food and Rural Affairs, 2026</a>)</span>. Los resultados de UKMRIO, además, se contrastan con otros modelos: son ligeramente menores hasta 2007 y muy similares a los de Eora y EXIOBASE desde entonces <span class="citation" data-cites="owen2026">(<a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>)</span>.</p>
<p><strong>Retos metodológicos.</strong> La nota de Leeds es notablemente franca sobre las limitaciones, lo cual la vuelve especialmente útil para quien inicia el trabajo <span class="citation" data-cites="owen2026">(<a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>)</span>:</p>
<ul>
<li><em>Tablas analíticas faltantes.</em> Solo existen para algunos años; para el resto se interpola y, desde 2019, se reutiliza la última matriz disponible.</li>
<li><em>Valores negativos o nulos.</em> Los componentes negativos de la demanda final se llevan a cero y se compensan en el valor agregado para que la tabla siga cuadrando; los demás negativos, ceros y vacíos se sustituyen por un número muy pequeño, porque algunos pasos del balanceo no los admiten.</li>
<li><em>Datos preliminares.</em> EXIOBASE proyecta (hace un <em>nowcast</em> de) los años recientes a partir de tendencias y totales mundiales, y no capturó la caída de emisiones de 2020. FIGARO es la única base que ofrece datos reales hasta 2023, y el cambio de una a otra en 2010 modificó ligeramente la trayectoria posterior.</li>
<li><em>Tipo de cambio.</em> Se aplica un único factor de conversión a todos los sectores y regiones, lo que la propia nota reconoce como fuente de incertidumbre.</li>
<li><em>Años lejanos.</em> Las estimaciones de 1990 y 1991 son las menos precisas, por falta de detalle comercial y de clasificaciones consistentes.</li>
<li><em>Incertidumbre.</em> La única medición cuantitativa proviene de una investigación previa de Defra sobre el CO2 de 1992 a 2004, con un error estándar relativo de 3.3% a 5.5% para el total anual, y mayor por sector; las importaciones llevan más incertidumbre que el resto.</li>
<li><em>Revisiones y rezago.</em> Cada edición revisa toda la serie, y el último año se publica con unos dos años y medio de rezago.</li>
</ul>
<p><strong>Qué rescatar.</strong></p>
<ul>
<li>Se puede usar la tabla nacional como núcleo y tomar de una base global solo la estructura comercial y las emisiones del resto del mundo.</li>
<li>Las tablas analíticas, o un sustituto documentado, son necesarias para separar el uso nacional del importado.</li>
<li>Conviene elegir la base global también por su disponibilidad de datos recientes, no solo por su calidad.</li>
<li>Publicar la política de revisiones y los niveles de confianza por año ayuda a los usuarios a interpretar los cambios.</li>
<li>Vincular la encuesta de gasto con la clasificación de las cuentas permite descomponer la huella por grupo de hogares y por región dentro del país.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-uk" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-uk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-uk-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-uk-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Reino Unido: emisiones de gases de efecto invernadero según tres bases de contabilidad, 1996 a 2023 (MtCO2e). Fuente: Defra (2026), figura 8 del conjunto de datos.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="unión-europea" class="level4" data-number="6.1.2">
<h4 data-number="6.1.2" class="anchored" data-anchor-id="unión-europea"><span class="header-section-number">6.1.2</span> Unión Europea</h4>
<p>Eurostat publica una serie de huellas de gases de efecto invernadero para 2010 a 2023, desagregada en siete conjuntos de datos con la misma estructura (gases agregados, CO2, CH4, N2O, HFC, PFC y NF3 con SF6) <span class="citation" data-cites="eurostatghgfp">(<a href="#ref-eurostatghgfp" role="doc-biblioref">Eurostat, 2026</a>)</span>. A diferencia del caso británico, se trata de un producto estadístico comunitario cuyas cifras se obtienen con un modelo, y la propia ficha de metadatos lo aclara. El método es el insumo-producto ambientalmente extendido estándar, y combina las tablas multirregionales FIGARO de Eurostat, que siguen el marco del sistema europeo de cuentas, con las cuentas de emisiones atmosféricas de los países europeos. Para los países no europeos, Eurostat estima por su cuenta las emisiones con la base EDGAR. Los resultados se presentan para 46 entidades de origen y de destino (45 países y un agregado del resto del mundo), 64 ramas de actividad de la NACE y cinco categorías de demanda final (gobierno, hogares, instituciones sin fines de lucro, formación bruta de capital fijo y variación de existencias y objetos de valor). Las emisiones directas de los hogares se agregan a los resultados del modelo y se asignan al consumo de los hogares. Los totales de entrada no cambian: el modelo solo reasigna las emisiones de la cuenta a las categorías de uso final <span class="citation" data-cites="eurostatghgfp">(<a href="#ref-eurostatghgfp" role="doc-biblioref">Eurostat, 2026</a>)</span>.</p>
<p>La ficha de metadatos advierte que los supuestos de modelación implican márgenes de error mayores que los de los inventarios o de las cuentas de emisiones, y que los resultados deben interpretarse con cautela, sobre todo en los niveles más detallados. Las estimaciones de países no europeos tienen menor precisión que las cuentas reportadas por oficinas de estadística, y encajar tablas nacionales en tablas internacionales exige supuestos para equilibrar asimetrías comerciales. La serie completa se reestima cada año con el mismo método, lo que asegura buena comparabilidad en el tiempo, y se publica en octubre con una revisión en enero para alinearla con las cuentas de emisiones, con un rezago objetivo de dos años. No hay un informe de calidad específico para los resultados del modelo ni una cuantificación del error <span class="citation" data-cites="eurostatghgfp">(<a href="#ref-eurostatghgfp" role="doc-biblioref">Eurostat, 2026</a>)</span>.</p>
<p>El manual de cuentas de emisiones de 2015 aporta la referencia conceptual y una cifra ilustrativa: en 2011, el uso final de los residentes de la UE-27 implicó 7.8 toneladas de CO2 por habitante, dentro y fuera de la región, de las cuales 4.9 corresponden al consumo final, 1.3 a la formación de capital y 1.6 a las emisiones directas de los hogares; la demanda externa agrega 1.8 toneladas por habitante <span class="citation" data-cites="eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015, párr. 338</a>)</span>.</p>
<p><strong>Qué rescatar.</strong> Una oficina puede arrancar con una tabla multirregional ya hecha y su propia cuenta de emisiones, a un costo bajo, siempre que la cuenta siga el criterio de residencia y asigne los hogares por separado. Conviene fijar de antemano la regla de revisión, reestimar y republicar la serie completa en cada ciclo, y declarar abiertamente qué insumos no provienen de las oficinas nacionales de estadística.</p>
</section>
</section>
<section id="referencias-de-la-ocde-y-de-la-literatura-científica" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="referencias-de-la-ocde-y-de-la-literatura-científica"><span class="header-section-number">6.2</span> Referencias de la OCDE y de la literatura científica</h3>
<section id="la-base-de-la-ocde-sobre-co2-en-el-comercio" class="level4" data-number="6.2.1">
<h4 data-number="6.2.1" class="anchored" data-anchor-id="la-base-de-la-ocde-sobre-co2-en-el-comercio"><span class="header-section-number">6.2.1</span> La base de la OCDE sobre CO2 en el comercio</h4>
<p>El trabajo de Yamano y Guilhoto (2020) es el más relevante para una oficina de estadística, porque explica paso a paso cómo se convierte un inventario territorial en emisiones de residentes y luego en huella <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>. Parte de las estadísticas de la Agencia Internacional de Energía (AIE) sobre CO2 por quema de combustibles (46 combustibles, 34 flujos o sectores de uso, 138 economías), las reescala a los totales mundial y nacional, y las convierte en emisiones por industria y hogares residentes. Divide las emisiones de cada industria entre su producto para obtener un coeficiente, lo multiplica por la inversa de Leontief de las tablas ICIO de la OCDE y por la matriz de demanda final, y suma las emisiones directas de los hogares. El resultado es un arreglo de cuatro dimensiones: país emisor, industria emisora, país de la demanda final e industria de la demanda final. Aplica la misma lógica a los flujos comerciales brutos, y mantiene indicadores separados para la demanda final y para el comercio bruto, de modo que se eviten dobles conteos con los bienes intermedios <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</p>
<p><strong>Retos metodológicos.</strong> El valor del trabajo está en cómo trata los casos difíciles, que son los mismos que enfrentará cualquier oficina <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>:</p>
<ul>
<li><em>Flujos que corresponden a varias industrias.</em> De los 34 flujos de la AIE, 11 se relacionan con varias industrias del modelo. Las emisiones de los autoproductores a partir de gases de carbón se asignan a la industria siderúrgica, y las demás se reparten según los otros combustibles que usa la manufactura.</li>
<li><em>Transporte por carretera.</em> El flujo de la AIE mezcla industrias y hogares. Para algunos países se usan tablas de uso detalladas para separar gasolina y diésel; para el resto se aplican proporciones de referencia. El paso del enfoque territorial al de residentes utiliza las partidas de viajes de la balanza de pagos y el consumo de los hogares.</li>
<li><em>Aviación internacional.</em> Se reasigna la nacionalidad de las aerolíneas de la sede a su establecimiento, se usan datos de rutas y se supone que las emisiones son proporcionales al número de vuelos entre pares de aeropuertos, con igual número en ambos sentidos.</li>
<li><em>Transporte marítimo internacional.</em> El combustible cargado no coincide con el viaje ni con la nacionalidad del barco. Se asigna 10% a la industria de transporte por agua nacional y el resto según las compras de petróleo de las industrias de transporte por agua en las tablas de uso, y se excluyen las naves militares.</li>
<li><em>Brechas y redondeos.</em> Se corrigen con el reescalamiento a los totales, y se completan países sin datos.</li>
<li><em>Pendientes.</em> Los autores señalan como próximos pasos la integración plena con las cuentas de emisiones atmosféricas y la inclusión de otros gases, y no reportan un análisis formal de incertidumbre <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</li>
</ul>
<p><strong>Hallazgos globales.</strong> Las emisiones mundiales de CO2 por combustión pasaron de 27.1 a 32.3 Gt entre 2005 y 2015, un aumento de 19%. En 2015, 8.8 Gt (cerca de 27%) estuvieron ligadas al comercio internacional. China fue el mayor exportador neto de emisiones y Estados Unidos el mayor importador neto. La parte del CO2 de la demanda final que se emite en el exterior va de 8% en China a 65% en Suiza. Entre los países miembros de la OCDE, las emisiones por consumo por persona bajaron de 13.0 a 10.8 toneladas entre 2005 y 2015, y en 2015 eran 2.5 veces el promedio mundial. Chile figura entre los países de la OCDE que aumentaron tanto sus emisiones de producción como las de consumo <span class="citation" data-cites="yamano2020">(<a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</p>
<p><strong>Qué rescatar.</strong> Fijar por escrito las tres definiciones (territorial, de residentes y de demanda final) antes de calcular; documentar la correspondencia entre los flujos de energía y las industrias, con sus casos uno a muchos; atender primero el transporte por carretera y los combustibles de embarque internacional, que concentran los ajustes; y publicar indicadores de demanda final y de comercio bruto con su origen nacional o extranjero. Los resultados latinoamericanos que se presentan en la sección 5 dependen de las bases de la OCDE y la AIE, por lo que una oficina nacional debería contrastarlos con su propio balance de energía.</p>
</section>
<section id="davis-y-caldeira-2010-y-peters-y-coautores-2011" class="level4" data-number="6.2.2">
<h4 data-number="6.2.2" class="anchored" data-anchor-id="davis-y-caldeira-2010-y-peters-y-coautores-2011"><span class="header-section-number">6.2.2</span> Davis y Caldeira (2010) y Peters y coautores (2011)</h4>
<p>Dos artículos publicados en la revista <em>Proceedings of the National Academy of Sciences</em> establecieron las cifras globales que hoy se citan. Ambos usan la base GTAP, con 113 países o regiones y 57 sectores, y se limitan al CO2 de los combustibles fósiles <span class="citation" data-cites="davis2010 peters2011">(<a href="#ref-davis2010" role="doc-biblioref">Davis y Caldeira, 2010</a>; <a href="#ref-peters2011" role="doc-biblioref">Peters et&nbsp;al., 2011</a>)</span>.</p>
<p>Davis y Caldeira construyen un inventario de consumo para 2004. Su modelo multirregional está plenamente acoplado, es decir, sigue las cadenas de suministro a través de varios países, y reparte las importaciones de cada región entre uso intermedio y final en proporción a lo que exporta cada socio. Encuentran que 6.2 Gt de CO2, 23% de las emisiones fósiles, se emitieron en la producción de bienes consumidos en otro país. Las exportaciones de China incorporaban 1.4 Gt. Las importaciones netas representaban 10.8% de las emisiones de consumo de Estados Unidos (2.4 toneladas por persona), 17.8% en Japón y entre 20% y 50% en las grandes economías de Europa occidental. Las emisiones netas exportadas equivalían a 22.5% de las emisiones de producción de China. Los autores señalan que la principal incertidumbre está en la antigüedad y calidad de las tablas de GTAP y en los ajustes que la base introduce, que no pueden cuantificarse; que el estudio cubre un solo año; que excluye las 27 economías más pequeñas, el combustible de embarque internacional y los gases distintos del CO2; y que usa tipos de cambio de mercado en lugar de paridades de poder adquisitivo. Advierten también que Luxemburgo aparece sobrestimado por los trabajadores transfronterizos, un caso típico de problema de residencia en economías pequeñas <span class="citation" data-cites="davis2010">(<a href="#ref-davis2010" role="doc-biblioref">Davis y Caldeira, 2010</a>)</span>.</p>
<p>Peters y coautores amplían el análisis a una serie anual de 1990 a 2008. Como las tablas detalladas solo existen para 1997, 2001 y 2004, construyen la serie intermedia con un procedimiento más simple, calibrado con los años de referencia, y lo contrastan con otros dos métodos. Las emisiones incorporadas en bienes comerciados pasaron de 4.3 Gt (20% del total) en 1990 a 7.8 Gt (26%) en 2008, y las transferencias netas de países sin metas de Kioto a países con metas, de 0.4 a 1.6 Gt. Esa transferencia en 2008 fue más de cinco veces la reducción real de los países con metas, de unos 0.3 Gt. Por eso los autores sostienen que las emisiones de consumo deberían vigilarse junto con los inventarios territoriales. Reconocen que la incertidumbre crece con el detalle regional y sectorial, que el análisis de insumo-producto no tiene una tradición sólida de análisis formal de incertidumbre, que la formación de capital se trata como consumo interno y que el estudio no determina las causas de la transferencia <span class="citation" data-cites="peters2011">(<a href="#ref-peters2011" role="doc-biblioref">Peters et&nbsp;al., 2011</a>)</span>.</p>
<p><strong>Qué rescatar.</strong> Ambos trabajos recuerdan que una huella debe presentarse junto con el inventario territorial, que los resultados se leen mejor en términos absolutos, por persona y por unidad de producto a la vez, porque los rankings difieren, y que se debe declarar el año base, el rezago de los datos y las exclusiones desde el comienzo. Peters y coautores muestran además que una serie anual puede construirse a partir de pocos años de referencia, siempre que se documente la lógica de los años proxy.</p>
</section>
</section>
<section id="bases-multirregionales" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="bases-multirregionales"><span class="header-section-number">6.3</span> Bases multirregionales</h3>
<p>Como se explicó en la sección 3.3, las importaciones requieren una base multirregional o un supuesto sobre la tecnología extranjera. El <strong>?@tbl-bases</strong> resume las opciones revisadas. La elección depende de la cobertura de países, del detalle sectorial y de las condiciones de uso, que no son iguales en todas las bases.</p>
<table class="caption-top table">
<caption>Bases multirregionales de acceso abierto o restringido</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Base</th>
<th style="text-align: left;">Cobertura</th>
<th style="text-align: left;">Acceso</th>
<th style="text-align: left;">Observación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ICIO y huellas de gases de efecto invernadero de la OCDE <span class="citation" data-cites="oecdghgfp2025">(<a href="#ref-oecdghgfp2025" role="doc-biblioref">OECD, 2025</a>)</span></td>
<td style="text-align: left;">1995 a 2022 (edición 2025); incluye Perú, Chile, Colombia, Costa Rica, México, Brasil y Argentina; no incluye Ecuador, Bolivia, Uruguay, Paraguay ni Venezuela</td>
<td style="text-align: left;">Datos abiertos mediante SDMX</td>
<td style="text-align: left;">Buena cobertura latinoamericana; sirve también como referencia externa</td>
</tr>
<tr class="even">
<td style="text-align: left;">EXIOBASE 3 <span class="citation" data-cites="stadler2018">(<a href="#ref-stadler2018" role="doc-biblioref">Stadler et&nbsp;al., 2018</a>)</span></td>
<td style="text-align: left;">44 países y 5 regiones del resto del mundo; 163 industrias y 200 productos; 1995 a 2011 en el artículo</td>
<td style="text-align: left;">Licencia abierta</td>
<td style="text-align: left;">Entre los países latinoamericanos, Perú no figura como economía individual</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eora <span class="citation" data-cites="eora2026">(<a href="#ref-eora2026" role="doc-biblioref">Eora Global Supply Chain Database, 2026</a>)</span></td>
<td style="text-align: left;">190 países; versión Eora26 con 26 sectores</td>
<td style="text-align: left;">Gratuita solo para uso académico; los informes requieren licencia comercial</td>
<td style="text-align: left;">Verificar la cobertura y la licencia antes de una publicación oficial</td>
</tr>
</tbody>
</table>
<p>EXIOBASE 3 merece una descripción más detallada, porque es la base abierta de uso más extendido y la que usa, por ejemplo, el modelo británico <span class="citation" data-cites="stadler2018">(<a href="#ref-stadler2018" role="doc-biblioref">Stadler et&nbsp;al., 2018</a>)</span>. Se construye de arriba hacia abajo: parte de los agregados de cuentas nacionales de Naciones Unidas, y desarrolla cuadros de oferta y utilización rectangulares (con más productos que industrias) para 44 países, 28 de la Unión Europea y 16 grandes economías, más cinco regiones del resto del mundo. El comercio se obtiene de BACI (Naciones Unidas) y de datos de la AIE, y los márgenes de transporte se estiman con un modelo. Cada año se equilibra por separado con un programa cuadrático de mínimos cuadrados ponderados que altera lo menos posible la tabla inicial. Para las emisiones, los gases de combustión se calculan de abajo hacia arriba con los balances de energía de la AIE y factores de emisión de modelos europeos, y se reasignan al criterio de residencia con modelos de transporte para la pesca internacional, la aviación y la navegación. La base incluye 27 contaminantes, además de agua, materiales, tierra, residuos y empleo <span class="citation" data-cites="stadler2018">(<a href="#ref-stadler2018" role="doc-biblioref">Stadler et&nbsp;al., 2018</a>)</span>.</p>
<p>Los autores advierten de limitaciones que importan a quien la use <span class="citation" data-cites="stadler2018">(<a href="#ref-stadler2018" role="doc-biblioref">Stadler et&nbsp;al., 2018</a>)</span>. Las tablas privilegian la coherencia de la serie sobre la coincidencia con las estadísticas oficiales, por lo que no replican exactamente los cuadros nacionales ni los datos más recientes de Eurostat. Los cambios de clasificación en el tiempo se revisaron visualmente y afectan sobre todo a los servicios. La asignación de importaciones por origen supone que cada usuario compra a cada exportador en las mismas proporciones, y los impuestos y márgenes mantienen proporciones de 2007. Los autores recomiendan considerar el número limitado de países al analizar economías en desarrollo y emergentes, para las cuales Eora o bases construidas sobre GTAP pueden ser más adecuadas. No ofrecen estimaciones de incertidumbre. Perú no figura entre los países individuales, y solo puede quedar dentro de la región del resto del mundo de América.</p>
</section>
<section id="américa-latina" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="américa-latina"><span class="header-section-number">6.4</span> América Latina</h3>
<p>El contexto regional da relieve a estos estudios. Según un documento de la CEPAL, la región emite cerca de 5% del CO2 mundial, y su perfil difiere del global: el cambio de uso de suelo explica 34% de los gases de efecto invernadero de la región, la energía 33% y la agricultura 24%, y las emisiones por persona (2.9 toneladas de CO2 equivalente en 2008) eran inferiores al promedio mundial de 4.8. Además, 52% de las exportaciones regionales en 2011 se dirigió a Estados Unidos y a la Unión Europea, mercados donde la huella de carbono de los productos importados es un tema creciente de política comercial <span class="citation" data-cites="frohmann2013">(<a href="#ref-frohmann2013" role="doc-biblioref">Frohmann y Olmos, 2013</a>)</span>. Ese mismo documento ilustra la diferencia entre la huella de producto o de empresa y la huella nacional: usa el análisis de ciclo de vida y el GHG Protocol para estudiar casos de exportadores de alimentos, pero no recurre a tablas de insumo-producto. Es útil sobre todo para entender el entorno de exportadores y reguladores, y para apreciar que los datos de uso de suelo y de óxido nitroso de los suelos son difíciles de medir, un dato que reaparece en los estudios nacionales <span class="citation" data-cites="frohmann2013">(<a href="#ref-frohmann2013" role="doc-biblioref">Frohmann y Olmos, 2013</a>)</span>.</p>
<p>La revisión no identificó estadísticas oficiales de huella de carbono basadas en cuentas nacionales, con acceso abierto verificable, en los institutos de estadística de la región. Los trabajos encontrados provienen de la academia y de organismos multilaterales, y siguen tres enfoques: huellas de hogares con encuestas de gasto (Perú, México, Brasil, región), huellas nacionales con una base multirregional abierta (Ecuador) y multiplicadores de emisiones con tablas nacionales (Colombia). El <strong>?@tbl-latam</strong> los resume. Conviene confirmar el vacío de estadísticas oficiales directamente con las oficinas de estadística de Colombia, México, Chile, Brasil y Costa Rica.</p>
<table class="caption-top table">
<caption>Experiencias latinoamericanas de huellas de carbono</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">País</th>
<th style="text-align: left;">Estudio</th>
<th style="text-align: left;">Datos y modelo</th>
<th style="text-align: left;">Resultado destacado</th>
<th style="text-align: left;">Lección</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Perú</td>
<td style="text-align: left;"><span class="citation" data-cites="malerba2024">Malerba et&nbsp;al. (<a href="#ref-malerba2024" role="doc-biblioref">2024</a>)</span></td>
<td style="text-align: left;">GTAP 9 (140 regiones, 57 sectores) para 2004, 2007 y 2011; encuesta ENAHO con más de 320 rubros de gasto</td>
<td style="text-align: left;">La huella sube hasta casi 60% en los tres primeros deciles entre 2004 y 2011</td>
<td style="text-align: left;">Una tabla de correspondencia gasto a sector elimina el paso manual más costoso</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ecuador</td>
<td style="text-align: left;"><span class="citation" data-cites="romancollado2021">Román-Collado et&nbsp;al. (<a href="#ref-romancollado2021" role="doc-biblioref">2021</a>)</span></td>
<td style="text-align: left;">Eora26 (26 sectores, 187 países), 2000 a 2015</td>
<td style="text-align: left;">La huella crece 145% entre 2000 y 2015</td>
<td style="text-align: left;">Una primera estimación es factible con una base abierta, pero exige armonizar con las tablas nacionales</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colombia</td>
<td style="text-align: left;"><span class="citation" data-cites="hernandez2021">Hernández (<a href="#ref-hernandez2021" role="doc-biblioref">2021</a>)</span></td>
<td style="text-align: left;">Cuadros de oferta y utilización de 2012 del DANE convertidos a 61 sectores; inventario del IDEAM</td>
<td style="text-align: left;">59% de las emisiones proviene de agricultura, silvicultura y otros usos del suelo; 16 de 61 sectores son clave</td>
<td style="text-align: left;">La concordancia inventario a cuentas nacionales es la pieza central</td>
</tr>
<tr class="even">
<td style="text-align: left;">México</td>
<td style="text-align: left;"><span class="citation" data-cites="renner2018">Renner (<a href="#ref-renner2018" role="doc-biblioref">2018</a>)</span></td>
<td style="text-align: left;">WIOD (34 sectores); encuesta ENIGH 2014 con 744 rubros</td>
<td style="text-align: left;">Un impuesto de 50 USD por tonelada eleva la pobreza entre 0.6 y 0.9 puntos porcentuales (solo energía)</td>
<td style="text-align: left;">Los años de la tabla y de las emisiones deben coincidir</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brasil</td>
<td style="text-align: left;"><span class="citation" data-cites="cachola2021">Cachola y Pacca (<a href="#ref-cachola2021" role="doc-biblioref">2021</a>)</span></td>
<td style="text-align: left;">Matriz de IBGE 2010 (67 actividades); inventario WIOD 2009; encuesta POF 2008-09</td>
<td style="text-align: left;">Los hogares del tramo más alto de ingreso emiten unas 12 veces más que los del más bajo</td>
<td style="text-align: left;">Tabla, inventario y encuesta bastan para una primera estimación por hogar</td>
</tr>
<tr class="even">
<td style="text-align: left;">Región</td>
<td style="text-align: left;"><span class="citation" data-cites="zhong2020">Zhong et&nbsp;al. (<a href="#ref-zhong2020" role="doc-biblioref">2020</a>)</span></td>
<td style="text-align: left;">GTAP v10 para 2014; Base de Datos Global de Consumo del Banco Mundial</td>
<td style="text-align: left;">Entre 0.53 y 2.21 tCO2e per cápita en diez países</td>
<td style="text-align: left;">La huella por nivel de ingreso exige microdatos de encuesta</td>
</tr>
</tbody>
</table>
<section id="perú" class="level4" data-number="6.4.1">
<h4 data-number="6.4.1" class="anchored" data-anchor-id="perú"><span class="header-section-number">6.4.1</span> Perú</h4>
<p><span class="citation" data-cites="malerba2024">Malerba et&nbsp;al. (<a href="#ref-malerba2024" role="doc-biblioref">2024</a>)</span> preguntan cómo cambió la huella de carbono de los hogares peruanos entre 2004, 2007 y 2011, y cómo habría afectado a la pobreza y la desigualdad un impuesto al carbono acompañado de transferencias en efectivo en cada uno de esos años. Los estudios anteriores analizaban un solo año, y los autores muestran que eso puede llevar a diseñar una compensación que deja de funcionar cuando cambia la estructura de consumo.</p>
<p><em>Datos y método.</em> La huella se estima de abajo hacia arriba. Se usa la tabla multirregional GTAP 9 para 2004, 2007 y 2011 (140 regiones, 57 sectores), con las emisiones de CO2 de la base, y la Encuesta Nacional de Hogares (ENAHO), con entre 19,462 y 24,802 hogares según el año y 324 rubros de consumo. Los autores asignan cada rubro de la encuesta a uno de los 57 sectores de GTAP, y la huella de cada hogar es la suma del gasto en cada sector por la intensidad de emisiones incorporadas en ese sector. Los resultados se agrupan en alimentos, calefacción y electricidad, combustible de transporte privado, otro transporte y otros bienes. El análisis principal simula un impuesto sobre las emisiones internas más el uso directo de combustibles por los hogares, y una versión con impuesto global, que incluye bienes importados, se presenta en un apéndice con resultados cualitativamente similares. Los precios se deflactan a 2011, la pobreza se mide con el gasto y la línea oficial del INEI, y se supone que el impuesto se traslada íntegramente al consumidor <span class="citation" data-cites="malerba2024">(<a href="#ref-malerba2024" role="doc-biblioref">Malerba et&nbsp;al., 2024</a>)</span>.</p>
<p><em>Hallazgos.</em></p>
<ul>
<li>La pobreza bajó de 58.7% en 2004 a 42.4% en 2007 y 27.8% en 2011.</li>
<li>Entre 2004 y 2011 el consumo creció más de 50% en la mitad inferior de la distribución y cerca de 20% en el decil superior, y la huella aumentó hasta casi 60% en los tres primeros deciles, 40% en el cuarto y 20% en los deciles sexto a octavo. La huella del decil más rico cayó levemente, por lo que la desigualdad de la huella disminuyó.</li>
<li>La huella promedio bajó en 2007 aunque el gasto subió, porque cayó la intensidad de carbono del petróleo y de la electricidad, por precios de combustibles más altos y un mayor uso de gas natural; volvió a subir en 2011.</li>
<li>Calefacción y electricidad es el rubro mayor por persona, y el combustible de transporte se multiplicó por cinco en el segundo decil, impulsado por la propiedad de automóviles y sobre todo de motocicletas. La propiedad de automóvil pasó de 2% de los hogares en 2004 a 10% en 2011.</li>
<li>Un impuesto de 50 dólares por tonelada elevaría la pobreza en 0.8 puntos porcentuales en 2007 (226,000 personas), 1.1 en 2004 (315,000) y 1.0 en 2011 (296,000), y recaudaría cerca de 1.5% del producto. La carga es menor en los tres primeros deciles que en los deciles quinto a octavo.</li>
<li>La reducción de pobreza que se logra al devolver los ingresos como transferencias cambia con el año: en 2007 los esquemas basados en el programa Juntos reducen la pobreza entre 2.4% y 3.1%, más de tres veces lo que logran en 2004. Ajustar las transferencias por inflación duplica el efecto en 2004.</li>
<li>La focalización de Juntos es débil: el error de exclusión es 89% en 2007 y 78% en 2011, y solo 6% y 8.4% de los hogares declaran recibirlo. Una compensación perfectamente focalizada en los cuatro primeros deciles requeriría cerca de 10% de la recaudación <span class="citation" data-cites="malerba2024">(<a href="#ref-malerba2024" role="doc-biblioref">Malerba et&nbsp;al., 2024</a>)</span>.</li>
</ul>
<p><em>Retos y limitaciones.</em> Los autores construyeron ellos mismos la correspondencia entre rubros de gasto y sectores, porque no existía una tabla oficial por falta de detalle en la información de la oficina de estadística. El gasto de la encuesta no se escala a los totales de las cuentas nacionales, lo que mantiene la coherencia con la línea oficial de pobreza y no cambia los resultados cualitativos. Es un análisis estático, sin respuestas de comportamiento, y por eso entrega un techo de los efectos de corto plazo. Se supone tecnología homogénea dentro de cada sector, el autoconsumo no se grava y los márgenes de transporte no se diferencian por sector. Solo se analizan tres años, cada uno con su encuesta y su tabla <span class="citation" data-cites="malerba2024">(<a href="#ref-malerba2024" role="doc-biblioref">Malerba et&nbsp;al., 2024</a>)</span>.</p>
<p><em>Qué rescatar.</em> Una tabla de correspondencia entre la clasificación del gasto y los sectores de las cuentas, publicada por la oficina de estadística, elimina el paso manual más costoso. Conviene contar con encuestas y tablas de años coincidentes y decidir, y documentar, si el gasto se escala a las cuentas nacionales. Reportar la huella por decil muestra distribuciones que cambian con el tiempo, y un cambio en la mezcla de combustibles puede mover la huella sin que cambie el consumo. Debe aclararse si la huella incluye las emisiones de las importaciones, porque las bases impositivas difieren.</p>
</section>
<section id="ecuador" class="level4" data-number="6.4.2">
<h4 data-number="6.4.2" class="anchored" data-anchor-id="ecuador"><span class="header-section-number">6.4.2</span> Ecuador</h4>
<p><span class="citation" data-cites="romancollado2021">Román-Collado et&nbsp;al. (<a href="#ref-romancollado2021" role="doc-biblioref">2021</a>)</span> estudian cómo cambiaron entre 2000 y 2015 las emisiones de CO2 de Ecuador desde la perspectiva de la producción y del consumo, qué sectores y socios comerciales explican el cambio, y si el aumento de las importaciones trae bienes más o menos intensivos en carbono. Lo hacen con Eora26, una versión simplificada de la base Eora, con 26 sectores y 187 países, que mezcla valores a precios básicos y de comprador, y con emisiones de CO2 de la propia base, completadas con EDGAR donde faltan. Analizan solo tres años (2000, 2008 y 2015), que justifican como el año de la dolarización, el del cambio constitucional y el último disponible, y agregan los resultados en 8 sectores y 6 regiones. Calculan la huella, las emisiones de producción, el saldo comercial de emisiones (exportadas menos importadas) y una descomposición de cada sector en emisiones directas, indirectas nacionales e indirectas importadas. No usan encuesta de hogares ni separan las categorías de demanda final <span class="citation" data-cites="romancollado2021">(<a href="#ref-romancollado2021" role="doc-biblioref">Román-Collado et&nbsp;al., 2021</a>)</span>.</p>
<p><em>Hallazgos.</em> Las cifras provienen de la versión preliminar del artículo y conviene confirmarlas con la versión publicada.</p>
<ul>
<li>La huella pasó de 18,554 Gg de CO2 en 2000 a 31,814 en 2008 y 45,506 en 2015, un aumento de 145%. Las emisiones de producción fueron 19,499, 30,883 y 41,749 Gg, un aumento de 114%.</li>
<li>Las dos medidas se cruzan: la huella estaba cerca de 5% por debajo de la producción en 2000 y fue 3% mayor en 2008 y 9% mayor en 2015. Las emisiones internas siguen siendo más de 70% de la huella.</li>
<li>Las emisiones incorporadas en importaciones subieron de 4,514 a 12,183 Gg (170%) y las de exportaciones, de 5,459 a 8,427 Gg (54%). El saldo comercial pasó de un superávit de 945 Gg a un déficit de 3,757 Gg.</li>
<li>Entre 2008 y 2015, las importaciones crecieron cerca de 11% en valor, pero 34% en emisiones incorporadas, lo que sugiere que se importan bienes más intensivos en carbono.</li>
<li>Las importaciones de emisiones desde los BRICS (Brasil, Rusia, India, China y Sudáfrica) crecieron 325% y alcanzan 24% del total. Ecuador es importador neto de emisiones frente a los BRICS en los tres años, y en 2015 solo sigue siendo exportador neto hacia la Unión Europea.</li>
<li>En 2015, el transporte aportó 40% de la huella (18,141 Gg) y la industria manufacturera, 31% (14,252 Gg) <span class="citation" data-cites="romancollado2021">(<a href="#ref-romancollado2021" role="doc-biblioref">Román-Collado et&nbsp;al., 2021</a>)</span>.</li>
</ul>
<p><em>Retos y limitaciones.</em> El artículo no incluye una sección de limitaciones y no discute la incertidumbre de los datos. Los autores señalan que la agregación puede generar diferencias entre la versión completa de Eora y Eora26, pero sostienen que el efecto es menor en su nivel de detalle. No analizan las consecuencias de mezclar precios básicos y de comprador, ni concilian las emisiones con el inventario nacional, ni prueban la calidad de Eora para Ecuador. Solo hay tres años, pese al rango del título, y hay inconsistencias menores de redacción entre el texto y los cuadros, otra razón para confirmar las cifras con la versión final <span class="citation" data-cites="romancollado2021">(<a href="#ref-romancollado2021" role="doc-biblioref">Román-Collado et&nbsp;al., 2021</a>)</span>.</p>
<p><em>Qué rescatar.</em> Una base abierta permite una primera estimación de la huella, sin construir tablas multirregionales. Mostrar la brecha entre huella y producción, y el saldo comercial de emisiones, resume en pocas cifras la posición del país. Comparar las emisiones incorporadas con los flujos monetarios, como muestra el contraste entre 11% y 34%, agrega información que el valor de las importaciones no da. Separar las emisiones directas, indirectas nacionales e indirectas importadas por sector orienta la política. Una base global debe armonizarse con las cuentas nacionales para ser creíble, algo que el artículo no prueba.</p>
</section>
<section id="colombia" class="level4" data-number="6.4.3">
<h4 data-number="6.4.3" class="anchored" data-anchor-id="colombia"><span class="header-section-number">6.4.3</span> Colombia</h4>
<p><span class="citation" data-cites="hernandez2021">Hernández (<a href="#ref-hernandez2021" role="doc-biblioref">2021</a>)</span> pregunta qué sectores colombianos tienen más efecto sobre las emisiones de gases de efecto invernadero, a través de sus vínculos directos e indirectos con el resto de la economía. El interés está en que los compromisos de mitigación del país (una reducción de 20% frente a la proyección a 2030) se apoyaron en curvas de costos de abatimiento que ignoran los vínculos entre sectores. El estudio no simula políticas; caracteriza sectores. No es una huella por demanda final, sino un análisis de multiplicadores con la tabla nacional.</p>
<p><em>Datos y método.</em> El autor construye una tabla de insumo-producto de 2012 con los cuadros de oferta y utilización del DANE, con 61 sectores, y usa el método de Eurostat para tratar la producción secundaria y evitar coeficientes negativos. Como las emisiones se producen dentro del país, emplea la matriz de uso de producción nacional y excluye los insumos importados. Las emisiones provienen del inventario de gases de efecto invernadero del IDEAM de 2012, en CO2 equivalente: 129 Mt de agricultura, silvicultura y otros usos del suelo, 75 de energía, 9 de residuos y 7 de procesos industriales, con 59% del total en el primer grupo y 4.8 toneladas por persona. No usa las cuentas de emisiones del DANE porque cubren solo la energía y subestimarían el efecto de los gases en conjunto. Como no existe una correspondencia oficial entre las categorías del inventario y las cuentas nacionales, la construye: para residuos, procesos industriales y uso de suelo reparte las emisiones según el consumo intermedio interno de los sectores vinculados, adaptando procedimientos aplicados en Chile y México, y para los sectores de energía usa directamente la matriz de uso del DANE. Calcula inversas de Leontief y de Ghosh, y los encadenamientos hacia atrás (cuánto compra cada sector a sus proveedores) y hacia delante (a cuántos sectores abastece) con el método de extracción hipotética, que mide la importancia de un sector al imaginar que no tuviera emisiones. Clasifica los sectores en clave, de arrastre, impulsores y de enclave según la tipología de Hirschman <span class="citation" data-cites="hernandez2021">(<a href="#ref-hernandez2021" role="doc-biblioref">Hernández, 2021</a>)</span>.</p>
<p><em>Hallazgos.</em></p>
<ul>
<li>De 61 sectores, 16 son clave (14.5% de la producción, 9.6% del valor agregado y 12.4% del empleo), 13 tienen fuertes encadenamientos hacia atrás, 17 hacia delante y 14 son de enclave, y estos últimos generan casi la mitad del valor agregado (46.7%).</li>
<li>Medidos por sus emisiones, de 59 sectores 35 emiten por debajo del promedio, son responsables de 69.1% del producto y emiten 14.3% de los gases. Los 18 mayores emisores concentran 69.9% de las emisiones, con 25.1% del valor agregado y 35.6% del empleo.</li>
<li>Entre los mayores emisores que además son sectores clave destacan transporte terrestre, químicos, molinería, otro transporte, caucho y plástico y transporte aéreo, que suman 6.3% del producto.</li>
<li>La electricidad aporta 6.9% de las emisiones, a pesar de la matriz energética basada en hidroeléctricas, porque el consumo total de energía depende del petróleo y el gas. El conjunto minero-energético (petróleo refinado, gas y transporte) genera 16.7%, y la agricultura y ganadería, 14.2% <span class="citation" data-cites="hernandez2021">(<a href="#ref-hernandez2021" role="doc-biblioref">Hernández, 2021</a>)</span>.</li>
<li>El autor propone una lectura de política según el tipo de encadenamiento: si domina el componente directo, las medidas sectoriales son eficaces; si domina el indirecto hacia delante, conviene una política transversal; y si domina el indirecto hacia atrás, las políticas de demanda tienen más efecto <span class="citation" data-cites="hernandez2021">(<a href="#ref-hernandez2021" role="doc-biblioref">Hernández, 2021</a>)</span>.</li>
</ul>
<p><em>Retos y limitaciones.</em> La correspondencia entre inventario y cuentas es construida por el autor y reparte emisiones con un supuesto de ponderación. El método excluye las importaciones, de modo que no mide una huella de consumo, y cubre un solo año. Combinar las cuentas del DANE con el inventario del IDEAM mezcla metodologías (flujos de energía frente a datos de actividad y factores de emisión del IPCC), y el autor optó por el inventario por su cobertura completa <span class="citation" data-cites="hernandez2021">(<a href="#ref-hernandez2021" role="doc-biblioref">Hernández, 2021</a>)</span>.</p>
<p><em>Qué rescatar.</em> La correspondencia entre el inventario de gases de efecto invernadero y los sectores de las cuentas nacionales es la pieza clave, y conviene publicarla. Debe usarse el inventario completo y no solo las emisiones de energía: la agricultura y el uso de suelo suman casi 60% en Colombia. La matriz de uso nacional evita mezclar insumos importados en los coeficientes internos, y la producción secundaria debe tratarse de forma explícita. Una huella con importaciones requiere además un supuesto de tecnología o una base multirregional.</p>
</section>
<section id="méxico" class="level4" data-number="6.4.4">
<h4 data-number="6.4.4" class="anchored" data-anchor-id="méxico"><span class="header-section-number">6.4.4</span> México</h4>
<p><span class="citation" data-cites="renner2018">Renner (<a href="#ref-renner2018" role="doc-biblioref">2018</a>)</span> estima cómo afectarían a los hogares mexicanos distintos impuestos al carbono, y si devolver la recaudación compensa las pérdidas. México introdujo un impuesto en 2014 y se comprometió a reducir emisiones, pero no había evidencia sobre quién asumiría el costo. La versión que se revisó es el documento de trabajo de 2017, y los resultados deben confirmarse con el artículo publicado.</p>
<p><em>Datos y método.</em> El cálculo tiene dos pasos. Primero, un modelo de insumo-producto ambientalmente extendido da la intensidad de emisiones, directa e indirecta, de cada sector. Segundo, los cambios de precios sectoriales se multiplican por las participaciones de gasto de cada hogar. Se supone que el impuesto se traslada íntegramente al consumidor, por lo que el modelo vale solo para cambios pequeños y de corto plazo. La tabla y las emisiones provienen de WIOD (35 sectores, de los cuales se usan 34), con CO2, CH4 y N2O y potenciales de calentamiento de 28 y 265 para metano y óxido nitroso. Las emisiones llegan solo a 2009, mientras que la tabla más reciente es de 2014, por lo que se usan las intensidades de 2009 con precios convertidos a 2014 y se transforman los precios básicos a precios de consumidor con las tasas netas de impuestos de WIOD. Las emisiones directas de combustibles de los hogares se derivan del gasto dividido entre precios. La encuesta ENIGH 2014 (cerca de 20,000 hogares, 744 rubros) se asigna a los 34 sectores por coincidencia de nombres y descripciones, y esa correspondencia solo está disponible por solicitud. Se simulan tres escenarios: A (CO2 de energía sin gas natural ni combustible de aviación), B (agrega gas natural) y C (agrega CH4, N2O y CO2 no energético), con tasas de 3.5, 20 y 50 dólares por tonelada <span class="citation" data-cites="renner2018">(<a href="#ref-renner2018" role="doc-biblioref">Renner, 2018</a>)</span>.</p>
<p><em>Hallazgos.</em></p>
<ul>
<li>El impuesto vigente en 2014 equivale en promedio a 3.4 dólares por tonelada, y a ese nivel las pérdidas son inferiores a 0.2% del gasto para la mayoría de los hogares.</li>
<li>A 50 dólares por tonelada, el impuesto sobre el CO2 de energía eleva la pobreza nacional en 0.6 puntos porcentuales con la línea de bienestar mínimo y en 0.9 con la línea de bienestar (escenario A); con todos los gases (escenario C) las cifras son 1.5 y 1.8 puntos.</li>
<li>Las pérdidas son progresivas en los escenarios A y B, porque la intensidad de carbono del consumo crece hasta cerca del percentil 50 del gasto, impulsada por la gasolina, y cae en los deciles altos, donde predominan los servicios. En el escenario C el impuesto es regresivo: las pérdidas llegan a 4.2% del gasto de los más pobres y a 3.4% del de los más ricos, porque los alimentos son intensivos en CH4 y N2O y pesan más en el gasto de los pobres.</li>
<li>La pobreza rural sube más que la urbana. Si la recaudación se devuelve como una suma fija por hogar (escenario B con 20 dólares por tonelada), los hogares del 85% inferior ganan en promedio. Devolverla a través del programa PROSPERA reduce la pobreza rural, pero deja de lado a hogares urbanos cercanos a la pobreza: cerca de 70% de los hogares del percentil más bajo recibe el programa, y solo 13% en el percentil 50 <span class="citation" data-cites="renner2018">(<a href="#ref-renner2018" role="doc-biblioref">Renner, 2018</a>)</span>.</li>
</ul>
<p><em>Retos y limitaciones.</em> La brecha entre la encuesta y las cuentas es la mayor: el consumo de la tabla de insumo-producto es 2.8 veces el de ENIGH, ajustado por crecimiento. El autor se concentra en efectos relativos, que no cambian al escalar, y advierte que los montos absolutos y la recaudación necesitarían multiplicarse por ese factor si se confía en las cuentas. La correspondencia de 744 rubros se hizo por criterio propio y no está publicada. Hay un desfase de años entre las emisiones (2009) y la encuesta (2014); el autor lo justifica por el descenso de la intensidad en el sector eléctrico. Se consideran solo efectos de primer orden, sin sustitución, y la mayoría de los efectos de bienestar queda dentro de la banda de confianza de 95% <span class="citation" data-cites="renner2018">(<a href="#ref-renner2018" role="doc-biblioref">Renner, 2018</a>)</span>.</p>
<p><em>Qué rescatar.</em> Publicar una correspondencia entre los rubros de la encuesta y los sectores de las cuentas es una de las contribuciones más útiles que puede hacer una oficina de estadística. Conciliar el gasto de la encuesta con el consumo de las cuentas, que aquí difieren por un factor de casi tres, es una condición para obtener huellas y recaudaciones absolutas confiables. Los años de las cuentas de emisiones, de la tabla y de la encuesta deben coincidir, y conviene mantener la separación por gas (CO2, CH4 y N2O) en las cuentas, porque la base impositiva cambia el signo distributivo.</p>
</section>
<section id="brasil" class="level4" data-number="6.4.5">
<h4 data-number="6.4.5" class="anchored" data-anchor-id="brasil"><span class="header-section-number">6.4.5</span> Brasil</h4>
<p><span class="citation" data-cites="cachola2021">Cachola y Pacca (<a href="#ref-cachola2021" role="doc-biblioref">2021</a>)</span> estiman cuánto CO2 equivalente emiten los hogares brasileños por su consumo, y cómo difiere según el ingreso y el tipo de gasto. Existen pocos estudios para países de ingreso bajo y medio, y la respuesta importa para políticas con perspectiva de equidad.</p>
<p><em>Datos y método.</em> La huella de cada grupo de ingreso suma emisiones indirectas y directas. Las indirectas se obtienen multiplicando el gasto por sector por la matriz de Leontief de las cuentas nacionales de IBGE de 2010 (67 actividades) y por un coeficiente ambiental, que es la emisión del inventario ambiental de WIOD de 2009 dividida entre la producción de 2010, para lo cual hubo que vincular las actividades brasileñas con los sectores de WIOD. El gasto proviene de la Encuesta de Presupuestos Familiares POF 2008-09 (55,970 hogares), cuyos rubros siguen la clasificación COICOP y se asignan a las 67 actividades mediante los códigos CNAE. Las emisiones directas resultan de dividir el gasto en combustibles, electricidad, gas natural y gas licuado entre el precio medio y multiplicar por un factor de emisión. Se definen seis tramos de ingreso <span class="citation" data-cites="cachola2021">(<a href="#ref-cachola2021" role="doc-biblioref">Cachola y Pacca, 2021</a>)</span>.</p>
<p><em>Hallazgos.</em></p>
<ul>
<li>Los hogares de menores ingresos (hasta 415 al mes) emiten menos de 1.5 toneladas al año, y los de mayores ingresos (más de 5,187.50 al mes) unas 18.5, casi 12 veces más.</li>
<li>El tramo más bajo es más de 20% de los hogares y emite cerca de 7% del total; el más alto es 4% de los hogares y emite 16%.</li>
<li>La huella crece de forma casi lineal con el ingreso (R² de 95%).</li>
<li>Las emisiones de los hogares en 2009 equivalen a 77% del total nacional según WIOD, una proporción comparable a la de los hogares de Estados Unidos.</li>
<li>Por categoría, la proporción de alimentos baja y la de servicios sube con el ingreso. Para los más pobres pesa más la vivienda (electricidad y gas licuado), y el transporte es la categoría de mayor influencia global.</li>
<li>Las huellas son inferiores a las de países desarrollados, que los autores citan en 48 toneladas para Estados Unidos, 30 para Alemania y 22.3 para Noruega <span class="citation" data-cites="cachola2021">(<a href="#ref-cachola2021" role="doc-biblioref">Cachola y Pacca, 2021</a>)</span>.</li>
</ul>
<p><em>Retos y limitaciones.</em> El artículo no tiene sección de limitaciones. El modelo entrega resultados promedio para todo Brasil, sin variación regional ni dentro de cada tramo. Se usa la POF 2008-09 porque las tablas de la encuesta de 2017-18 no estaban disponibles en el sistema de IBGE. Hay desfases entre las emisiones (2009), la matriz (2010) y la encuesta (2008-09), y las concordancias entre COICOP, CNAE, las 67 actividades y WIOD no se muestran. No hay análisis de incertidumbre ni se discuten las emisiones de las importaciones, lo que sugiere que la estimación equivale en la práctica a un supuesto de tecnología doméstica <span class="citation" data-cites="cachola2021">(<a href="#ref-cachola2021" role="doc-biblioref">Cachola y Pacca, 2021</a>)</span>.</p>
<p><em>Qué rescatar.</em> Basta una tabla nacional, un inventario y una encuesta de gasto para una primera estimación por grupo de ingreso. Tabulaciones oportunas de la encuesta por tramo de ingreso y por COICOP facilitan la actualización, y una correspondencia publicada entre COICOP y las actividades de las cuentas evita rehacerla. Si las cuentas ambientales tuvieran el mismo detalle sectorial que la tabla, los coeficientes no requerirían reasignarse a WIOD. Conviene informar las emisiones directas de los hogares por separado y, si es posible, por región.</p>
</section>
<section id="región" class="level4" data-number="6.4.6">
<h4 data-number="6.4.6" class="anchored" data-anchor-id="región"><span class="header-section-number">6.4.6</span> Región</h4>
<p><span class="citation" data-cites="zhong2020">Zhong et&nbsp;al. (<a href="#ref-zhong2020" role="doc-biblioref">2020</a>)</span> estiman la desigualdad de las huellas de carbono y de energía entre y dentro de diez países de América Latina y el Caribe (Bolivia, Brasil, Colombia, Guatemala, Honduras, Jamaica, México, Nicaragua, Paraguay y Perú). Usan GTAP v10 para 2014 (141 regiones y 65 sectores) y reparten el consumo de los hogares en diez grupos de ingreso con los perfiles de la Base de Datos Global de Consumo del Banco Mundial, construida con encuestas de hogares (33 sectores de consumo, referencia 2011, en dólares de paridad de poder adquisitivo). La correspondencia entre los 33 y los 65 sectores se hace por definición <span class="citation" data-cites="zhong2020">(<a href="#ref-zhong2020" role="doc-biblioref">Zhong et&nbsp;al., 2020</a>)</span>.</p>
<p>El 10% de mayores ingresos explica 29.1% de la huella regional de carbono y 26.3% de la de energía. Su huella por persona es de 4.65 toneladas de CO2 equivalente, frente a 0.38 del 10% más pobre, es decir, unas 12 veces. El promedio regional es de cerca de 1.5 toneladas por persona, y entre países va de 0.53 (Honduras) a 2.21 (México). Solo Jamaica, Nicaragua y Honduras tienen una desigualdad de la huella mayor que la del consumo (por ejemplo, Honduras tiene un índice de Gini de 0.52 para la huella y 0.48 para el consumo), mientras que Brasil combina la desigualdad de consumo más severa (0.52) con una desigualdad de huella baja (0.39), que los autores atribuyen al uso de bioetanol y a los precios del combustible <span class="citation" data-cites="zhong2020">(<a href="#ref-zhong2020" role="doc-biblioref">Zhong et&nbsp;al., 2020</a>)</span>.</p>
<p>Los autores reconocen tres limitaciones: la correspondencia entre 33 y 65 sectores genera traslapes; se supone que la estructura de energía es idéntica entre grupos de ingreso de un mismo país, lo que puede sobrestimar la huella de los más ricos, que acceden a tecnologías de bajo carbono; y el año de los perfiles (2011) difiere del de GTAP (2014). Sugieren combinar datos físicos y monetarios <span class="citation" data-cites="zhong2020">(<a href="#ref-zhong2020" role="doc-biblioref">Zhong et&nbsp;al., 2020</a>)</span>. El artículo contiene además pequeñas inconsistencias entre el resumen y el cuerpo en algunas razones entre grupos, que no afectan las conclusiones generales. De allí se rescata que el reparto del consumo por decil requiere una clasificación de gasto compatible con las cuentas, datos físicos de energía por grupo de ingreso, años de referencia alineados y una comparación con referentes regionales construidos con el mismo método.</p>
<p>Otros dos estudios regionales completan el panorama. Según su resumen, <span class="citation" data-cites="wang2024">Wang et&nbsp;al. (<a href="#ref-wang2024" role="doc-biblioref">2024</a>)</span> examinan nueve países sudamericanos en 2015-2019 y encuentran que Brasil es el único exportador neto de emisiones incorporadas y Colombia el mayor importador neto, y que la intensidad energética compensa el aumento de las emisiones de consumo por persona. <span class="citation" data-cites="sanguinet2022">Sanguinet et&nbsp;al. (<a href="#ref-sanguinet2022" role="doc-biblioref">2022</a>)</span> usan un modelo interregional para Brasil, Chile, Colombia y México y muestran que las industrias basadas en recursos naturales incorporan más CO2 en sus cadenas de valor. No se revisaron sus textos completos.</p>
</section>
</section>
<section id="lecciones-comunes" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="lecciones-comunes"><span class="header-section-number">6.5</span> Lecciones comunes</h3>
<p>Entre las experiencias oficiales y las académicas, se repiten ocho lecciones:</p>
<ol type="1">
<li><strong>Tres insumos.</strong> Todas combinan una tabla de insumo-producto, un inventario o cuenta de emisiones y, para los hogares, una encuesta de gasto.</li>
<li><strong>Concordancias.</strong> La correspondencia entre clasificaciones (inventario, cuentas nacionales, encuesta y base multirregional) es el paso que más trabajo exige y el que más se documenta como limitación. Publicarla beneficia a todos los usuarios.</li>
<li><strong>Importaciones.</strong> Los estudios con modelos multirregionales cubren las importaciones; los que usan solo la tabla nacional las excluyen o las tratan con el supuesto de tecnología doméstica. La interpretación de los resultados cambia según la opción.</li>
<li><strong>Residencia y transporte.</strong> Los ajustes del transporte internacional, la pesca y el turismo concentran el trabajo de conciliación entre inventario y cuenta, y conviene atenderlos primero.</li>
<li><strong>Años de referencia.</strong> Los desfases entre tablas, inventarios y encuestas obligan a supuestos y se mencionan en casi todos los casos.</li>
<li><strong>Revisión y calendario.</strong> Las prácticas oficiales actualizan y revisan la serie completa cada año, con un rezago de dos a tres años, y publican una nota metodológica con las limitaciones.</li>
<li><strong>Sensibilidad.</strong> Los resultados dependen del alcance de gases, de la base de datos y del período, como muestra el caso de Brasil.</li>
<li><strong>Incertidumbre.</strong> Casi ninguna fuente cuantifica la incertidumbre. Las oficinas pueden aportar valor comunicando al menos rangos entre bases alternativas y contrastes con referencias independientes.</li>
</ol>
</section>
</section>
<section id="consideraciones-de-diseño" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="consideraciones-de-diseño"><span class="header-section-number">7</span> Consideraciones de diseño</h2>
<p>Las experiencias revisadas muestran que la huella de carbono nacional es una estadística factible para una oficina que ya compila cuadros de oferta y utilización y que cuenta, o está construyendo, cuentas de emisiones atmosféricas. También muestran que sus resultados dependen de decisiones metodológicas que no son evidentes para el usuario. Las siete que siguen condensan lo aprendido en la sección 6.</p>
<ol type="1">
<li><strong>Alcance de gases y uso de suelo.</strong> La elección entre CO2 de combustión y gases de efecto invernadero en CO2 equivalente cambia el mensaje. La serie de la OCDE incluye solo combustión; el Reino Unido excluye el uso de suelo; en Colombia, la agricultura y el uso de suelo suman casi 60% de las emisiones, y en América Latina el cambio de uso de suelo pesa más que en el promedio mundial. En México, además, la base impositiva por gas cambia el signo distributivo <span class="citation" data-cites="yamano2020 owen2026 hernandez2021 frohmann2013 renner2018">(<a href="#ref-frohmann2013" role="doc-biblioref">Frohmann y Olmos, 2013</a>; <a href="#ref-hernandez2021" role="doc-biblioref">Hernández, 2021</a>; <a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>; <a href="#ref-renner2018" role="doc-biblioref">Renner, 2018</a>; <a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</li>
<li><strong>Importaciones.</strong> Las opciones son el supuesto de tecnología doméstica, una base multirregional o una combinación. El Reino Unido usa su propia tabla y toma de una base global solo la estructura comercial y las emisiones del exterior; Ecuador usa una base abierta completa; Colombia y Brasil, en la práctica, trabajan con la tabla nacional. Conviene contrastar el resultado con una referencia independiente, como las series de la OCDE, y recordar que el supuesto de tecnología doméstica mide emisiones evitadas y no emisiones reales en el exterior <span class="citation" data-cites="owen2026 romancollado2021 eurostat2015">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015</a>; <a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>; <a href="#ref-romancollado2021" role="doc-biblioref">Román-Collado et&nbsp;al., 2021</a>)</span>.</li>
<li><strong>Concordancias.</strong> Es el paso más costoso y el más citado como limitación, en el caso de las encuestas (Perú, México y Brasil), del inventario (Colombia) y de los flujos de energía (la OCDE). Una oficina de estadística que publica las correspondencias entre su clasificación industrial, el inventario de emisiones y la clasificación del gasto elimina el trabajo manual a todos los usuarios <span class="citation" data-cites="malerba2024 renner2018 cachola2021 hernandez2021 yamano2020">(<a href="#ref-cachola2021" role="doc-biblioref">Cachola y Pacca, 2021</a>; <a href="#ref-hernandez2021" role="doc-biblioref">Hernández, 2021</a>; <a href="#ref-malerba2024" role="doc-biblioref">Malerba et&nbsp;al., 2024</a>; <a href="#ref-renner2018" role="doc-biblioref">Renner, 2018</a>; <a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</li>
<li><strong>Residencia y transporte.</strong> Los ajustes del transporte por carretera, aéreo y marítimo, de la pesca y del turismo concentran el trabajo de conciliación con el inventario. Conviene atender primero las partidas grandes, documentar las partidas puente y reconocer que algunos supuestos, como igual número de vuelos por ruta, son toscos <span class="citation" data-cites="eurostat2015 yamano2020">(<a href="#ref-eurostat2015" role="doc-biblioref">Eurostat, 2015</a>; <a href="#ref-yamano2020" role="doc-biblioref">Yamano y Guilhoto, 2020</a>)</span>.</li>
<li><strong>Años de referencia, series y revisiones.</strong> Los desfases entre tabla, inventario y encuesta obligan a supuestos, y casi todos los estudios los mencionan. Las prácticas oficiales publican con dos a tres años de rezago, reestiman la serie completa en cada ciclo y declaran la política de revisión. Una serie anual puede construirse con pocos años de referencia si se documenta la lógica de los años proxy <span class="citation" data-cites="owen2026 eurostatghgfp peters2011">(<a href="#ref-eurostatghgfp" role="doc-biblioref">Eurostat, 2026</a>; <a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>; <a href="#ref-peters2011" role="doc-biblioref">Peters et&nbsp;al., 2011</a>)</span>.</li>
<li><strong>Hogares y distribución.</strong> Para huellas por decil se necesita una encuesta de gasto conciliada con las cuentas nacionales; en México, el consumo de las cuentas es 2.8 veces el de la encuesta. Conviene reportar las emisiones directas de los hogares por separado y mostrar la distribución, porque cambios en la mezcla de combustibles pueden mover la huella sin que cambie el consumo <span class="citation" data-cites="renner2018 malerba2024 zhong2020">(<a href="#ref-malerba2024" role="doc-biblioref">Malerba et&nbsp;al., 2024</a>; <a href="#ref-renner2018" role="doc-biblioref">Renner, 2018</a>; <a href="#ref-zhong2020" role="doc-biblioref">Zhong et&nbsp;al., 2020</a>)</span>.</li>
<li><strong>Incertidumbre, metadatos y comunicación.</strong> Casi ninguna fuente cuantifica la incertidumbre. Una nota metodológica pública que documente fuentes, concordancias, ajustes y limitaciones, junto con rangos entre bases alternativas, aporta credibilidad. La huella debe presentarse junto con el inventario territorial y, cuando sea posible, en términos absolutos, por persona y por unidad de producto <span class="citation" data-cites="owen2026 peters2011 davis2010">(<a href="#ref-davis2010" role="doc-biblioref">Davis y Caldeira, 2010</a>; <a href="#ref-owen2026" role="doc-biblioref">Owen, 2026</a>; <a href="#ref-peters2011" role="doc-biblioref">Peters et&nbsp;al., 2011</a>)</span>.</li>
</ol>
<p>Una secuencia prudente es empezar con una versión sencilla (CO2 equivalente, tabla nacional y una base multirregional abierta para las importaciones), compararla con las referencias externas, y refinarla en ciclos posteriores con las mejoras que la propia oficina identifique.</p>
</section>
<section id="referencias" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-cachola2021" class="csl-entry" role="listitem">
Cachola, C. da S. y Pacca, S. A. (2021). The carbon footprint of <span>B</span>razilian households through the <span>C</span>onsumer <span>E</span>xpenditure <span>S</span>urvey (<span>POF</span>). <em>Revista Kawsaypacha: Sociedad y Medio Ambiente</em>, <em>7</em>, 11-27. <a href="https://doi.org/10.18800/kawsaypacha.202101.001">https://doi.org/10.18800/kawsaypacha.202101.001</a>
</div>
<div id="ref-davis2010" class="csl-entry" role="listitem">
Davis, S. J. y Caldeira, K. (2010). Consumption-based accounting of <span>CO<span class="math inline">\(_2\)</span></span> emissions. <em>Proceedings of the National Academy of Sciences</em>, <em>107</em>(12), 5687-5692. <a href="https://doi.org/10.1073/pnas.0906974107">https://doi.org/10.1073/pnas.0906974107</a>
</div>
<div id="ref-defra2026" class="csl-entry" role="listitem">
Department for Environment, Food and Rural Affairs. (2026). <em><span>UK and England’s carbon footprint to 2023</span></em> [Estad{\'i}sticas oficiales]. GOV.UK. <a href="https://www.gov.uk/government/statistics/uks-carbon-footprint">https://www.gov.uk/government/statistics/uks-carbon-footprint</a>
</div>
<div id="ref-eora2026" class="csl-entry" role="listitem">
Eora Global Supply Chain Database. (2026). <em>Eora global supply chain database</em> [Base de datos]. Eora. <a href="https://worldmrio.com/">https://worldmrio.com/</a>
</div>
<div id="ref-espindola2012" class="csl-entry" role="listitem">
Espíndola, C. y Valderrama, J. O. (2012). Huella del carbono. <span>P</span>arte 1: Conceptos, m<span>é</span>todos de estimaci<span>ó</span>n y complejidades metodol<span>ó</span>gicas. <em>Informaci<span class="nocase">ó</span>n Tecnol<span class="nocase">ó</span>gica</em>, <em>23</em>(1), 163-176. <a href="https://doi.org/10.4067/S0718-07642012000100017">https://doi.org/10.4067/S0718-07642012000100017</a>
</div>
<div id="ref-eurostat2015" class="csl-entry" role="listitem">
Eurostat. (2015). <em>Manual for air emissions accounts</em>. Publications Office of the European Union. <a href="https://doi.org/10.2785/527552">https://doi.org/10.2785/527552</a>
</div>
<div id="ref-eurostatghgfp" class="csl-entry" role="listitem">
Eurostat. (2026). <em>Greenhouse gas emission footprints (<span>FIGARO</span> application) (<span>env_ac_ghgfp</span>)</em> [Base de datos y metadatos]. Eurostat. <a href="https://ec.europa.eu/eurostat/cache/metadata/en/env_ac_ghgfp_esms.htm">https://ec.europa.eu/eurostat/cache/metadata/en/env_ac_ghgfp_esms.htm</a>
</div>
<div id="ref-frohmann2013" class="csl-entry" role="listitem">
Frohmann, A. y Olmos, X. (2013). <em>Huella de carbono, exportaciones y estrategias empresariales frente al cambio clim<span>á</span>tico</em> (Documentos de proyectos LC/W.559/Rev.1). Comisi<span>ó</span>n Econ<span>ó</span>mica para Am<span>é</span>rica Latina y el Caribe. <a href="http://hdl.handle.net/11362/4101">http://hdl.handle.net/11362/4101</a>
</div>
<div id="ref-hernandez2021" class="csl-entry" role="listitem">
Hernández, G. (2021). Emisiones de gases de efecto invernadero y sectores clave en <span>C</span>olombia. <em>El Trimestre Econ<span class="nocase">ó</span>mico</em>, <em>88</em>(350), 523-550. <a href="https://doi.org/10.20430/ete.v88i350.857">https://doi.org/10.20430/ete.v88i350.857</a>
</div>
<div id="ref-hertwich2009" class="csl-entry" role="listitem">
Hertwich, E. G. y Peters, G. P. (2009). Carbon footprint of nations: A global, trade-linked analysis. <em>Environmental Science &amp; Technology</em>, <em>43</em>(16), 6414-6420. <a href="https://doi.org/10.1021/es803496a">https://doi.org/10.1021/es803496a</a>
</div>
<div id="ref-malerba2024" class="csl-entry" role="listitem">
Malerba, D., Roscioli, F., Gaentzsch, A. y Ward, H. (2024). Changing carbon footprints and the consequent impacts of carbon taxes and cash transfers on poverty and inequality across years: A <span>P</span>eruvian case study. <em>Energy Policy</em>, <em>192</em>, 114246. <a href="https://doi.org/10.1016/j.enpol.2024.114246">https://doi.org/10.1016/j.enpol.2024.114246</a>
</div>
<div id="ref-millerblair2022" class="csl-entry" role="listitem">
Miller, R. E. y Blair, P. D. (2022). <em>Input-Output Analysis: Foundations and Extensions</em> (3.ª ed.). Cambridge University Press. <a href="https://doi.org/10.1017/9781108676212">https://doi.org/10.1017/9781108676212</a>
</div>
<div id="ref-oecdghgfp2025" class="csl-entry" role="listitem">
OECD. (2025). <em>Greenhouse gas footprints (<span>GHGFP</span>), edici<span>ó</span>n 2025: Principal indicators</em> [Conjunto de datos]. OECD. <a href="https://sdmx.oecd.org/public/rest/dataflow/OECD.STI.PIE/DSD_ICIO_GHG_MAIN_2025@DF_ICIO_GHG_MAIN_2025/1.0">https://sdmx.oecd.org/public/rest/dataflow/OECD.STI.PIE/DSD_ICIO_GHG_MAIN_2025@DF_ICIO_GHG_MAIN_2025/1.0</a>
</div>
<div id="ref-owen2026" class="csl-entry" role="listitem">
Owen, A. (2026). <em>Consumption-based accounts for the <span>UK</span>, 1990 to 2023: Summary of methods</em>. <span>Universidad de Leeds para el Department for Environment, Food and Rural Affairs</span>. <a href="https://assets.publishing.service.gov.uk/media/6a3ce626eaee00074150f449/UK_and_England_s_Carbon_Footprint_Summary_of_Methods_2026.pdf">https://assets.publishing.service.gov.uk/media/6a3ce626eaee00074150f449/UK_and_England_s_Carbon_Footprint_Summary_of_Methods_2026.pdf</a>
</div>
<div id="ref-peters2011" class="csl-entry" role="listitem">
Peters, G. P., Minx, J. C., Weber, C. L. y Edenhofer, O. (2011). Growth in emission transfers via international trade from 1990 to 2008. <em>Proceedings of the National Academy of Sciences</em>, <em>108</em>(21), 8903-8908. <a href="https://doi.org/10.1073/pnas.1006388108">https://doi.org/10.1073/pnas.1006388108</a>
</div>
<div id="ref-renner2018" class="csl-entry" role="listitem">
Renner, S. (2018). Poverty and distributional effects of a carbon tax in <span>M</span>exico. <em>Energy Policy</em>, <em>112</em>, 98-110. <a href="https://doi.org/10.1016/j.enpol.2017.10.011">https://doi.org/10.1016/j.enpol.2017.10.011</a>
</div>
<div id="ref-rivas2025" class="csl-entry" role="listitem">
Rivas, L. y Gomes, A. (2025). <em>Peru: Report on the Physical Energy Flow and Air Emissions Accounts Mission (February 3–7, 2025)</em> [Technical Assistance Report]. Fondo Monetario Internacional, Departamento de Estad<span>í</span>stica.
</div>
<div id="ref-romancollado2021" class="csl-entry" role="listitem">
Román-Collado, R., Sanz-Díaz, M. T. y Loja Pacheco, C. (2021). Towards the decarbonisation of <span>E</span>cuador: A multisectoral and multiregional analysis of its carbon footprint. <em>Environmental Science and Pollution Research</em>, <em>28</em>, 53412-53431. <a href="https://doi.org/10.1007/s11356-021-14521-1">https://doi.org/10.1007/s11356-021-14521-1</a>
</div>
<div id="ref-sanguinet2022" class="csl-entry" role="listitem">
Sanguinet, E. R., Azzoni, C. R. y Alvim, A. M. (2022). Resource-based industries and <span>CO2</span> emissions embedded in value chains: A regional analysis for selected countries in <span>L</span>atin <span>A</span>merica. <em>Atmosphere</em>, <em>13</em>(6), 856. <a href="https://doi.org/10.3390/atmos13060856">https://doi.org/10.3390/atmos13060856</a>
</div>
<div id="ref-stadler2018" class="csl-entry" role="listitem">
Stadler, K., Wood, R., Bulavskaya, T., Södersten, C.-J., Simas, M., Schmidt, S., Usubiaga, A., Acosta-Fernández, J., Kuenen, J., Bruckner, M., Giljum, S., Lutter, S., Merciai, S., Schmidt, J. H., Theurl, M. C., Plutzar, C., Kastner, T., Eisenmenger, N., Erb, K.-H., … Tukker, A. (2018). <span>EXIOBASE</span> 3: Developing a time series of detailed environmentally extended multi-regional input-output tables. <em>Journal of Industrial Ecology</em>, <em>22</em>(3), 502-515. <a href="https://doi.org/10.1111/jiec.12715">https://doi.org/10.1111/jiec.12715</a>
</div>
<div id="ref-stanger2024" class="csl-entry" role="listitem">
Stanger, M. y Guilhoto, J. (2024). <em>Peru: Report of the Diagnostic Mission on Macro-relevant Climate Change Statistics (July 10–14, 2023)</em> [Technical Assistance Report]. Fondo Monetario Internacional, Departamento de Estad<span>í</span>stica.
</div>
<div id="ref-sna2009" class="csl-entry" role="listitem">
United Nations. (2009). <em>System of National Accounts 2008</em>. United Nations.
</div>
<div id="ref-seea2014" class="csl-entry" role="listitem">
United Nations. (2014). <em>System of Environmental-Economic Accounting 2012: Central Framework</em>. United Nations.
</div>
<div id="ref-wang2024" class="csl-entry" role="listitem">
Wang, Z., Peng, H., Meng, J., Zheng, H., Li, J., Huo, J., Chen, Y., Wen, Q., Ma, X. y Guan, D. (2024). Enormous inter-country inequality of embodied carbon emissions and its driving forces in <span>S</span>outh <span>A</span>merica. <em>Global Environmental Change</em>, <em>89</em>, 102944. <a href="https://doi.org/10.1016/j.gloenvcha.2024.102944">https://doi.org/10.1016/j.gloenvcha.2024.102944</a>
</div>
<div id="ref-yamano2020" class="csl-entry" role="listitem">
Yamano, N. y Guilhoto, J. (2020). <em><span>CO2</span> emissions embodied in international trade and domestic final demand: Methodology and results using the <span>OECD</span> Inter-Country Input-Output Database</em> (OECD Science, Technology and Industry Working Papers 2020/11). OECD. <a href="https://doi.org/10.1787/8f2963b8-en">https://doi.org/10.1787/8f2963b8-en</a>
</div>
<div id="ref-zhong2020" class="csl-entry" role="listitem">
Zhong, H., Feng, K., Sun, L., Cheng, L. y Hubacek, K. (2020). Household carbon and energy inequality in <span>L</span>atin <span>A</span>merican and <span>C</span>aribbean countries. <em>Journal of Environmental Management</em>, <em>273</em>, 110979. <a href="https://doi.org/10.1016/j.jenvman.2020.110979">https://doi.org/10.1016/j.jenvman.2020.110979</a>
</div>
</div>
</section>
<section id="anexo-a.-glosario" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="anexo-a.-glosario">Anexo A. Glosario</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Término</th>
<th style="text-align: left;">Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Huella de carbono nacional</td>
<td style="text-align: left;">Emisiones de gases de efecto invernadero asociadas con la demanda final de los residentes de un país, dentro y fuera de su territorio</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inventario territorial</td>
<td style="text-align: left;">Registro de las emisiones que ocurren en el territorio de un país, sin importar quién las genera; es el que se reporta a la CMNUCC</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principio de residencia</td>
<td style="text-align: left;">Criterio de las cuentas nacionales que asigna las emisiones a las unidades cuyo centro de interés económico está en el país, donde sea que emitan</td>
</tr>
<tr class="even">
<td style="text-align: left;">Partidas puente</td>
<td style="text-align: left;">Líneas que concilian el total de la cuenta de emisiones con el total del inventario</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuentas de emisiones atmosféricas</td>
<td style="text-align: left;">Cuentas físicas del SEEA que presentan las emisiones por industria y por hogares, con las clasificaciones de las cuentas nacionales</td>
</tr>
<tr class="even">
<td style="text-align: left;">SEEA</td>
<td style="text-align: left;">Sistema de Contabilidad Ambiental y Económica, marco estadístico de Naciones Unidas para las cuentas ambientales</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuadros de oferta y utilización</td>
<td style="text-align: left;">Cuadros que muestran qué productos genera cada industria y qué productos usa cada industria y cada categoría de demanda final</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tabla de insumo-producto</td>
<td style="text-align: left;">Tabla derivada de los cuadros de oferta y utilización que muestra las compras entre industrias o entre productos</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matriz de requerimientos totales (inversa de Leontief)</td>
<td style="text-align: left;">Matriz que da la producción total, directa e indirecta, necesaria por cada unidad de demanda final</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coeficiente de emisión</td>
<td style="text-align: left;">Emisiones de una industria divididas entre su producción</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emisiones directas e indirectas</td>
<td style="text-align: left;">Las que ocurren en la producción propia frente a las que ocurren en la producción de los insumos que se usan</td>
</tr>
<tr class="even">
<td style="text-align: left;">Supuesto de tecnología doméstica</td>
<td style="text-align: left;">Supuesto de que los bienes importados se producen con la tecnología del país importador</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tabla multirregional (MRIO, ICIO)</td>
<td style="text-align: left;">Tabla de insumo-producto que incluye varios países y el comercio entre sus industrias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Precios básicos y precios de comprador</td>
<td style="text-align: left;">Precio que recibe el productor sin impuestos ni márgenes, frente al que paga el comprador</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RAS</td>
<td style="text-align: left;">Procedimiento iterativo que ajusta filas y columnas de una tabla hasta que coincidan con totales conocidos</td>
</tr>
<tr class="even">
<td style="text-align: left;"><em>Nowcast</em></td>
<td style="text-align: left;">Estimación de años recientes a partir de tendencias, cuando aún no hay datos observados</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CO2 equivalente</td>
<td style="text-align: left;">Unidad que expresa el efecto de distintos gases en términos del CO2, con potenciales de calentamiento global</td>
</tr>
<tr class="even">
<td style="text-align: left;">UTCUTS (LULUCF)</td>
<td style="text-align: left;">Uso de la tierra, cambio de uso de la tierra y silvicultura</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fuga de carbono</td>
<td style="text-align: left;">Traslado de producción intensiva en emisiones a otros países, que desplaza las emisiones sin reducirlas</td>
</tr>
<tr class="even">
<td style="text-align: left;">Concordancia</td>
<td style="text-align: left;">Tabla de correspondencia entre dos clasificaciones, por ejemplo entre el inventario y las industrias de las cuentas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">COICOP</td>
<td style="text-align: left;">Clasificación del consumo individual por finalidad, usada en las encuestas de gasto</td>
</tr>
<tr class="even">
<td style="text-align: left;">GTAP, WIOD, EXIOBASE, Eora, FIGARO</td>
<td style="text-align: left;">Bases de datos globales de insumo-producto utilizadas para estimar huellas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Incidencia de un impuesto</td>
<td style="text-align: left;">Reparto del costo de un impuesto entre los hogares, usualmente como porcentaje de su gasto</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gini</td>
<td style="text-align: left;">Índice de desigualdad entre 0 (igualdad total) y 1 (desigualdad máxima)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sector clave</td>
<td style="text-align: left;">Sector con encadenamientos hacia atrás y hacia delante superiores al promedio de la economía</td>
</tr>
<tr class="even">
<td style="text-align: left;">Encadenamiento hacia atrás y hacia delante</td>
<td style="text-align: left;">Cuánto compra un sector a sus proveedores y a cuántos sectores abastece</td>
</tr>
</tbody>
</table>
</section>
<section id="anexo-b.-contexto-de-la-asistencia-técnica-del-fmi-a-perú" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="anexo-b.-contexto-de-la-asistencia-técnica-del-fmi-a-perú">Anexo B. Contexto de la asistencia técnica del FMI a Perú</h2>
<p>Este anexo resume el contexto que motivó la preparación de la nota y aplica a Perú las consideraciones de las secciones anteriores. Se basa en los informes de las misiones del Departamento de Estadística del FMI de julio de 2023 y febrero de 2025 <span class="citation" data-cites="stanger2024 rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>; <a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span>.</p>
<section id="antecedentes" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="antecedentes">Antecedentes</h3>
<p>El Gobierno de Perú estableció su marco legal de cambio climático con la Ley N.° 30754 y, en 2020, elevó su meta de mitigación de 30% a 40% respecto del escenario de referencia a 2030, con un límite absoluto de 179 MtCO2e <span class="citation" data-cites="stanger2024 rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>; <a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span>. El monitoreo de las medidas cubre cinco sectores: energía, residuos, procesos industriales, agricultura y cambio de uso de suelo <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span>. Dos de ellos, la agricultura y el cambio de uso de suelo, quedan fuera de las series de CO2 por combustión de la sección 5, lo que subraya la conveniencia de una huella en CO2 equivalente.</p>
<p>El Departamento de Estadística del FMI, con apoyo de la Secretaría de Estado de Asuntos Económicos de Suiza, lanzó en marzo de 2023 un programa de estadísticas ambientales y de cambio climático. La misión diagnóstica de julio de 2023 recomendó tres productos con fecha meta de diciembre de 2024: cuentas de flujos de energía, cuentas de emisiones atmosféricas con cambio de uso de suelo y huellas de carbono domésticas, estas últimas a cargo del Ministerio del Ambiente (MINAM) y del INEI <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span>. La misión de febrero de 2025 revisó las cuentas físicas de energía y de emisiones del año 2019, fijó abril de 2025 como meta para su publicación experimental y propuso incluir la huella de carbono entre los usos de la cuenta de emisiones para su difusión <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>)</span>.</p>
<p>El INEI compila y difunde cuadros de oferta y utilización anuales de 2007 a 2021, con 101 industrias y 365 productos, sobre la base 2007; el cambio a la base 2019 estaba en curso <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span>. La misión de 2023 concluyó que, con cuentas de emisiones y cuadros actualizados, Perú estaría en buena posición para iniciar la compilación de huellas nacionales, y señaló sus usos: identificar industrias de alta y baja emisión y los productos cuyo consumo genera más emisiones, comparar las emisiones de alcance 1, 2 y 3 de una empresa con el promedio de su industria, y alimentar un modelo de precios del carbono para evaluar, por ejemplo, el efecto de un impuesto sobre la inflación <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024, párr. 36, 37</a> y 45)</span>. La misión de 2025 agregó el apoyo a las decisiones sobre impuestos o precios del carbono y la comprensión de los efectos de los ajustes de carbono en frontera <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025, párr. 3</a>)</span>.</p>
<p>Perú cuenta además con una plataforma de huella de organización: la Huella de Carbono Perú del MINAM, donde organizaciones públicas y privadas declaran sus emisiones a nivel de empresa <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>, apéndice A)</span>. Es una huella del tipo descrito en la sección 2.1 y no sustituye a la huella nacional.</p>
</section>
<section id="disponibilidad-de-datos" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="disponibilidad-de-datos">Disponibilidad de datos</h3>
<p>El <strong>?@tbl-datos</strong> resume el estado de las fuentes según las dos misiones.</p>
<table class="caption-top table">
<caption>Fuentes de datos para una huella de carbono en Perú</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Insumo</th>
<th style="text-align: left;">Institución y estado</th>
<th style="text-align: left;">Observación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cuadros de oferta y utilización</td>
<td style="text-align: left;">INEI; anuales de 2007 a 2021, 101 industrias y 365 productos, base 2007; cambio a la base 2019 en curso <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span></td>
<td style="text-align: left;">El proyecto dispone de los cuadros de 2019 a precios corrientes, con 365 productos y 101 industrias</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inventario nacional de gases de efecto invernadero</td>
<td style="text-align: left;">MINAM; último año publicado 2019</td>
<td style="text-align: left;">Difundido por INFOCARBONO; se usó una correspondencia uno a uno con las industrias para la mayoría de las clases <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Balance nacional de energía</td>
<td style="text-align: left;">Ministerio de Energía y Minas (MINEM); último año 2021, con series desde 1965</td>
<td style="text-align: left;">El consumo se presenta para siete industrias y siete grupos de productos; solo se publica en PDF, sin base de datos descargable <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Datos agropecuarios</td>
<td style="text-align: left;">Ministerio de Desarrollo Agrario y Riego (MIDAGRI)</td>
<td style="text-align: left;">Insumo de las emisiones agropecuarias y de cambio de uso de suelo <span class="citation" data-cites="stanger2024">(<a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cuentas físicas de energía y de emisiones 2019</td>
<td style="text-align: left;">INEI; versión experimental con ajustes por residencia</td>
<td style="text-align: left;">Meta de publicación: abril de 2025 <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fuentes para ajustes por residencia</td>
<td style="text-align: left;">Estadísticas de transporte, balanza de pagos, comercio exterior, turismo y Autoridad Portuaria</td>
<td style="text-align: left;">La misión recomendó solicitar oficialmente los datos de transporte marítimo <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Encuesta de hogares</td>
<td style="text-align: left;">INEI (ENAHO)</td>
<td style="text-align: left;">Necesaria para huellas por hogar o decil <span class="citation" data-cites="malerba2024">(<a href="#ref-malerba2024" role="doc-biblioref">Malerba et&nbsp;al., 2024</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Base multirregional</td>
<td style="text-align: left;">Externa (<strong>?@tbl-bases</strong>)</td>
<td style="text-align: left;">Para las emisiones incorporadas en las importaciones</td>
</tr>
</tbody>
</table>
<p>Las fuentes de energía y de emisiones están muy agregadas para el detalle por actividad que exige la cuenta; los datos de las cuentas nacionales y la información auxiliar permiten desagregarlas <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025, párr. 5</a> y 25)</span>. Los ajustes por residencia revisados en la misión de 2025 cubren el transporte acuático, aéreo y por carretera, las embarcaciones pesqueras, el turismo (no residentes en el territorio y residentes en el exterior) y el transporte por ductos <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025, párr. 32</a>)</span>. La pandemia afectó la disponibilidad y oportunidad de las fuentes <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025, párr. 1</a>)</span>.</p>
</section>
<section id="secuencia-de-compilación-sugerida" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="secuencia-de-compilación-sugerida">Secuencia de compilación sugerida</h3>
<p>La secuencia sigue el orden de las presentaciones 02 a 04 de este proyecto, que desarrollan el álgebra de insumo-producto, y las recomendaciones de las misiones:</p>
<ol type="1">
<li>Completar y validar las cuentas de emisiones de 2019, con la clasificación alineada a las 101 industrias de los cuadros.</li>
<li>Preparar los cuadros de oferta y utilización de 2019: márgenes de comercio y transporte, importaciones competitivas e impuestos, e importaciones no competitivas. Verificar los balances de productos y de industrias antes de continuar.</li>
<li>Calcular los coeficientes de emisión y la matriz de requerimientos totales.</li>
<li>Decidir el tratamiento de las importaciones (<strong>?@tbl-bases</strong>).</li>
<li>Calcular la huella por categoría de demanda final y por producto, y conciliarla con la cuenta de emisiones de producción mediante las partidas puente.</li>
<li>Documentar los metadatos y fijar el calendario de revisiones.</li>
</ol>
</section>
<section id="problemas-específicos-y-decisiones" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="problemas-específicos-y-decisiones">Problemas específicos y decisiones</h3>
<p>Además de los problemas generales del <strong>?@tbl-problemas-gen</strong>, las misiones señalan tres aspectos propios de la situación peruana. El primero es la agregación de las fuentes: el balance de energía y el inventario tienen menos detalle que las cuentas nacionales <span class="citation" data-cites="rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>)</span>. El segundo es la coordinación entre agencias: los datos ambientales están dispersos, en formatos distintos y sin un protocolo formal de intercambio, por lo que se propone un centro único de datos a cargo del INEI o del MINAM <span class="citation" data-cites="stanger2024 rivas2025">(<a href="#ref-rivas2025" role="doc-biblioref">Rivas y Gomes, 2025</a>; <a href="#ref-stanger2024" role="doc-biblioref">Stanger y Guilhoto, 2024</a>)</span>. El tercero es la oportunidad: el inventario más reciente corresponde a 2019 y el balance de energía a 2021, de modo que las fuentes no coinciden en el año.</p>
<p>Las decisiones de diseño de la sección 7 se concretan para Perú en cuatro puntos que conviene acordar con el INEI y el MINAM: el alcance de gases y el tratamiento del cambio de uso de suelo; el tratamiento de las importaciones, con una comparación frente a la referencia de la OCDE, que incluye a Perú como economía individual; el año 2019 como punto de partida, con un calendario para extender la serie; y el reparto de funciones entre ambas instituciones, con un protocolo de intercambio de datos en el marco del comité interinstitucional de estadísticas y cuentas ambientales y económicas.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>