<!DOCTYPE html>
<html lang="es"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Renato Vargas">
  <meta name="author" content="Con ejemplos de Joe St.&nbsp;Lawrence, consultor FMI">
  <title>Perú HC – Matrices rectangulares de insumo-producto</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-fd542209079e4ef8f2453008e73e312f.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script>
    window.MathJax = {
      "HTML-CSS": { scale: 80 }
    };
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="theme-title center" data-state="sin-footer">
  <h1 class="title">Matrices rectangulares de insumo-producto</h1>
  <p class="subtitle">De los cuadros de oferta y utilización al modelo de producto por industria</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Renato Vargas
</div>
        <p class="quarto-title-affiliation">
            Economista / Consultor FMI
          </p>
    </div>
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Con ejemplos de Joe St.&nbsp;Lawrence, consultor FMI
</div>
</div>
</div>

</section>
<section id="temas-a-tratar" class="slide level2 theme-content">
<h2>Temas a tratar</h2>
<ol type="1">
<li>Por qué matrices rectangulares.</li>
<li>Estructura del sistema producto por industria.</li>
<li>De precios de comprador a precios de productor.</li>
<li>El modelo de insumo-producto con matrices rectangulares.</li>
<li>Ejercicio numérico.</li>
</ol>
</section>
<section id="flujo-circular" class="slide level2">
<h2>El flujo circular de la economía</h2>
<p>Las cuentas nacionales organizan la información económica con base en la idea del flujo circular <span class="citation" data-cites="sna2009">(<a href="#/bibliografía" role="doc-biblioref" onclick="">United Nations, 2009</a>)</span>. En su forma más simple:</p>
<p><span class="math display">\[
Q + M = C + X + G + I
\]</span></p>
<p>El producto total (<span class="math inline">\(Q\)</span>) más las importaciones (<span class="math inline">\(M\)</span>) es igual al consumo final de bienes y servicios (<span class="math inline">\(C\)</span>), las exportaciones (<span class="math inline">\(X\)</span>), las compras del gobierno (<span class="math inline">\(G\)</span>) y la inversión en capital (<span class="math inline">\(I\)</span>). En un período dado, lo que se produce y se importa es igual a lo que se utiliza.</p>
<p>Esta ecuación se desagrega en los <strong>cuadros de oferta y utilización</strong>, que registran las transacciones por producto (filas) y por actividad económica o industria (columnas).</p>
</section>
<section id="cou" class="slide level2">
<h2>Cuadros de oferta y utilización</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Oferta</span></p>
<p>Muestra qué productos genera cada industria y cuánto se importa de cada producto. Se compila a precios básicos o de productor, y se le agregan los márgenes de comercio y transporte y los impuestos menos subsidios a los productos, para llegar a precios de comprador.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">Utilización</span></p>
<p>Muestra qué productos consume cada industria como insumo (consumo intermedio) y cuáles se destinan a la demanda final: hogares, gobierno, inversión y exportaciones. Se compila a precios de comprador.</p>
</div></div>
<p>El valor agregado de una industria es su producción menos su consumo intermedio. La suma del valor agregado de todas las industrias, más los impuestos netos a los productos, da el producto interno bruto.</p>
</section>
<section id="rectangulares" class="slide level2">
<h2>Por qué matrices rectangulares</h2>
<p>Un cuadro de insumo-producto cuadrado necesita que filas y columnas sean la misma lista. Los cuadros de oferta y utilización tienen productos en filas e industrias en columnas, y esas dos listas no coinciden: cada industria puede producir más de un producto y un producto puede ser producido por varias industrias <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 25%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Enfoque</th>
<th>Dimensión</th>
<th>Costo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Industria por industria</td>
<td>Cuadrada</td>
<td>Pierde detalle de producción primaria y secundaria; exige supuestos para reasignar la producción secundaria</td>
</tr>
<tr class="even">
<td>Producto por industria</td>
<td>Rectangular</td>
<td>Conserva el detalle por producto; requiere un paso adicional para llegar a la matriz de requerimientos totales</td>
</tr>
</tbody>
</table>
<p>El Sistema de Cuentas Nacionales sugiere el enfoque industria por industria <span class="citation" data-cites="sna2009">(<a href="#/bibliografía" role="doc-biblioref" onclick="">United Nations, 2009</a>)</span>. Aquí se trabaja el segundo, que conserva el detalle de los productos.</p>
</section>
<section id="diagrama" class="slide level2">
<h2>El diagrama del sistema</h2>
<table class="diagrama caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Productos</th>
<th data-quarto-table-cell-role="th">Industrias</th>
<th data-quarto-table-cell-role="th">Demanda final</th>
<th data-quarto-table-cell-role="th">Producto total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Productos</th>
<td class="vacio"></td>
<td class="bg-Z">\(\mathbf{U}\)<br>
<span class="small">productos × industrias</span></td>
<td class="bg-f">\(\mathbf{f}\)<br>
<span class="small">productos × 1</span></td>
<td class="bg-x">\(\mathbf{q}\)<br>
<span class="small">productos × 1</span></td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Industrias</th>
<td class="bg-V">\(\mathbf{V}\)<br>
<span class="small">industrias × productos</span></td>
<td class="vacio"></td>
<td class="vacio"></td>
<td class="bg-x">\(\mathbf{x}\)<br>
<span class="small">industrias × 1</span></td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Valor agregado</th>
<td class="vacio"></td>
<td class="bg-va">\(\mathbf{v}'\)<br>
<span class="small">1 × industrias</span></td>
<td class="vacio"></td>
<td class="vacio"></td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Insumos totales</th>
<td class="bg-x">\(\mathbf{q}'\)<br>
<span class="small">1 × productos</span></td>
<td class="bg-x">\(\mathbf{x}'\)<br>
<span class="small">1 × industrias</span></td>
<td class="vacio"></td>
<td class="vacio"></td>
</tr>
</tbody>
</table>
</section>
<section id="bloques" class="slide level2">
<h2>Qué contiene cada bloque</h2>
<ul>
<li><span class="bg-Z"><span class="math inline">\(\mathbf{U}\)</span></span>, matriz de <strong>utilización</strong> (también de absorción o de insumos): el elemento <span class="math inline">\(u_{ij}\)</span> es el valor de las compras del producto <span class="math inline">\(i\)</span> por la industria <span class="math inline">\(j\)</span>.</li>
<li><span class="bg-V"><span class="math inline">\(\mathbf{V}\)</span></span>, matriz de <strong>producción</strong> (en inglés, <em>Make</em>): el elemento <span class="math inline">\(v_{ij}\)</span> es el valor del producto <span class="math inline">\(j\)</span> producido por la industria <span class="math inline">\(i\)</span>.</li>
<li><span class="bg-f"><span class="math inline">\(\mathbf{f}\)</span></span>, vector de demanda final por producto.</li>
<li><span class="bg-x"><span class="math inline">\(\mathbf{x}\)</span></span>, producto total por industria, y <span class="bg-x"><span class="math inline">\(\mathbf{q}\)</span></span>, producto total por producto.</li>
<li><span class="bg-va"><span class="math inline">\(\mathbf{v}'\)</span></span>, vector fila de valor agregado por industria.</li>
</ul>
<p>Con <span class="math inline">\(\mathbf{i}\)</span> como vector sumatorio del tamaño apropiado, los totales salen de sumar las filas y columnas de <span class="math inline">\(\mathbf{V}\)</span> <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>:</p>
<p><span class="math display">\[
\bbox[#A6C9EC,3px]{\mathbf{x}} = \bbox[#FFF0A6,3px]{\mathbf{V}}\mathbf{i} \qquad\qquad \bbox[#A6C9EC,3px]{\mathbf{q}} = \bbox[#FFF0A6,3px]{\mathbf{V}}'\mathbf{i}
\]</span></p>
</section>
<section id="identidades" class="slide level2">
<h2>Identidades del sistema</h2>
<p>El producto de cada producto se vende como insumo a las industrias o a la demanda final. Los insumos de cada industria se completan con el valor agregado:</p>
<p><span class="math display">\[
\bbox[#A6C9EC,3px]{\mathbf{q}} = \bbox[#B5E6A2,3px]{\mathbf{U}}\mathbf{i} + \bbox[#F2CEEF,3px]{\mathbf{f}} \qquad\qquad \bbox[#A6C9EC,3px]{\mathbf{x}}' = \mathbf{i}'\bbox[#B5E6A2,3px]{\mathbf{U}} + \bbox[#D9D6F0,3px]{\mathbf{v}'}
\]</span></p>
<p>Son los mismos balances del modelo con una matriz cuadrada, <span class="math inline">\(\mathbf{x} = \mathbf{Z}\mathbf{i} + \mathbf{f}\)</span>, pero con dos clasificaciones distintas: la primera ecuación está en términos de productos y la segunda en términos de industrias.</p>
<p>Esa diferencia es el problema central de este modelo y se resuelve más adelante.</p>
</section>
<section id="datos-u" class="slide level2">
<h2>Datos del ejercicio: utilización</h2>
<p>Un ejercicio con 8 productos y 5 industrias, adaptado de un ejercicio de extensiones ambientales. Los valores son monetarios.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a>U</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            granjas minas alimentos manufacturas servicios
ganado           10     0        80           10         0
hierro            0     0         0          100         0
leche            10     5       100            0         5
queso             0     5         0            0         5
combustible     100   200        10           50        50
acero             0     5         0          145         0
autos            10     5         5            5        10
publicidad        5    15        20           40        20</code></pre>
</div>
</div>
</div></div>
</section>
<section id="datos-v" class="slide level2">
<h2>Datos del ejercicio: producción</h2>
<p>Las minas producen hierro y combustible; las manufacturas producen combustible, acero y autos. Es producción secundaria, que un cuadro cuadrado tendría que reasignar.</p>
<div class="columns">
<div class="column" style="width:40%;">
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:60%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a>V</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             ganado hierro leche queso combustible acero autos publicidad
granjas         100      0   100    10           0     0     0          0
minas             0    100     0     0        1000     0     0          0
alimentos         0      0    80   200           0     0     0          0
manufacturas      0      0     0     0          10   150   200          0
servicios         0      0     0     0           0     0     0        100</code></pre>
</div>
</div>
</div></div>
</section>
<section id="datos-e" class="slide level2">
<h2>Datos del ejercicio: demanda final y valor agregado</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a>f <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">60</span>, <span class="dv">200</span>, <span class="dv">600</span>, <span class="dv">0</span>, <span class="dv">165</span>, <span class="dv">0</span>)</span>
<span id="cb5-2"><a aria-label="2"></a><span class="fu">names</span>(f) <span class="ot">&lt;-</span> productos</span>
<span id="cb5-3"><a aria-label="3"></a>f</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ganado      hierro       leche       queso combustible       acero 
          0           0          60         200         600           0 
      autos  publicidad 
        165           0 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a>va <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">75</span>, <span class="dv">865</span>, <span class="dv">65</span>, <span class="dv">10</span>, <span class="dv">10</span>)</span>
<span id="cb7-2"><a aria-label="2"></a><span class="fu">names</span>(va) <span class="ot">&lt;-</span> industrias</span>
<span id="cb7-3"><a aria-label="3"></a>va</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     granjas        minas    alimentos manufacturas    servicios 
          75          865           65           10           10 </code></pre>
</div>
</div>
</section>
<section id="balances" class="slide level2">
<h2>Totales y balances</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\bbox[#A6C9EC,3px]{\mathbf{x}} = \bbox[#FFF0A6,3px]{\mathbf{V}}\mathbf{i} \qquad \bbox[#A6C9EC,3px]{\mathbf{q}} = \bbox[#FFF0A6,3px]{\mathbf{V}}'\mathbf{i}
\]</span></p>
<p><span class="math display">\[
\mathbf{q} = \mathbf{U}\mathbf{i} + \mathbf{f}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a>ic <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">8</span>)</span>
<span id="cb9-2"><a aria-label="2"></a>ii <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">5</span>)</span>
<span id="cb9-3"><a aria-label="3"></a></span>
<span id="cb9-4"><a aria-label="4"></a>x <span class="ot">&lt;-</span> V <span class="sc">%*%</span> ic</span>
<span id="cb9-5"><a aria-label="5"></a>q <span class="ot">&lt;-</span> <span class="fu">t</span>(V) <span class="sc">%*%</span> ii</span>
<span id="cb9-6"><a aria-label="6"></a></span>
<span id="cb9-7"><a aria-label="7"></a><span class="co"># Producto total contra utilización más demanda final</span></span>
<span id="cb9-8"><a aria-label="8"></a><span class="fu">cbind</span>(q, U <span class="sc">%*%</span> ii <span class="sc">+</span> f)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1] [,2]
ganado       100  100
hierro       100  100
leche        180  180
queso        210  210
combustible 1010 1010
acero        150  150
autos        200  200
publicidad   100  100</code></pre>
</div>
</div>
</div></div>
</section>
<section id="balance-x" class="slide level2">
<h2>Totales por industria</h2>
<p>Cada industria usa insumos y valor agregado por el mismo valor que su producto total.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a><span class="fu">cbind</span>(x, <span class="fu">colSums</span>(U) <span class="sc">+</span> va)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1] [,2]
granjas       210  210
minas        1100 1100
alimentos     280  280
manufacturas  360  360
servicios     100  100</code></pre>
</div>
</div>
<p>Si ambas columnas coinciden en todas las filas, el cuadro es consistente. Esta revisión es la calibración del sistema: sin ella, los pasos siguientes no reproducen los datos originales.</p>
</section>
<section id="precios-contexto" class="slide level2">
<h2>Una matriz cuadrada vive en un solo juego de precios</h2>
<p>En un cuadro cuadrado, cada flujo está valorado de la misma manera: todo a precios de comprador, o todo a precios de productor, y todo incluyendo importaciones o todo solo producción nacional. Así, lo que vende una fila coincide con lo que compra una columna, y los coeficientes técnicos tienen sentido.</p>
<p>Los cuadros de oferta y utilización no cumplen esa condición: la oferta se registra a precios de productor y la utilización a precios de comprador.</p>
</section>
<section id="precios-ejemplo" class="slide level2">
<h2>Un mismo producto, dos precios</h2>
<p>Un producto cambia de precio en el camino de la fábrica al comprador:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Concepto</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Precio de productor (a la puerta de la fábrica)</td>
<td style="text-align: right;">100</td>
</tr>
<tr class="even">
<td>Más margen de comercio</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="odd">
<td>Más margen de transporte</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>Más impuestos menos subsidios a los productos</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td><strong>Precio de comprador</strong></td>
<td style="text-align: right;"><strong>135</strong></td>
</tr>
</tbody>
</table>
<p>La oferta registra los 100; la utilización registra los 135. Si se combinan tal cual, el total de un producto en la oferta no coincide con el de la utilización, y los 35 de diferencia se atribuirían a la industria que lo compra, aunque corresponden al comercio, al transporte y al gobierno.</p>
<p>Antes de calcular coeficientes hay que llevar la utilización al mismo juego de precios que la oferta. Se hace en tres ajustes: márgenes, importaciones competitivas e impuestos.</p>
</section>
<section id="margenes" class="slide level2">
<h2>De precios de comprador a precios de productor: márgenes</h2>
<p>La utilización está a precios de comprador y la oferta a precios de productor. Cada transacción de la utilización incluye los márgenes de comercio y transporte (y de servicios como electricidad y agua) que llevan el producto al punto de compra.</p>
<p>Se supone que, para cada producto, la proporción de margen es la misma en todas sus compras. Con ese supuesto:</p>
<ol type="1">
<li>Se resta el margen de cada fila de la matriz de utilización.</li>
<li>Se suman los márgenes extraídos en un vector fila.</li>
<li>Se vuelven a agregar en la fila del servicio que representa el margen (comercio, transporte, etc.).</li>
</ol>
<p>Los márgenes pasan a ser insumos de servicios para cada industria. Se aplica el mismo procedimiento al vector de demanda final. Las matrices resultantes se denotan <span class="math inline">\(\widetilde{\mathbf{U}}\)</span> y <span class="math inline">\(\widetilde{\mathbf{f}}\)</span>; la tilde indica que todavía contienen impuestos e importaciones competitivas.</p>
</section>
<section id="importaciones" class="slide level2">
<h2>Importaciones competitivas e impuestos: planteamiento</h2>
<p>Los coeficientes técnicos deben describir transacciones entre industrias nacionales. Si <span class="math inline">\(\widetilde{\mathbf{U}}\)</span> incluye compras a productores extranjeros e impuestos, un aumento de la demanda final aparecería como producción de industrias extranjeras con tecnología local. Eso no tiene sentido, y hay que quitar ambos elementos:</p>
<p><span class="math display">\[
\widetilde{\mathbf{U}} = \mathbf{U} + \mathbf{U}^m + \mathbf{U}^t
\]</span></p>
<p><span class="math inline">\(\mathbf{U}^m\)</span> (importaciones) y <span class="math inline">\(\mathbf{U}^t\)</span> (impuestos menos subsidios a los productos) no se conocen. De los cuadros se conocen sus totales por producto: el vector de importaciones <span class="math inline">\(\mathbf{m}\)</span> y el vector de impuestos <span class="math inline">\(\mathbf{t}\)</span>.</p>
</section>
<section id="estimacion-m-t" class="slide level2">
<h2>Importaciones competitivas e impuestos: estimación</h2>
<p>Se supone que la fracción de cada producto que proviene de importaciones es la misma para todas las industrias y para la demanda final. Esa fracción es <span class="math inline">\(r_i\)</span>, y de forma análoga <span class="math inline">\(s_i\)</span> para los impuestos:</p>
<p><span class="math display">\[
r_i = \frac{m_i}{\widetilde{u}_i + \widetilde{f}_i} \qquad\qquad s_i = \frac{t_i}{\widetilde{u}_i + \widetilde{f}_i}
\]</span></p>
<p>Con las fracciones en matrices diagonales <span class="math inline">\(\widehat{\mathbf{r}}\)</span> y <span class="math inline">\(\widehat{\mathbf{s}}\)</span>, se restan de la utilización y de la demanda final <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>:</p>
<p><span class="math display">\[
\bbox[#B5E6A2,3px]{\mathbf{U}} = \widetilde{\mathbf{U}} - \widehat{\mathbf{r}}\widetilde{\mathbf{U}} - \widehat{\mathbf{s}}\widetilde{\mathbf{U}} \qquad\qquad \bbox[#F2CEEF,3px]{\mathbf{f}} = \widetilde{\mathbf{f}} - \widehat{\mathbf{r}}\widetilde{\mathbf{f}} - \widehat{\mathbf{s}}\widetilde{\mathbf{f}}
\]</span></p>
<p>Las importaciones no competitivas (productos que el país no produce) suelen tratarse como producción de una industria adicional sin insumos, y se descuentan en la demanda final.</p>
</section>
<section id="modelo-cuadrado" class="slide level2">
<h2>El punto de partida: el modelo con matriz cuadrada</h2>
<p>Con una matriz de flujos <span class="math inline">\(\mathbf{Z}\)</span> entre industrias, un vector de demanda final <span class="math inline">\(\mathbf{f}\)</span> y un vector de producto <span class="math inline">\(\mathbf{x}\)</span> <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>:</p>
<p><span class="math display">\[
\mathbf{x} = \mathbf{Z}\mathbf{i} + \mathbf{f} \qquad \mathbf{A} = \mathbf{Z}\widehat{\mathbf{x}}^{-1} \qquad \mathbf{x} = (\mathbf{I} - \mathbf{A})^{-1}\mathbf{f} = \mathbf{L}\mathbf{f}
\]</span></p>
<p>Los coeficientes técnicos <span class="math inline">\(a_{ij}\)</span> dicen cuánto compra la industria <span class="math inline">\(j\)</span> a la industria <span class="math inline">\(i\)</span> por unidad de producción, y <span class="math inline">\(\mathbf{L}\)</span> dice cuánto debe producir cada industria, directa e indirectamente, para satisfacer la demanda final.</p>
<p>Con matrices rectangulares hay que encontrar un equivalente de cada elemento.</p>
</section>
<section id="matriz-b" class="slide level2">
<h2>Coeficientes de insumo por producto: la matriz B</h2>
<p>El primer paso es reemplazar <span class="math inline">\(\mathbf{Z}\)</span> por la matriz de utilización <span class="bg-Z"><span class="math inline">\(\mathbf{U}\)</span></span>. El coeficiente equivalente es <span class="math inline">\(b_{ij} = u_{ij}/x_j\)</span>: el valor del producto <span class="math inline">\(i\)</span> que usa la industria <span class="math inline">\(j\)</span> por unidad de su producción.</p>
<p><span class="math display">\[
\mathbf{B} = \bbox[#B5E6A2,3px]{\mathbf{U}}\bbox[#A6C9EC,3px]{\widehat{\mathbf{x}}}^{-1}
\]</span></p>
<p><span class="math inline">\(\mathbf{B}\)</span> es de productos por industrias, igual que <span class="bg-Z"><span class="math inline">\(\mathbf{U}\)</span></span>. Con <span class="math inline">\(\mathbf{U}\mathbf{i} = \mathbf{B}\mathbf{x}\)</span> (igual que <span class="math inline">\(\mathbf{Z}\mathbf{i} = \mathbf{A}\mathbf{x}\)</span>), la identidad de los productos queda:</p>
<p><span class="math display">\[
\bbox[#A6C9EC,3px]{\mathbf{q}} = \mathbf{B}\bbox[#A6C9EC,3px]{\mathbf{x}} + \bbox[#F2CEEF,3px]{\mathbf{f}}
\]</span></p>
</section>
<section id="problema" class="slide level2">
<h2>El problema: dos clasificaciones en una ecuación</h2>
<p>En <span class="math inline">\(\mathbf{q} = \mathbf{B}\mathbf{x} + \mathbf{f}\)</span>, el lado izquierdo está en términos de productos (<span class="math inline">\(\mathbf{q}\)</span>) y el derecho mezcla industrias (<span class="math inline">\(\mathbf{x}\)</span>) con productos (<span class="math inline">\(\mathbf{f}\)</span>).</p>
<p>No se puede factorizar ni invertir de la misma forma que en el modelo cuadrado. Hay que pasar el producto de las industrias a productos, o la demanda final a términos de industrias.</p>
<p>Para ello se necesita saber qué fracción de cada producto fabrica cada industria.</p>
</section>
<section id="matriz-d" class="slide level2">
<h2>La matriz de participación de mercado: D</h2>
<p>El elemento <span class="math inline">\(d_{ij} = v_{ij}/q_j\)</span> es la fracción del producto <span class="math inline">\(j\)</span> que fabrica la industria <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[
\mathbf{D} = \bbox[#FFF0A6,3px]{\mathbf{V}}\bbox[#A6C9EC,3px]{\widehat{\mathbf{q}}}^{-1}
\]</span></p>
<p><span class="math inline">\(\mathbf{D}\)</span> es de industrias por productos. Por definición, cada columna suma 1.</p>
<p>Despejando, <span class="math inline">\(\mathbf{D}\widehat{\mathbf{q}} = \mathbf{V}\)</span>. Posmultiplicando ambos lados por <span class="math inline">\(\mathbf{i}\)</span>, y recordando que <span class="math inline">\(\widehat{\mathbf{q}}\mathbf{i} = \mathbf{q}\)</span> y <span class="math inline">\(\mathbf{V}\mathbf{i} = \mathbf{x}\)</span>:</p>
<p><span class="math display">\[
\mathbf{D}\widehat{\mathbf{q}}\mathbf{i} = \mathbf{V}\mathbf{i} \quad \Rightarrow \quad \mathbf{D}\bbox[#A6C9EC,3px]{\mathbf{q}} = \bbox[#A6C9EC,3px]{\mathbf{x}}
\]</span></p>
</section>
<section id="sistema" class="slide level2">
<h2>Un solo sistema con dos ecuaciones</h2>
<p>Dos relaciones conectan a <span class="math inline">\(\mathbf{x}\)</span> y <span class="math inline">\(\mathbf{q}\)</span>:</p>
<p><span class="math display">\[
\mathbf{x} - \mathbf{D}\mathbf{q} = \mathbf{0} \qquad\qquad -\mathbf{B}\mathbf{x} + \mathbf{q} = \mathbf{f}
\]</span></p>
<p>Se pueden escribir como un sistema particionado de ecuaciones lineales, que se resolvería con la inversa de la matriz de coeficientes:</p>
<p><span class="math display">\[
\begin{bmatrix} \mathbf{I} &amp; -\mathbf{D} \\ -\mathbf{B} &amp; \mathbf{I} \end{bmatrix}
\begin{bmatrix} \mathbf{x} \\ \mathbf{q} \end{bmatrix} =
\begin{bmatrix} \mathbf{0} \\ \mathbf{f} \end{bmatrix}
\]</span></p>
<p>Con una sustitución se llega a una expresión más compacta.</p>
</section>
<section id="despeje" class="slide level2">
<h2>La matriz de requerimientos totales: despeje</h2>
<p>Se premultiplica <span class="math inline">\(\mathbf{q} = \mathbf{B}\mathbf{x} + \mathbf{f}\)</span> por <span class="math inline">\(\mathbf{D}\)</span>:</p>
<p><span class="math display">\[
\mathbf{D}\mathbf{q} = \mathbf{D}\mathbf{B}\mathbf{x} + \mathbf{D}\mathbf{f}
\]</span></p>
<p>Como <span class="math inline">\(\mathbf{D}\mathbf{q} = \mathbf{x}\)</span>, el lado izquierdo es <span class="math inline">\(\mathbf{x}\)</span>, y la ecuación queda en una sola clasificación, la de industrias:</p>
<p><span class="math display">\[
\mathbf{x} = \mathbf{D}\mathbf{B}\mathbf{x} + \mathbf{D}\mathbf{f}
\]</span></p>
<p>Igual que en el modelo cuadrado, se pasa <span class="math inline">\(\mathbf{D}\mathbf{B}\mathbf{x}\)</span> restando, se usa <span class="math inline">\(\mathbf{x} = \mathbf{I}\mathbf{x}\)</span> para factorizar, y se premultiplica por la inversa:</p>
<p><span class="math display">\[
(\mathbf{I} - \mathbf{D}\mathbf{B})\mathbf{x} = \mathbf{D}\mathbf{f} \quad \Rightarrow \quad \bbox[#A6C9EC,3px]{\mathbf{x}} = \bbox[#F7C7AC,3px]{(\mathbf{I} - \mathbf{D}\mathbf{B})^{-1}\mathbf{D}}\bbox[#F2CEEF,3px]{\mathbf{f}}
\]</span></p>
</section>
<section id="interpretacion" class="slide level2">
<h2>La matriz de requerimientos totales: interpretación</h2>
<p><span class="math display">\[
\bbox[#F7C7AC,3px]{\mathbf{T}} = (\mathbf{I} - \mathbf{D}\mathbf{B})^{-1}\mathbf{D} \qquad\qquad \mathbf{x} = \mathbf{T}\mathbf{f}
\]</span></p>
<p><span class="bg-L"><span class="math inline">\(\mathbf{T}\)</span></span> es la matriz de requerimientos totales de industrias por productos, el equivalente de <span class="math inline">\(\mathbf{L}\)</span> del modelo cuadrado <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>. Cada elemento dice cuántas unidades de producción de la industria de la fila se requieren, directa e indirectamente, para entregar una unidad de demanda final del producto de la columna.</p>
<p>Es rectangular: tiene tantas filas como industrias y tantas columnas como productos. La demanda final se expresa por producto y la producción resultante se obtiene por industria.</p>
</section>
<section id="practica-b" class="slide level2">
<h2>Paso 1: la matriz B en la práctica</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{B} = \bbox[#B5E6A2,3px]{\mathbf{U}}\bbox[#A6C9EC,3px]{\widehat{\mathbf{x}}}^{-1}
\]</span></p>
<p>Es de 8 × 5, igual que <span class="math inline">\(\mathbf{U}\)</span>.</p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a>B <span class="ot">&lt;-</span> U <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">diag</span>(<span class="fu">c</span>(x)))</span>
<span id="cb13-2"><a aria-label="2"></a><span class="fu">dimnames</span>(B) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(U)</span>
<span id="cb13-3"><a aria-label="3"></a><span class="fu">round</span>(B, <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            granjas minas alimentos manufacturas servicios
ganado        0.048 0.000     0.286        0.028      0.00
hierro        0.000 0.000     0.000        0.278      0.00
leche         0.048 0.005     0.357        0.000      0.05
queso         0.000 0.005     0.000        0.000      0.05
combustible   0.476 0.182     0.036        0.139      0.50
acero         0.000 0.005     0.000        0.403      0.00
autos         0.048 0.005     0.018        0.014      0.10
publicidad    0.024 0.014     0.071        0.111      0.20</code></pre>
</div>
</div>
</div></div>
</section>
<section id="practica-d" class="slide level2">
<h2>Paso 2: la matriz D en la práctica</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{D} = \bbox[#FFF0A6,3px]{\mathbf{V}}\bbox[#A6C9EC,3px]{\widehat{\mathbf{q}}}^{-1}
\]</span></p>
<p>Es de 5 × 8, igual que <span class="math inline">\(\mathbf{V}\)</span>, y cada columna suma 1.</p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-label="1"></a>D <span class="ot">&lt;-</span> V <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">diag</span>(<span class="fu">c</span>(q)))</span>
<span id="cb15-2"><a aria-label="2"></a><span class="fu">dimnames</span>(D) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(V)</span>
<span id="cb15-3"><a aria-label="3"></a><span class="fu">round</span>(D, <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             ganado hierro leche queso combustible acero autos publicidad
granjas           1      0 0.556 0.048        0.00     0     0          0
minas             0      1 0.000 0.000        0.99     0     0          0
alimentos         0      0 0.444 0.952        0.00     0     0          0
manufacturas      0      0 0.000 0.000        0.01     1     1          0
servicios         0      0 0.000 0.000        0.00     0     0          1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-label="1"></a><span class="co"># Cada columna suma 1</span></span>
<span id="cb17-2"><a aria-label="2"></a><span class="fu">colSums</span>(D)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ganado      hierro       leche       queso combustible       acero 
          1           1           1           1           1           1 
      autos  publicidad 
          1           1 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="practica-db" class="slide level2">
<h2>Paso 3: DB e I menos DB</h2>
<p><span class="math inline">\(\mathbf{D}\mathbf{B}\)</span> es de 5 × 5 (industrias por industrias), por lo que ya se le puede restar una identidad y, si el sistema es consistente, invertir.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{D}\mathbf{B} \qquad\qquad \mathbf{I} - \mathbf{D}\mathbf{B}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-label="1"></a>DB <span class="ot">&lt;-</span> D <span class="sc">%*%</span> B</span>
<span id="cb19-2"><a aria-label="2"></a><span class="fu">dim</span>(DB)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-label="1"></a>IDB <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">nrow</span>(DB)) <span class="sc">-</span> DB</span>
<span id="cb21-2"><a aria-label="2"></a><span class="fu">round</span>(IDB, <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             granjas  minas alimentos manufacturas servicios
granjas        0.926 -0.003    -0.484       -0.028    -0.030
minas         -0.471  0.820    -0.035       -0.415    -0.495
alimentos     -0.021 -0.006     0.841        0.000    -0.070
manufacturas  -0.052 -0.011    -0.018        0.582    -0.105
servicios     -0.024 -0.014    -0.071       -0.111     0.800</code></pre>
</div>
</div>
</div></div>
</section>
<section id="practica-t" class="slide level2">
<h2>Paso 4: la matriz de requerimientos totales</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\bbox[#F7C7AC,3px]{\mathbf{T}} = (\mathbf{I} - \mathbf{D}\mathbf{B})^{-1}\mathbf{D}
\]</span></p>
<p>Es de 5 × 8.</p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-label="1"></a>Treq <span class="ot">&lt;-</span> <span class="fu">solve</span>(IDB) <span class="sc">%*%</span> D</span>
<span id="cb23-2"><a aria-label="2"></a><span class="fu">dimnames</span>(Treq) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(V)</span>
<span id="cb23-3"><a aria-label="3"></a><span class="fu">round</span>(Treq, <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             ganado hierro leche queso combustible acero autos publicidad
granjas       1.109  0.012 0.905 0.672       0.013 0.084 0.084      0.117
minas         0.744  1.258 0.676 0.598       1.257 1.125 1.125      1.006
alimentos     0.039  0.012 0.565 1.166       0.012 0.033 0.033      0.120
manufacturas  0.127  0.030 0.131 0.136       0.047 1.797 1.797      0.271
servicios     0.067  0.027 0.107 0.153       0.029 0.274 0.274      1.319</code></pre>
</div>
</div>
</div></div>
</section>
<section id="calibracion" class="slide level2">
<h2>Calibración del modelo</h2>
<p>Si <span class="math inline">\(\mathbf{T}\mathbf{f}\)</span> devuelve el producto total observado de las industrias, el modelo es consistente con los cuadros originales.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\bbox[#F7C7AC,3px]{\mathbf{T}}\bbox[#F2CEEF,3px]{\mathbf{f}} = \begin{bmatrix} 210 \\ 1100 \\ 280 \\ 360 \\ 100 \end{bmatrix} = \bbox[#A6C9EC,3px]{\mathbf{x}}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a>Treq <span class="sc">%*%</span> f</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]
granjas       210
minas        1100
alimentos     280
manufacturas  360
servicios     100</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-label="1"></a><span class="co"># Comparación con x</span></span>
<span id="cb27-2"><a aria-label="2"></a><span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">c</span>(Treq <span class="sc">%*%</span> f), <span class="fu">c</span>(x)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</div></div>
</section>
<section id="escenario" class="slide level2">
<h2>Un escenario de demanda final</h2>
<p>La demanda final de autos aumenta en 100 unidades monetarias. La matriz <span class="bg-L"><span class="math inline">\(\mathbf{T}\)</span></span> no cambia: la tecnología es la misma y cambia solo la demanda.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\Delta\mathbf{f} = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 0 \\ 100 \\ 0 \end{bmatrix} \quad \Rightarrow \quad \Delta\mathbf{x} = \bbox[#F7C7AC,3px]{\mathbf{T}}\Delta\mathbf{f}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-label="1"></a>deltaf <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">0</span>)</span>
<span id="cb29-2"><a aria-label="2"></a></span>
<span id="cb29-3"><a aria-label="3"></a>deltax <span class="ot">&lt;-</span> Treq <span class="sc">%*%</span> deltaf</span>
<span id="cb29-4"><a aria-label="4"></a><span class="fu">round</span>(deltax, <span class="dv">2</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               [,1]
granjas        8.36
minas        112.55
alimentos      3.34
manufacturas 179.74
servicios     27.43</code></pre>
</div>
</div>
</div></div>
</section>
<section id="lectura-escenario" class="slide level2">
<h2>Qué pasó con el escenario</h2>
<p>El estímulo es un solo número, pero la producción cambia en las cinco industrias. Los autos los fabrica la industria de manufacturas, y el aumento de su producción excede la demanda adicional porque necesita insumos (acero, combustible) que ella misma produce o que compra a otras industrias.</p>
<ul>
<li><strong>Manufacturas (179.74):</strong> producen los 100 de autos y los insumos que ellas mismas consumen para hacerlos, incluido el acero.</li>
<li><strong>Minas (112.55):</strong> abastecen el combustible que usan manufacturas y las demás industrias.</li>
<li><strong>Servicios (27.43):</strong> venden publicidad a las demás industrias.</li>
<li><strong>Granjas (8.36) y alimentos (3.34):</strong> reciben el efecto indirecto más pequeño.</li>
</ul>
<p>El resultado se lee por industria aunque el estímulo se defina por producto. Esa es la ventaja del enfoque rectangular.</p>
</section>
<section id="extension" class="slide level2">
<h2>Extensión ambiental</h2>
<p>Una extensión ambiental asigna a cada industria una intensidad de emisiones por unidad de producción, <span class="math inline">\(\boldsymbol{\varepsilon}'\)</span> (1 × 5). El ejercicio usa valores ilustrativos.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\boldsymbol{\varepsilon}'\mathbf{x} \qquad\qquad \boldsymbol{\varepsilon}'\bbox[#F7C7AC,3px]{\mathbf{T}}
\]</span></p>
<p>El segundo producto es un vector de 1 × 8: las emisiones, directas e indirectas, por unidad de demanda final de cada producto.</p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-label="1"></a>epsilon <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.8</span>, <span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">0.1</span>)</span>
<span id="cb31-2"><a aria-label="2"></a></span>
<span id="cb31-3"><a aria-label="3"></a><span class="co"># Emisiones totales</span></span>
<span id="cb31-4"><a aria-label="4"></a><span class="fu">sum</span>(epsilon <span class="sc">*</span> x)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1223</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-label="1"></a><span class="co"># Multiplicadores por producto</span></span>
<span id="cb33-2"><a aria-label="2"></a><span class="fu">round</span>(epsilon <span class="sc">%*%</span> Treq, <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ganado hierro leche queso combustible acero autos publicidad
[1,]  1.218  1.031 1.226 1.234       1.037 1.699 1.699      1.139</code></pre>
</div>
</div>
</div></div>
</section>
<section id="multiplicadores-producto" class="slide level2">
<h2>Multiplicadores: por qué salen por producto</h2>
<p>Las dimensiones de <span class="math inline">\(\mathbf{T}\)</span> explican el resultado: tiene industrias en las filas y productos en las columnas.</p>
<ul>
<li><strong>Filas (industrias):</strong> la producción, y con ella las emisiones, ocurre en las industrias. Por eso <span class="math inline">\(\boldsymbol{\varepsilon}'\)</span> es un vector de 1 × 5.</li>
<li><strong>Columnas (productos):</strong> la demanda final compra productos, no producción de industrias. Por eso <span class="math inline">\(\mathbf{f}\)</span> es un vector de 8 × 1.</li>
</ul>
<p>Al multiplicar <span class="math inline">\(\boldsymbol{\varepsilon}'\)</span> (1 × 5) por <span class="math inline">\(\mathbf{T}\)</span> (5 × 8), las industrias se suman y quedan los productos: un multiplicador (1 × 8) por cada producto que se demanda.</p>
<p>La matriz <span class="math inline">\(\mathbf{D}\)</span> hace el traslado. Una unidad de demanda del producto <span class="math inline">\(j\)</span> se reparte entre las industrias que lo fabrican, según su participación de mercado <span class="math inline">\(d_{ij}\)</span>, y cada una de ellas activa su propia cadena de insumos. En el modelo cuadrado, producto e industria son la misma lista y esta distinción desaparece.</p>
</section>
<section id="multiplicadores-calculo" class="slide level2">
<h2>Multiplicadores: cálculo</h2>
<p>El multiplicador de un producto es la cantidad de emisiones que se genera, directa e indirectamente, en toda la economía por cada unidad monetaria de demanda final de ese producto. El multiplicador directo incluye solo las emisiones de las industrias que lo fabrican.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\text{directo} = \boldsymbol{\varepsilon}'\mathbf{D}
\]</span></p>
<p><span class="math display">\[
\text{total} = \boldsymbol{\varepsilon}'\bbox[#F7C7AC,3px]{\mathbf{T}}
\]</span></p>
<p><span class="math display">\[
\text{indirecto} = \text{total} - \text{directo}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-label="1"></a>directo <span class="ot">&lt;-</span> <span class="fu">c</span>(epsilon <span class="sc">%*%</span> D)</span>
<span id="cb35-2"><a aria-label="2"></a>total <span class="ot">&lt;-</span> <span class="fu">c</span>(epsilon <span class="sc">%*%</span> Treq)</span>
<span id="cb35-3"><a aria-label="3"></a></span>
<span id="cb35-4"><a aria-label="4"></a><span class="fu">data.frame</span>(</span>
<span id="cb35-5"><a aria-label="5"></a>  <span class="at">producto =</span> productos,</span>
<span id="cb35-6"><a aria-label="6"></a>  <span class="at">directo =</span> <span class="fu">round</span>(directo, <span class="dv">3</span>),</span>
<span id="cb35-7"><a aria-label="7"></a>  <span class="at">total =</span> <span class="fu">round</span>(total, <span class="dv">3</span>),</span>
<span id="cb35-8"><a aria-label="8"></a>  <span class="at">indirecto =</span> <span class="fu">round</span>(total <span class="sc">-</span> directo, <span class="dv">3</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     producto directo total indirecto
1      ganado   0.500 1.218     0.718
2      hierro   0.800 1.031     0.231
3       leche   0.411 1.226     0.814
4       queso   0.310 1.234     0.924
5 combustible   0.796 1.037     0.241
6       acero   0.400 1.699     1.299
7       autos   0.400 1.699     1.299
8  publicidad   0.100 1.139     1.039</code></pre>
</div>
</div>
</div></div>
</section>
<section id="multiplicadores-lectura" class="slide level2">
<h2>Multiplicadores: qué significan y cómo se comparan</h2>
<ul>
<li><strong>El orden cambia.</strong> Hierro y combustible tienen el mayor efecto directo (0.80), porque los produce la industria más intensiva (minas), pero su total es de los más bajos (cerca de 1.03). Acero y autos tienen un efecto directo de 0.40 y el mayor total (1.70).</li>
<li><strong>Lo indirecto domina en cadenas largas.</strong> Acero y autos dependen de insumos intensivos en emisiones (combustible, producido por minas), y el 76% de su multiplicador es indirecto. En publicidad, de intensidad directa baja (0.10), el 91% es indirecto.</li>
<li><strong>Mismos fabricantes, mismo multiplicador.</strong> Acero y autos solo los produce la industria de manufacturas, y <span class="math inline">\(\mathbf{T}\)</span> trata igual a todo lo que produce una industria. Si se quieren distinguir, hace falta información que separe las tecnologías de cada producto.</li>
</ul>
<p>Comparar solo la intensidad directa subestima los productos con cadenas de insumos largas.</p>
</section>
<section id="bibliografía" class="slide level2 theme-content smaller scrollable">
<h2>Bibliografía</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-millerblair2022" class="csl-entry" role="listitem">
Miller, R. E. y Blair, P. D. (2022). <em>Input-Output Analysis: Foundations and Extensions</em> (3.ª ed.). Cambridge University Press. <a href="https://doi.org/10.1017/9781108676212">https://doi.org/10.1017/9781108676212</a>
</div>
<div id="ref-sna2009" class="csl-entry" role="listitem">
United Nations. (2009). <em>System of National Accounts 2008</em>. United Nations.
</div>
</div>
</section>
<section id="section" class="slide level2 theme-blank center">
<h2></h2>
<div class="columns">
<div class="column" style="width:15%;">

</div><div class="column" style="width:70%;">
<div style="text-align: center">
<p><span style="font-size:2.2em;color:#204B92;">¡Gracias!</span></p>
<p><span style="font-size:1.2em;"><strong>Renato Vargas</strong></span></p>
<p><span style="font-size:0.9em;"><a href="https://renatovargas.com/">LinkedIn</a> | <a href="https://renatovargas.com/">website</a></span></p>
</div>
</div><div class="column" style="width:15%;">

</div></div>
</section>
<section id="anexo" class="slide level2 theme-content">
<h2>Anexo: una matriz cuadrada equivalente</h2>
<p>Los mismos resultados se obtienen con una sola matriz cuadrada que pone industrias y productos juntos, en ese orden, en filas y columnas. Los cuadrantes de industria con industria y de producto con producto son ceros:</p>
<p><span class="math display">\[
\mathbf{Z}^* = \begin{bmatrix} \mathbf{0} &amp; \bbox[#FFF0A6,3px]{\mathbf{V}} \\ \bbox[#B5E6A2,3px]{\mathbf{U}} &amp; \mathbf{0} \end{bmatrix} \qquad \mathbf{f}^* = \begin{bmatrix} \mathbf{0} \\ \bbox[#F2CEEF,3px]{\mathbf{f}} \end{bmatrix} \qquad \mathbf{x}^* = \begin{bmatrix} \bbox[#A6C9EC,3px]{\mathbf{x}} \\ \bbox[#A6C9EC,3px]{\mathbf{q}} \end{bmatrix}
\]</span></p>
<p>Con el modelo de siempre, <span class="math inline">\(\mathbf{A}^* = \mathbf{Z}^*\widehat{\mathbf{x}^*}^{-1}\)</span>, que resulta ser la matriz de coeficientes del sistema particionado:</p>
<p><span class="math display">\[
\mathbf{I} - \mathbf{A}^* = \begin{bmatrix} \mathbf{I} &amp; -\mathbf{D} \\ -\mathbf{B} &amp; \mathbf{I} \end{bmatrix} \qquad (\mathbf{I} - \mathbf{A}^*)^{-1} = \begin{bmatrix} (\mathbf{I}-\mathbf{D}\mathbf{B})^{-1} &amp; \bbox[#F7C7AC,3px]{(\mathbf{I}-\mathbf{D}\mathbf{B})^{-1}\mathbf{D}} \\ \mathbf{B}(\mathbf{I}-\mathbf{D}\mathbf{B})^{-1} &amp; \mathbf{I} + \mathbf{B}(\mathbf{I}-\mathbf{D}\mathbf{B})^{-1}\mathbf{D} \end{bmatrix}
\]</span></p>
<p>El bloque superior derecho es <span class="bg-L"><span class="math inline">\(\mathbf{T}\)</span></span>. Al multiplicar por <span class="math inline">\(\mathbf{f}^*\)</span> salen <span class="math inline">\(\mathbf{x}\)</span> y también <span class="math inline">\(\mathbf{q}\)</span>.</p>
</section>
<section id="anexo-r" class="slide level2">
<h2>Anexo: verificación en R</h2>
<p>Se arma <span class="math inline">\(\mathbf{Z}^*\)</span> por bloques, se aplica el modelo de siempre y se compara el bloque superior derecho con <span class="bg-L"><span class="math inline">\(\mathbf{T}\)</span></span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-label="1"></a>nI <span class="ot">&lt;-</span> <span class="fu">nrow</span>(V)</span>
<span id="cb37-2"><a aria-label="2"></a>nP <span class="ot">&lt;-</span> <span class="fu">ncol</span>(V)</span>
<span id="cb37-3"><a aria-label="3"></a></span>
<span id="cb37-4"><a aria-label="4"></a>Zs <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb37-5"><a aria-label="5"></a>  <span class="fu">cbind</span>(<span class="fu">matrix</span>(<span class="dv">0</span>, nI, nI), V),</span>
<span id="cb37-6"><a aria-label="6"></a>  <span class="fu">cbind</span>(U, <span class="fu">matrix</span>(<span class="dv">0</span>, nP, nP)))</span>
<span id="cb37-7"><a aria-label="7"></a></span>
<span id="cb37-8"><a aria-label="8"></a>fs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">0</span>, nI), f)</span>
<span id="cb37-9"><a aria-label="9"></a>xs <span class="ot">&lt;-</span> <span class="fu">c</span>(x, q)</span>
<span id="cb37-10"><a aria-label="10"></a></span>
<span id="cb37-11"><a aria-label="11"></a>As <span class="ot">&lt;-</span> Zs <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">diag</span>(xs))</span>
<span id="cb37-12"><a aria-label="12"></a>Ls <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">diag</span>(nI <span class="sc">+</span> nP) <span class="sc">-</span> As)</span>
<span id="cb37-13"><a aria-label="13"></a></span>
<span id="cb37-14"><a aria-label="14"></a><span class="co"># El bloque superior derecho es T</span></span>
<span id="cb37-15"><a aria-label="15"></a>Tbloque <span class="ot">&lt;-</span> Ls[<span class="dv">1</span><span class="sc">:</span>nI, (nI <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>(nI <span class="sc">+</span> nP)]</span>
<span id="cb37-16"><a aria-label="16"></a><span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">unname</span>(Tbloque), <span class="fu">unname</span>(Treq)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-label="1"></a><span class="co"># Reproduce x y q</span></span>
<span id="cb39-2"><a aria-label="2"></a><span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">c</span>(Ls <span class="sc">%*%</span> fs), xs))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Hay que cuidar al agregar: <span class="math inline">\(\mathbf{x}^*\)</span> mezcla producción de industrias y de productos, así que sumarlo cuenta dos veces.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Matrices rectangulares de insumo-producto</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>