<!DOCTYPE html>
<html lang="es"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Renato Vargas">
  <title>Perú HC – Extensión ambiental y multiplicadores</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-5452d8afb4ea365b311360b8f54a7c55.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script>
    window.MathJax = {
      "HTML-CSS": { scale: 80 }
    };
  </script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="theme-title center" data-state="sin-footer">
  <h1 class="title">Extensión ambiental y multiplicadores</h1>
  <p class="subtitle">Emisiones de dióxido de carbono en el modelo de insumo-producto</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Renato Vargas
</div>
        <p class="quarto-title-affiliation">
            Economista / Consultor FMI
          </p>
    </div>
</div>

</section>
<section id="temas-a-tratar" class="slide level2 theme-content">
<h2>Temas a tratar</h2>
<ol type="1">
<li>La extensión ambiental básica.</li>
<li>Multiplicadores de producto.</li>
<li>Multiplicadores de emisiones.</li>
</ol>
</section>
<section id="section" class="slide level2 theme-blank center">
<h2></h2>
<div style="text-align: center">
<p>Descargar el archivo de ejemplo:</p>
<p><a href="../datos/ejemplos/modelo-insumo-producto.xlsx" class="button" download="modelo-insumo-producto.xlsx">modelo-insumo-producto.xlsx</a></p>
</div>
</section>
<section id="modelo-basico" class="slide level2">
<h2>El modelo básico con emisiones</h2>
<p>Una economía de dos sectores, agricultura y manufacturas, se describe con un cuadro de flujos entre industrias <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>. Cada fila muestra a quién vende un sector; cada columna muestra qué compra para producir. Se agrega una fila con las emisiones de dióxido de carbono (<span class="math inline">\(CO_2\)</span>) de cada sector, en toneladas.</p>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Agricultura</th>
<th style="text-align: right;">Manufacturas</th>
<th style="text-align: right;">Demanda final</th>
<th style="text-align: right;">Producto total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agricultura</td>
<td style="text-align: right;"><span class="bg-Z">150</span></td>
<td style="text-align: right;"><span class="bg-Z">500</span></td>
<td style="text-align: right;"><span class="bg-f">350</span></td>
<td style="text-align: right;"><span class="bg-x">1000</span></td>
</tr>
<tr class="even">
<td>Manufacturas</td>
<td style="text-align: right;"><span class="bg-Z">200</span></td>
<td style="text-align: right;"><span class="bg-Z">100</span></td>
<td style="text-align: right;"><span class="bg-f">1700</span></td>
<td style="text-align: right;"><span class="bg-x">2000</span></td>
</tr>
<tr class="odd">
<td>Pagos a factores</td>
<td style="text-align: right;">650</td>
<td style="text-align: right;">1400</td>
<td style="text-align: right;">1100</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>Total insumos</td>
<td style="text-align: right;"><span class="bg-x">1000</span></td>
<td style="text-align: right;"><span class="bg-x">2000</span></td>
<td style="text-align: right;">3150</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Emisiones de <span class="math inline">\(CO_2\)</span> (t)</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<ul>
<li>Los flujos entre industrias forman la matriz <span class="bg-Z"><span class="math inline">\(\mathbf{Z}\)</span></span>.</li>
<li>La demanda final forma el vector <span class="bg-f"><span class="math inline">\(\mathbf{f}\)</span></span>.</li>
<li>El producto total forma el vector <span class="bg-x"><span class="math inline">\(\mathbf{x}\)</span></span>, que aparece como columna y también como fila.</li>
<li>Las emisiones por sector forman el vector <span class="math inline">\(\mathbf{e}\)</span>, que es la extensión ambiental del modelo.</li>
</ul>
</section>
<section id="recordatorio" class="slide level2">
<h2>Recordemos el modelo de insumo-producto</h2>
<p>Para cada sector, el producto total es lo que se vende a otros sectores más la demanda final, con <span class="math inline">\(\mathbf{i}\)</span> un vector de unos que suma las filas de <span class="math inline">\(\mathbf{Z}\)</span>:</p>
<p><span class="math display">\[
\bbox[#A6C9EC,3px]{\mathbf{x}} = \mathbf{Z}\mathbf{i} + \bbox[#F2CEEF,3px]{\mathbf{f}}
\]</span></p>
<p>Los coeficientes técnicos son la compra por unidad de producto del sector comprador, <span class="math inline">\(\mathbf{A} = \mathbf{Z}\widehat{\mathbf{x}}^{-1}\)</span>, con <span class="math inline">\(\widehat{\mathbf{x}}\)</span> la matriz diagonal de <span class="math inline">\(\mathbf{x}\)</span>. Con ellos el modelo se resuelve para el producto:</p>
<p><span class="math display">\[
\bbox[#A6C9EC,3px]{\mathbf{x}} = \bbox[#F7C7AC,3px]{\mathbf{L}}\bbox[#F2CEEF,3px]{\mathbf{f}} \qquad \text{con} \qquad \bbox[#F7C7AC,3px]{\mathbf{L}} = (\mathbf{I} - \mathbf{A})^{-1}
\]</span></p>
<p><span class="bg-L"><span class="math inline">\(\mathbf{L}\)</span></span> es la matriz inversa de Leontief: dice cuánto debe producir cada sector, directa e indirectamente, para satisfacer la demanda final. En el ejemplo:</p>
<p><span class="math display">\[
\mathbf{A} = \begin{bmatrix} 0.15 &amp; 0.25 \\ 0.20 &amp; 0.05 \end{bmatrix} \qquad \bbox[#F7C7AC,3px]{\mathbf{L}} = \begin{bmatrix} 1.2541 &amp; 0.3300 \\ 0.2640 &amp; 1.1221 \end{bmatrix}
\]</span></p>
</section>
<section id="implementación-del-modelo" class="slide level2">
<h2>Implementación del modelo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a>sectores <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Agricultura"</span>, <span class="st">"Manufacturas"</span>)</span>
<span id="cb1-2"><a aria-label="2"></a></span>
<span id="cb1-3"><a aria-label="3"></a>Z <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">150</span>, <span class="dv">500</span>, <span class="dv">200</span>, <span class="dv">100</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-4"><a aria-label="4"></a><span class="fu">colnames</span>(Z) <span class="ot">&lt;-</span> sectores</span>
<span id="cb1-5"><a aria-label="5"></a><span class="fu">rownames</span>(Z) <span class="ot">&lt;-</span> sectores</span>
<span id="cb1-6"><a aria-label="6"></a></span>
<span id="cb1-7"><a aria-label="7"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1000</span>, <span class="dv">2000</span>)</span>
<span id="cb1-8"><a aria-label="8"></a>f <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">350</span>, <span class="dv">1700</span>)</span>
<span id="cb1-9"><a aria-label="9"></a></span>
<span id="cb1-10"><a aria-label="10"></a>A <span class="ot">&lt;-</span> Z <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">diag</span>(x))</span>
<span id="cb1-11"><a aria-label="11"></a>L <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">diag</span>(<span class="fu">dim</span>(A)[<span class="dv">1</span>]) <span class="sc">-</span> A)</span>
<span id="cb1-12"><a aria-label="12"></a>L</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Agricultura Manufacturas
[1,]   1.2541254     0.330033
[2,]   0.2640264     1.122112</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="co"># Comprobación: L por f devuelve el producto total</span></span>
<span id="cb3-2"><a aria-label="2"></a>L <span class="sc">%*%</span> f</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]
[1,] 1000
[2,] 2000</code></pre>
</div>
</div>
</div></div>
</section>
<section id="extension-ambiental" class="slide level2">
<h2>La extensión ambiental básica</h2>
<p>Otros impactos, como el uso de agua o las emisiones, se pueden obtener a través de coeficientes, del mismo modo que los coeficientes técnicos <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>.</p>
<p>La idea es que cada sector emite una cantidad proporcional a lo que produce, igual que compra insumos en proporción a lo que produce.</p>
<p>Si <span class="math inline">\(\mathbf{e}\)</span> es el vector de emisiones directas de cada sector (las que ocurren dentro del propio sector), el coeficiente de emisiones es la cantidad emitida por unidad monetaria de producto. También se le llama intensidad de emisiones: mide qué tan intensivo en emisiones es cada sector.</p>
<p><span class="math display">\[
\varepsilon_j = \frac{e_j}{x_j} \qquad \Longleftrightarrow \qquad \boldsymbol{\varepsilon}' = \mathbf{e}'\widehat{\mathbf{x}}^{-1}
\]</span></p>
</section>
<section id="emisiones-totales" class="slide level2">
<h2>Emisiones totales y matriz diagonal de coeficientes</h2>
<p>Despejando <span class="math inline">\(\mathbf{e}\)</span> del coeficiente, las emisiones son el coeficiente de cada sector por su producto. Para escribirlo en forma matricial se convierte el vector de coeficientes en una matriz diagonal, <span class="math inline">\(\widehat{\boldsymbol{\varepsilon}}\)</span>, de modo que cada sector conserve su propia fila:</p>
<p><span class="math display">\[
\mathbf{e} = \widehat{\boldsymbol{\varepsilon}}\,\bbox[#A6C9EC,3px]{\mathbf{x}}
\quad \Rightarrow \quad
\begin{pmatrix} e_1 \\ e_2 \end{pmatrix} =
\begin{bmatrix} \varepsilon_1 &amp; 0 \\ 0 &amp; \varepsilon_2 \end{bmatrix}
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix} =
\begin{pmatrix} \varepsilon_1 x_1 \\ \varepsilon_2 x_2 \end{pmatrix}
\]</span></p>
<p>Esta ecuación parte del producto, pero las preguntas de política suelen partir de la demanda final. Para eso hace falta pasar de <span class="math inline">\(\mathbf{x}\)</span> a <span class="math inline">\(\mathbf{f}\)</span>.</p>
</section>
<section id="emisiones-demanda" class="slide level2">
<h2>Emisiones a partir de la demanda final</h2>
<p>Como sabemos que <span class="math inline">\(\mathbf{x} = \mathbf{L}\mathbf{f}\)</span>, se sustituye en la ecuación anterior:</p>
<p><span class="math display">\[
\begin{pmatrix} e_1 \\ e_2 \end{pmatrix} =
\begin{bmatrix} \varepsilon_1 &amp; 0 \\ 0 &amp; \varepsilon_2 \end{bmatrix}
\bbox[#F7C7AC,3px]{\begin{bmatrix} l_{11} &amp; l_{12} \\ l_{21} &amp; l_{22} \end{bmatrix}}
\bbox[#F2CEEF,3px]{\begin{pmatrix} f_1 \\ f_2 \end{pmatrix}}
\]</span></p>
<p>Premultiplicar por una matriz diagonal multiplica cada fila <span class="math inline">\(i\)</span> de <span class="bg-L"><span class="math inline">\(\mathbf{L}\)</span></span> por el coeficiente <span class="math inline">\(\varepsilon_i\)</span> <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>:</p>
<p><span class="math display">\[
\begin{pmatrix} e_1 \\ e_2 \end{pmatrix} =
\begin{bmatrix} \varepsilon_1 l_{11} &amp; \varepsilon_1 l_{12} \\ \varepsilon_2 l_{21} &amp; \varepsilon_2 l_{22} \end{bmatrix}
\bbox[#F2CEEF,3px]{\begin{pmatrix} f_1 \\ f_2 \end{pmatrix}}
\qquad \Longleftrightarrow \qquad
\mathbf{e} = \widehat{\boldsymbol{\varepsilon}}\,\bbox[#F7C7AC,3px]{\mathbf{L}}\,\mathbf{f}
\]</span></p>
<p>El impacto se calcula a partir de la demanda final, porque <span class="bg-L"><span class="math inline">\(\mathbf{L}\)</span></span><span class="math inline">\(\mathbf{f}\)</span> es el producto que la economía debe generar para satisfacerla.</p>
</section>
<section id="emisiones-de-dióxido-de-carbono-por-sector" class="slide level2">
<h2>Emisiones de dióxido de carbono por sector</h2>
<p>Imaginemos que las emisiones de dióxido de carbono (<span class="math inline">\(CO_2\)</span>), en toneladas, son 300 para agricultura y 500 para manufacturas.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{e}' = \begin{bmatrix} 300 &amp; 500 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a>eprima <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">300</span>, <span class="dv">500</span>)</span>
<span id="cb5-2"><a aria-label="2"></a><span class="fu">names</span>(eprima) <span class="ot">&lt;-</span> sectores</span>
<span id="cb5-3"><a aria-label="3"></a>eprima</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Agricultura Manufacturas 
         300          500 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="coeficientes-de-emisiones" class="slide level2">
<h2>Coeficientes de emisiones</h2>
<p>El coeficiente se mide en toneladas de <span class="math inline">\(CO_2\)</span> por unidad monetaria de producto.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\boldsymbol{\varepsilon}' = \mathbf{e}'\widehat{\mathbf{x}}^{-1} = \begin{bmatrix} 0.30 &amp; 0.25 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<p>En álgebra matricial se transpone el vector de emisiones y se posmultiplica por la inversa de la diagonal de <span class="math inline">\(\mathbf{x}\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a>epsilon <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">as.matrix</span>(eprima)) <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">diag</span>(x))</span>
<span id="cb7-2"><a aria-label="2"></a>epsilon</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]  0.3 0.25</code></pre>
</div>
</div>
<p>También se puede usar la regla de reciclaje de R y dividir directamente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a>eprima <span class="sc">/</span> x</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Agricultura Manufacturas 
        0.30         0.25 </code></pre>
</div>
</div>
</div></div>
</section>
<section id="emisiones-calculadas-desde-la-demanda-final" class="slide level2">
<h2>Emisiones calculadas desde la demanda final</h2>
<p>Con los coeficientes y la matriz de Leontief, la demanda final reproduce las emisiones del cuadro. El resultado es el vector de emisiones de cada sector productor, sin importar para qué demanda se producen.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{e} = \widehat{\boldsymbol{\varepsilon}}\,\bbox[#F7C7AC,3px]{\mathbf{L}}\,\bbox[#F2CEEF,3px]{\mathbf{f}} = \begin{bmatrix} 300 \\ 500 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a>e <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">c</span>(epsilon)) <span class="sc">%*%</span> L <span class="sc">%*%</span> f</span>
<span id="cb11-2"><a aria-label="2"></a><span class="fu">rownames</span>(e) <span class="ot">&lt;-</span> sectores</span>
<span id="cb11-3"><a aria-label="3"></a><span class="fu">colnames</span>(e) <span class="ot">&lt;-</span> <span class="st">"Toneladas de CO2"</span></span>
<span id="cb11-4"><a aria-label="4"></a>e</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Toneladas de CO2
Agricultura               300
Manufacturas              500</code></pre>
</div>
</div>
</div></div>
</section>
<section id="multiplicadores" class="slide level2">
<h2>Multiplicadores: definición</h2>
<p>Un multiplicador responde una pregunta simple: qué pasa en toda la economía cuando la demanda final de un solo sector sube una unidad. El multiplicador responde una pregunta más simple: qué pasa en toda la economía cuando la demanda final de un solo sector sube una unidad.</p>
<p>El multiplicador de producto del sector <span class="math inline">\(j\)</span> es el valor de producción, en todos los sectores de la economía, que se necesita para satisfacer una unidad monetaria de demanda final de los productos de ese sector <span class="citation" data-cites="millerblair2022">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Miller y Blair, 2022</a>)</span>.</p>
<p>El multiplicador simple compara dos cambios en el producto:</p>
<ul>
<li>El cambio directo es la unidad monetaria adicional de demanda final del sector <span class="math inline">\(j\)</span>.</li>
<li>El cambio indirecto es la producción adicional, en todos los sectores, que hace falta para que circulen los insumos entre sectores.</li>
</ul>
<p>El multiplicador es la razón entre el cambio total en el producto y el cambio directo. Como numerador y denominador están en dinero, no tiene unidades de medida.</p>
</section>
<section id="multiplicadores-un-sector-a-la-vez" class="slide level2">
<h2>Multiplicadores: un sector a la vez</h2>
<p>Partimos de los resultados que ya tenemos:</p>
<p><span class="math display">\[
\mathbf{A} = \begin{bmatrix} 0.15 &amp; 0.25 \\ 0.20 &amp; 0.05 \end{bmatrix} \qquad \bbox[#F7C7AC,3px]{\mathbf{L}} = \begin{bmatrix} 1.2541 &amp; 0.3300 \\ 0.2640 &amp; 1.1221 \end{bmatrix}
\]</span></p>
<p>Para aislar un sector se usa un vector de demanda adicional con un 1 en ese sector y ceros en los demás. Primero, la demanda adicional de solo el primer sector:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\Delta\mathbf{f}_1 = \begin{bmatrix} 1 \\ 0 \end{bmatrix} \qquad \Delta\mathbf{x}_1 = \bbox[#F7C7AC,3px]{\mathbf{L}}\,\Delta\mathbf{f}_1 = \begin{bmatrix} 1.2541 \\ 0.2640 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a>L</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Agricultura Manufacturas
[1,]   1.2541254     0.330033
[2,]   0.2640264     1.122112</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-label="1"></a>deltaf1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb15-2"><a aria-label="2"></a>L <span class="sc">%*%</span> deltaf1</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]
[1,] 1.2541254
[2,] 0.2640264</code></pre>
</div>
</div>
</div></div>
</section>
<section id="multiplicadores-interpretación" class="slide level2">
<h2>Multiplicadores: interpretación</h2>
<p>En el primer caso hay una producción adicional de USD 1.254 del sector 1 y de USD 0.264 del sector 2.</p>
<ul>
<li>El 1 en el 1.254 es lo que se necesita para satisfacer la demanda; los USD 0.254 restantes sirven para mover los insumos entre sectores.</li>
<li>Los USD 0.264 del sector 2 son para compras entre sectores exclusivamente.</li>
</ul>
<p>El multiplicador del sector 1 es la suma de los elementos de la columna <span class="math inline">\(\Delta\mathbf{x}_1\)</span>, dividida entre la unidad adicional de demanda:</p>
<p><span class="math display">\[
m_{o1} = \frac{1.254 + 0.264}{1} = \frac{\text{USD } 1.518}{\text{USD } 1} = 1.518
\]</span></p>
</section>
<section id="multiplicadores-el-segundo-sector" class="slide level2">
<h2>Multiplicadores: el segundo sector</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\Delta\mathbf{f}_2 = \begin{bmatrix} 0 \\ 1 \end{bmatrix} \qquad \Delta\mathbf{x}_2 = \bbox[#F7C7AC,3px]{\mathbf{L}}\,\Delta\mathbf{f}_2 = \begin{bmatrix} 0.3300 \\ 1.1221 \end{bmatrix}
\]</span></p>
<p><span class="math display">\[
m_{o2} = 0.330 + 1.122 = 1.452
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-label="1"></a>deltaf2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb17-2"><a aria-label="2"></a>L <span class="sc">%*%</span> deltaf2</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 0.330033
[2,] 1.122112</code></pre>
</div>
</div>
</div></div>
</section>
<section id="multiplicadores-para-todos-los-sectores-vectores-sumatorios" class="slide level2">
<h2>Multiplicadores para todos los sectores: vectores sumatorios</h2>
<p>Sumar la columna de <span class="bg-L"><span class="math inline">\(\mathbf{L}\)</span></span> de cada sector, uno por uno, no escala a economías con decenas de sectores. Para hacerlo con todos a la vez se usa un vector sumatorio <span class="math inline">\(\mathbf{i}\)</span>: un vector de unos que, al premultiplicar una matriz, suma sus columnas.</p>
<p><span class="math display">\[
\mathbf{m}_o' = \mathbf{i}'\bbox[#F7C7AC,3px]{\mathbf{L}}, \qquad m_{oj} = \sum_{i=1}^{n} l_{ij}
\]</span></p>
<p>Estos multiplicadores son muy útiles porque indican en qué sectores una inversión tiene mayor impacto en la economía.</p>
</section>
<section id="multiplicadores-en-la-práctica" class="slide level2">
<h2>Multiplicadores: en la práctica</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{i}' = \begin{bmatrix} 1 &amp; 1 \end{bmatrix} \qquad \mathbf{m}_o' = \mathbf{i}'\bbox[#F7C7AC,3px]{\mathbf{L}} = \begin{bmatrix} 1.518 &amp; 1.452 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-label="1"></a><span class="co"># Dimensiones de L</span></span>
<span id="cb19-2"><a aria-label="2"></a><span class="fu">dim</span>(L)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-label="1"></a><span class="co"># Vector sumatorio de largo apropiado</span></span>
<span id="cb21-2"><a aria-label="2"></a>i <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">dim</span>(L)[<span class="dv">1</span>])</span>
<span id="cb21-3"><a aria-label="3"></a></span>
<span id="cb21-4"><a aria-label="4"></a><span class="co"># Multiplicadores</span></span>
<span id="cb21-5"><a aria-label="5"></a>mo <span class="ot">&lt;-</span> i <span class="sc">%*%</span> L</span>
<span id="cb21-6"><a aria-label="6"></a>mo</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Agricultura Manufacturas
[1,]    1.518152     1.452145</code></pre>
</div>
</div>
</div></div>
</section>
<section id="multiplicadores-emisiones" class="slide level2">
<h2>Multiplicadores de emisiones: planteamiento</h2>
<p>Los multiplicadores de producto miden dinero. Para medir emisiones se aplica la misma idea a la matriz <span class="math inline">\(\widehat{\boldsymbol{\varepsilon}}\mathbf{L}\)</span> de la sección anterior. La llamamos <span class="math inline">\(\mathbf{M}_e\)</span>:</p>
<p><span class="math display">\[
\begin{pmatrix} e_1 \\ e_2 \end{pmatrix} =
\bbox[#E8E8E8,3px]{\begin{bmatrix} m^e_{11} &amp; m^e_{12} \\ m^e_{21} &amp; m^e_{22} \end{bmatrix}}
\bbox[#F2CEEF,3px]{\begin{pmatrix} f_1 \\ f_2 \end{pmatrix}}
\qquad \text{con} \qquad m^e_{ij} = \varepsilon_i\, l_{ij}
\]</span></p>
<p><span class="math display">\[
\mathbf{M}_e = \widehat{\boldsymbol{\varepsilon}}\,\bbox[#F7C7AC,3px]{\mathbf{L}} \qquad \Longrightarrow \qquad \mathbf{e} = \mathbf{M}_e\,\mathbf{f}
\]</span></p>
<p>El elemento <span class="math inline">\(m^e_{ij}\)</span> muestra las toneladas de <span class="math inline">\(CO_2\)</span> que se emiten en el sector <span class="math inline">\(i\)</span>, directa e indirectamente, cuando se necesita una unidad monetaria adicional de producto del sector <span class="math inline">\(j\)</span> para satisfacer la demanda final.</p>
</section>
<section id="multiplicadores-de-emisiones-interpretación" class="slide level2">
<h2>Multiplicadores de emisiones: interpretación</h2>
<p><span class="math inline">\(\mathbf{M}_e\)</span> es interesante por sí misma, porque muestra qué sectores generan más o menos emisiones por unidad de demanda final.</p>
<ul>
<li>Cada columna <span class="math inline">\(j\)</span> de <span class="math inline">\(\mathbf{M}_e\)</span> reparte entre los sectores las emisiones que provoca una unidad monetaria de demanda final del sector <span class="math inline">\(j\)</span>.</li>
<li>La suma de esa columna es el multiplicador de emisiones del sector <span class="math inline">\(j\)</span>: las emisiones totales, en toda la economía, por unidad monetaria de demanda final de sus productos. En notación matricial es <span class="math inline">\(\mathbf{i}'\mathbf{M}_e = \mathbf{i}'\widehat{\boldsymbol{\varepsilon}}\mathbf{L} = \boldsymbol{\varepsilon}'\mathbf{L}\)</span>, porque sumar las filas de una matriz diagonal devuelve su diagonal.</li>
</ul>
<p>A diferencia de <span class="math inline">\(\mathbf{m}_o\)</span>, este multiplicador sí tiene unidades de medida: toneladas de <span class="math inline">\(CO_2\)</span> por unidad monetaria. Es la huella de carbono por unidad monetaria de demanda final de cada sector, y sirve para compararlos entre sí.</p>
</section>
<section id="multiplicadores-de-emisiones-y-huella-de-carbono" class="slide level2">
<h2>Multiplicadores de emisiones y huella de carbono</h2>
<p>Sumar las emisiones asociadas a la demanda final de un país, dondequiera que ocurran, da su huella de carbono.</p>
<ul>
<li>Las cuentas de emisiones atmosféricas registran las emisiones de las unidades residentes de una economía, sin importar dónde ocurran, con los mismos principios y sectores que las cuentas nacionales <span class="citation" data-cites="eurostat2015">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Eurostat, 2015</a>)</span>.</li>
<li>Los modelos de insumo-producto trasladan esas emisiones a la demanda final que las origina, lo que distingue las emisiones basadas en la producción de las basadas en la demanda final <span class="citation" data-cites="yamano2020">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Yamano y Guilhoto, 2020</a>)</span>.</li>
</ul>
</section>
<section id="huella-de-carbono-alcance-del-ejemplo" class="slide level2">
<h2>Huella de carbono: alcance del ejemplo</h2>
<ul>
<li>Nuestro ejemplo es de un solo país y no incluye importaciones.</li>
<li>Con él se puede medir la huella de carbono de la demanda final de productos de sectores específicos, agricultura y manufacturas, con las emisiones que su producción genera, directa e indirectamente, dentro de la economía.</li>
<li>En un ejemplo real (como el de la MIP de Perú), la demanda final se desagrega, por ejemplo en consumo, inversión y exportaciones, y hay una fila de importaciones.</li>
<li>Con las exportaciones se separan las emisiones incorporadas en la demanda interna de las incorporadas en las exportaciones, sin identificar el destino.</li>
<li>Las importaciones suelen estimarse suponiendo que se producen con la tecnología del propio país, un supuesto que debe interpretarse con cautela <span class="citation" data-cites="eurostat2015">(<a href="#/bibliografía" role="doc-biblioref" onclick="">Eurostat, 2015</a>)</span>; la alternativa es contar con datos del exterior.</li>
</ul>
</section>
<section id="multiplicadores-de-emisiones-en-la-práctica" class="slide level2">
<h2>Multiplicadores de emisiones: en la práctica</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
\mathbf{M}_e = \widehat{\boldsymbol{\varepsilon}}\,\bbox[#F7C7AC,3px]{\mathbf{L}} = \begin{bmatrix} 0.3762 &amp; 0.0990 \\ 0.0660 &amp; 0.2805 \end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\mathbf{i}'\mathbf{M}_e = \begin{bmatrix} 0.4422 &amp; 0.3795 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-label="1"></a>Me <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">c</span>(epsilon)) <span class="sc">%*%</span> L</span>
<span id="cb23-2"><a aria-label="2"></a><span class="fu">rownames</span>(Me) <span class="ot">&lt;-</span> sectores</span>
<span id="cb23-3"><a aria-label="3"></a><span class="fu">colnames</span>(Me) <span class="ot">&lt;-</span> sectores</span>
<span id="cb23-4"><a aria-label="4"></a>Me</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Agricultura Manufacturas
Agricultura    0.3762376    0.0990099
Manufacturas   0.0660066    0.2805281</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a><span class="co"># Multiplicadores de emisiones</span></span>
<span id="cb25-2"><a aria-label="2"></a><span class="fu">colSums</span>(Me)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Agricultura Manufacturas 
   0.4422442    0.3795380 </code></pre>
</div>
</div>
<p>Las emisiones por unidad monetaria de demanda final son algo mayores para agricultura que para manufacturas.</p>
</div></div>
</section>
<section id="huella-toneladas" class="slide level2">
<h2>Huella de carbono en toneladas</h2>
<p>El multiplicador de emisiones está por unidad monetaria. Para obtener la huella total de cada sector, en toneladas, se multiplica por su demanda final <span class="bg-f"><span class="math inline">\(\mathbf{f}\)</span></span>. Manufacturas tiene un multiplicador menor que agricultura, pero su huella total es mayor porque su demanda final también lo es.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emphasis">Notación</span></p>
<p><span class="math display">\[
h_j = \left(\boldsymbol{\varepsilon}'\bbox[#F7C7AC,3px]{\mathbf{L}}\right)_j \bbox[#F2CEEF,3px]{f_j}
\]</span></p>
<p><span class="math display">\[
\mathbf{h}' = \boldsymbol{\varepsilon}'\bbox[#F7C7AC,3px]{\mathbf{L}}\,\widehat{\mathbf{f}} = \begin{bmatrix} 154.79 &amp; 645.21 \end{bmatrix}
\]</span></p>
<p><span class="emphasis">En Excel</span></p>
<p>Insertar captura de pantalla de Excel aquí.</p>
</div><div class="column" style="width:50%;">
<p><span class="emphasis">En R</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-label="1"></a>huella <span class="ot">&lt;-</span> epsilon <span class="sc">%*%</span> L <span class="sc">%*%</span> <span class="fu">diag</span>(f)</span>
<span id="cb27-2"><a aria-label="2"></a><span class="fu">colnames</span>(huella) <span class="ot">&lt;-</span> sectores</span>
<span id="cb27-3"><a aria-label="3"></a>huella</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Agricultura Manufacturas
[1,]    154.7855     645.2145</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-label="1"></a><span class="co"># Equivale a multiplicar elemento por elemento</span></span>
<span id="cb29-2"><a aria-label="2"></a><span class="fu">colSums</span>(Me) <span class="sc">*</span> f</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Agricultura Manufacturas 
    154.7855     645.2145 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-label="1"></a><span class="co"># La suma es el total de emisiones del cuadro</span></span>
<span id="cb31-2"><a aria-label="2"></a><span class="fu">sum</span>(huella)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 800</code></pre>
</div>
</div>
</div></div>
</section>
<section id="bibliografía" class="slide level2 theme-content smaller scrollable">
<h2>Bibliografía</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-eurostat2015" class="csl-entry" role="listitem">
Eurostat. (2015). <em>Manual for Air Emissions Accounts</em> (2015.ª ed.). Publications Office of the European Union. <a href="https://doi.org/10.2785/527552">https://doi.org/10.2785/527552</a>
</div>
<div id="ref-millerblair2022" class="csl-entry" role="listitem">
Miller, R. E. y Blair, P. D. (2022). <em>Input-Output Analysis: Foundations and Extensions</em> (3.ª ed.). Cambridge University Press. <a href="https://doi.org/10.1017/9781108676212">https://doi.org/10.1017/9781108676212</a>
</div>
<div id="ref-yamano2020" class="csl-entry" role="listitem">
Yamano, N. y Guilhoto, J. (2020). <em><span>CO2</span> Emissions Embodied in International Trade and Domestic Final Demand: Methodology and Results Using the <span>OECD</span> Inter-Country Input-Output Database</em> (OECD Science, Technology and Industry Working Papers 2020/11). OECD Publishing. <a href="https://doi.org/10.1787/8f2963b8-en">https://doi.org/10.1787/8f2963b8-en</a>
</div>
</div>
</section>
<section id="section-1" class="slide level2 theme-blank center">
<h2></h2>
<div class="columns">
<div class="column" style="width:15%;">

</div><div class="column" style="width:70%;">
<div style="text-align: center">
<p><span style="font-size:2.2em;color:#204B92;">¡Gracias!</span></p>
<p><span style="font-size:1.2em;"><strong>Renato Vargas</strong></span></p>
<p><span style="font-size:0.9em;"><a href="https://renatovargas.com/">LinkedIn</a> | <a href="https://renatovargas.com/">website</a></span></p>
</div>
</div><div class="column" style="width:15%;">

</div></div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Extensión ambiental y multiplicadores</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>